### ISSUE TITLE
Feature: save/load cookies instead of userDataDir

### ISSUE THREAD

**Issue by jackblk** [vogler/free-games-claimer#10]
Currently the script will save userDataDir to reuse next time, this is inefficient and we cannot use it for multiple accounts.

Instead, we can save the cookies and inject the cookie into a new session. This way, we can also start a new container with cookies as env var.

It's working with no captcha when we disable headless, so I think this is the best approach so far.

**Comment by vogler** [comment]
I had that initially: https://github.com/vogler/free-games-claimer/commit/e34a5fed60fa14b55446a38d28cd0027dc28e773
The problem with `storageState` instead of `launchPersistentContext` was that you had to login again much sooner.
I don't know what `launchPersistentContext` saves besides cookies that's relevant here.
Maybe it refreshes the cookies every time but `storageState` only stores them when the browser exits successfully.

**Comment by vogler** [comment]
> Currently the script will save userDataDir to reuse next time, this is inefficient and very hard to dockerize

What's hard about it? Can't you define a shared directory?

> It's working with no captcha when we disable headless, so I think this is the best approach so far.

Can you open a (draft) PR?

**Comment by jackblk** [comment]
Sure, I'll make a draft PR when I finish my approach.

The issue with using `userDataDir` is that, we can't use more than 1 account. It would be nice to make it so it can collect multiple accounts at once, but it is hard to dockerize. Sorry it was confusing, I edited the issue.

**Comment by vogler** [comment]
> The issue with using `userDataDir` is that, we can't use more than 1 account. It would be nice to make it so it can collect multiple accounts at once, but it is hard to dockerize.

Could make the directory an option and have a `userDataDir` for each user.
The `storageState` was some `json` file containing the cookies, so it wouldn't be much different.

> If the cookies only expire after a month, I think it's fine because we are collecting (and refreshing the token) every week.

I think it was more like on every start. But maybe that had to do with playwright not writing out the refreshed cookies.
I'll make a PR with `storageState` added back as an additional option, then we can check.

**Comment by vogler** [comment]
I think the problem may have been that `storageState` just restores cookies, but otherwise it's a fresh browser which probably has some different fingerprint they check and then ask you to login earlier than with `launchPersistentContext`.

**Comment by jackblk** [comment]
Hmm interesting. I think if we run it in Docker, the fingerprint should be identical.

I'll try implementing `storageState` and `sessionStorage`, maybe it will work - TODO.

Refs:

* https://playwright.dev/docs/auth#session-storage
* https://playwright.dev/docs/auth#reuse-authentication-state

**Comment by vogler** [comment]
Closing this. The whole browser profile is ~64MB and needs no extra care for cookie refresh, fingerprinting etc.
