### ISSUE TITLE
Epic Store - claiming games does not work when ran from terminal without X environment

### ISSUE THREAD

**Issue by GothicIII** [vogler/free-games-claimer#100]
Hello there,

I am using debian bookworm with cronjob to claim games instead of docker. The job is running fom the user environment where the nodes are configured with ngx.
It works for prime (gog not tested) but not for epic. The command I issue is:

`node /<path>/free-games-claimer-main/epic-games.js`

The log it produces:

```
started checking epic-games
Signed in as <USERID>
Free games: [
  'https://store.epicgames.com/en-US/p/warhammer-40000-gladius-relics-of-war'
]
Current free game: Warhammer 40,000: Gladius - Relics of War
  Not in library yet! Click GET.
[AggregateError: All promises were rejected] {
  [errors]: [
    locator.click: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for frameLocator('#webPurchaseContainer iframe').locator('button:has-text("I Agree")')
    ============================================================
        at file:///home/<USERID>/free-games-claimer-main/epic-games.js:160:37 {
      name: 'TimeoutError'
    },
    page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('text=Thank you for buying') to be visible
    ============================================================
        at file:///home/<USERID>/free-games-claimer-main/epic-games.js:160:51 {
      name: 'TimeoutError'
    }
  ]
}
  Failed to claim! To avoid captchas try to get a new IP address.
```

If I run the command with SHOW=1 inside a X environment, it works. e.g.

`SHOW=1 node /<path>/free-games-claimer-main/epic-games.js`

I run the server headless to save ressources, so cron does not have an X-environment to interact with.

Is there a way to fix this beside using Docker?

**Comment by vogler** [comment]
See #84. Also should `git pull` since the errors correspond to an older version. Maybe that's enough to fix it for you (as for me) - results vary.

**Comment by GothicIII** [comment]
Sorry, you are right! I forgot that I didn't use git so I was not aware of new versions. 
I'll have results next week when the new game comes up.

Thanks!
