### ISSUE TITLE
The CPU usage of the docker container is abnormal

### ISSUE THREAD

**Issue by niliovo** [vogler/free-games-claimer#103]
c1de268bb8f9   epicfree                     113.86%   555.8MiB / 14.59GiB   3.72%     1.75MB / 1.3MB    517MB / 137MB

**Comment by vogler** [comment]
Do you have some context? Why do you think it is abnormal? If it's the avg cpu load for a run that's only x seconds long and includes the cold start of Firefox, I wouldn't find it abnormal.

**Comment by niliovo** [comment]
> Do you have some context? Why do you think it is abnormal? If it's the avg cpu load for a run that's only x seconds long and includes the cold start of Firefox, I wouldn't find it abnormal.

Thanks for the reply, because this container can take up about 30% of CPU performance and lasts for a long time, other containers don't take up so much, so I don't think it's normal. If it really needs these CPU performances, then I'm wrong.

93fedfcd8c6c   epicfree          0.08%     653.2MiB / 1.884GiB   33.86%    1.81MB / 1.09MB   374MB / 17.2MB    167
93fedfcd8c6c   epicfree          0.08%     653.2MiB / 1.884GiB   33.86%    1.81MB / 1.09MB   374MB / 17.2MB    167
93fedfcd8c6c   epicfree          194.63%   652.8MiB / 1.884GiB   33.84%    1.81MB / 1.09MB   374MB / 17.2MB    167
93fedfcd8c6c   epicfree          194.63%   652.8MiB / 1.884GiB   33.84%    1.81MB / 1.09MB   374MB / 17.2MB    167
93fedfcd8c6c   epicfree          129.49%   653.3MiB / 1.884GiB   33.86%    1.81MB / 1.09MB   374MB / 17.2MB    167
93fedfcd8c6c   epicfree          129.49%   653.3MiB / 1.884GiB   33.86%    1.81MB / 1.09MB   374MB / 17.2MB    167
93fedfcd8c6c   epicfree          216.89%   509.4MiB / 1.884GiB   26.40%    1.81MB / 1.1MB    375MB / 17.2MB    167
93fedfcd8c6c   epicfree          216.89%   509.4MiB / 1.884GiB   26.40%    1.81MB / 1.1MB    375MB / 17.2MB    167
93fedfcd8c6c   epicfree          216.67%   515.2MiB / 1.884GiB   26.71%    1.82MB / 1.1MB    376MB / 17.2MB    167
93fedfcd8c6c   epicfree          216.67%   515.2MiB / 1.884GiB   26.71%    1.82MB / 1.1MB    376MB / 17.2MB    167
93fedfcd8c6c   epicfree          216.67%   515.2MiB / 1.884GiB   26.71%    1.82MB / 1.1MB    376MB / 17.2MB    167
93fedfcd8c6c   epicfree          216.70%   518.3MiB / 1.884GiB   26.87%    1.85MB / 1.12MB   376MB / 18.1MB    167
93fedfcd8c6c   epicfree          216.70%   518.3MiB / 1.884GiB   26.87%    1.85MB / 1.12MB   376MB / 18.1MB    167
93fedfcd8c6c   epicfree          105.83%   518.3MiB / 1.884GiB   26.87%    1.85MB / 1.13MB   376MB / 18.2MB    166
93fedfcd8c6c   epicfree          105.83%   518.3MiB / 1.884GiB   26.87%    1.85MB / 1.13MB   376MB / 18.2MB    166
93fedfcd8c6c   epicfree          140.44%   520.8MiB / 1.884GiB   27.00%    1.85MB / 1.13MB   377MB / 18.2MB    165
93fedfcd8c6c   epicfree          140.44%   520.8MiB / 1.884GiB   27.00%    1.85MB / 1.13MB   377MB / 18.2MB    165
93fedfcd8c6c   epicfree          101.06%   520.7MiB / 1.884GiB   26.99%    1.85MB / 1.13MB   377MB / 18.2MB    165
93fedfcd8c6c   epicfree          101.06%   520.7MiB / 1.884GiB   26.99%    1.85MB / 1.13MB   377MB / 18.2MB    165
93fedfcd8c6c   epicfree          152.02%   520.9MiB / 1.884GiB   27.00%    1.85MB / 1.13MB   377MB / 18.2MB    165
93fedfcd8c6c   epicfree          152.02%   520.9MiB / 1.884GiB   27.00%    1.85MB / 1.13MB   377MB / 18.2MB    165
93fedfcd8c6c   epicfree          152.02%   520.9MiB / 1.884GiB   27.00%    1.85MB / 1.13MB   377MB / 18.2MB    165
93fedfcd8c6c   epicfree          261.29%   528.3MiB / 1.884GiB   27.39%    1.86MB / 1.15MB   378MB / 18.2MB    165
93fedfcd8c6c   epicfree          261.29%   528.3MiB / 1.884GiB   27.39%    1.86MB / 1.15MB   378MB / 18.2MB    165
93fedfcd8c6c   epicfree          373.51%   547.2MiB / 1.884GiB   28.37%    1.91MB / 1.15MB   378MB / 18.2MB    165
93fedfcd8c6c   epicfree          373.51%   547.2MiB / 1.884GiB   28.37%    1.91MB / 1.15MB   378MB / 18.2MB    165
93fedfcd8c6c   epicfree          371.74%   564.3MiB / 1.884GiB   29.25%    1.93MB / 1.16MB   379MB / 19.8MB    165
93fedfcd8c6c   epicfree          371.74%   564.3MiB / 1.884GiB   29.25%    1.93MB / 1.16MB   379MB / 19.8MB    165
93fedfcd8c6c   epicfree          380.64%   570.4MiB / 1.884GiB   29.57%    1.95MB / 1.17MB   382MB / 19.8MB    165
93fedfcd8c6c   epicfree          380.64%   570.4MiB / 1.884GiB   29.57%    1.95MB / 1.17MB   382MB / 19.8MB    165
93fedfcd8c6c   epicfree          380.64%   570.4MiB / 1.884GiB   29.57%    1.95MB / 1.17MB   382MB / 19.8MB    165
93fedfcd8c6c   epicfree          374.42%   585.5MiB / 1.884GiB   30.35%    2MB / 1.19MB      382MB / 19.8MB    166
93fedfcd8c6c   epicfree          374.42%   585.5MiB / 1.884GiB   30.35%    2MB / 1.19MB      382MB / 19.8MB    166
93fedfcd8c6c   epicfree          394.60%   594.4MiB / 1.884GiB   30.81%    2.01MB / 1.19MB   385MB / 19.8MB    167
93fedfcd8c6c   epicfree          394.60%   594.4MiB / 1.884GiB   30.81%    2.01MB / 1.19MB   385MB / 19.8MB    167
93fedfcd8c6c   epicfree          339.37%   604MiB / 1.884GiB     31.31%    2.04MB / 1.19MB   387MB / 19.8MB    168

**Comment by vogler** [comment]
How long does a run last? For me epic-games takes ~1min.

**Comment by niliovo** [comment]
> How long does a run last? For me epic-games in Docker takes ~1min on a M1 MacBook Air.

I didn't understand your question.How long is this going on? It behaves like this on my arm machine and x86 machine. I only enabled epic, do I need to add environment variables to disable other unenabled services such as GOG

**Comment by vogler** [comment]
It's not a server that's constantly running, but a set of scripts that claim games and then quit. The question was how long it takes to e.g. run the script for epic-games.

See the readme on how to run only specific stores.

**Comment by niliovo** [comment]
> It's not a server that's constantly running, but a set of scripts that claim games and then quit. The question was how long it takes to e.g. run the script for epic-games.
> 
> 
> 
> See the readme on how to run only specific stores.

I understand and the modification has been completed according to the content of the readme, but the occupancy rate is still relatively high, maybe the container needs such performance. Thanks again for your reply
