### ISSUE TITLE
[Epic DLC] Free in-game items get stuck/time-out if you do not have the base game

### ISSUE THREAD

**Issue by future10se** [vogler/free-games-claimer#106]
If one of the free "games" for the week is an add-on or DLC for a base game the user does not have, the app will get stuck waiting for the claim button to become active.

Since the user does not have the base game, the button will never become active, and so claiming this freebie will time-out.

This is not a super big deal since the app will just move on to the next thing that needs claiming, but it may get annoying as the app bothers the user (via notification) throughout the week for something it can't claim :)

This could possibly be fixed by adding a check for something like the small "**add-on**" badge (above the price/free text), the button on the text for "**requires base game**", the nav bar below the title that has "**add-ons**" highlighted, or some other possible identifier. I tried checking the javascript state to see if there is some object that identifies the item as an add-on but have not found one so far.

I might give making a PR for this a shot (assuming I can find a reliable identifier), but I've not worked with playwright before, so I may take a while. You (or some other user) can feel free to beat me to it, or you can just close this if you think it is not a big deal (see above).

Sample below for this week (March 24, 2023): "[World of Warships -- Starter Pack: Ishizuchi](https://store.epicgames.com/en-US/p/world-of-warships--starter-pack-ishizuchi)"

![Screenshot 2023-03-24 001105 copy](https://user-images.githubusercontent.com/109644501/227271130-925c72e2-6f11-4bb9-a69f-7ae198eaf8ef.png)

![Screenshot 2023-03-24 001245 copy](https://user-images.githubusercontent.com/109644501/227271171-f71083bc-7afe-43f1-aeb8-f4aaab6c8dfa.png)

**Comment by vogler** [comment]
It's strange that the base game is not even linked in the description.
I skipped it and set the status to `failed:requires-base-game`. Bit of a hack: since you're right that repeated notifications would be annoying, it will not send any if there's no other game for which the status changed.

**Comment by silentguy256** [comment]
> It's strange that the base game is not even linked in the description. 

It seems the Add-on is on a sub page of the actual game. Clicking on the "Overview" in the top right under the title takes you to the base game. This is not a call to action, it was just something I just noticed and remembered you mentioning here

**Comment by yoshimo** [comment]
The base game is for free so it should be possible to automatically fix this dependency.
