### ISSUE TITLE
Error: Cannot find module '/epic-games'

### ISSUE THREAD

**Issue by PixelDu5t** [vogler/free-games-claimer#118]
Heya,

Trying to run this with docker on Ubuntu Server, and getting the following error:

```
root@gamereclaimer:/home/gamereclaimer# docker run node epic-games -it -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer
node:internal/modules/cjs/loader:1093
  throw err;
  ^

Error: Cannot find module '/epic-games'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.8.1

```
How would I go about fixing this? Is a desktop environment required on Linux? I'm not experienced with Docker so apologies if there is an obvious issue here that I'm not understanding.

**Comment by vogler** [comment]
You need to put `node epic-games` at the end of the command.

**Comment by PixelDu5t** [comment]
Truly am a noob lol, much appreciated and thanks for making this tool! About time I learn docker ":D"

**Comment by PixelDu5t** [comment]
Also must add damn, this seriously is awesome. Love it!
