### ISSUE TITLE
Epic - Doesn't seem to support 2FA

### ISSUE THREAD

**Issue by sealldeveloper** [vogler/free-games-claimer#122]
I login and it times out, my hunch is TOTP is killing the login.

**Comment by sealldeveloper** [comment]
Just did with `SHOW=1`, It seems to be failing to click the login button?

**Comment by Nackophilz** [comment]
The 2FA function works very well on my side, can you tell us more about your activated options, and especially your logs?

**Comment by sealldeveloper** [comment]
Seems to have been a bug bundled with [#123](https://github.com/vogler/free-games-claimer/issues/123). Apologies for the multiple issues.
