### ISSUE TITLE
Epic - Device not supported error

### ISSUE THREAD

**Issue by sealldeveloper** [vogler/free-games-claimer#123]
I'm running this on my MacBook idle. Seems to hit an error with the current Dying Light for the product not being supported on this platform. Maybe pushing a custom User-Agent could help or just a check for the issue.

**Comment by sealldeveloper** [comment]
I manually clicked `Continue` when using `SHOW=1` and I hit this error

```
locator.click: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for frameLocator('#webPurchaseContainer iframe').locator('button:has-text("Place Order"):not(:has(.payment-loading--loading))')
  locator resolved to <button class="payment-btn payment-order-confirm__btn pa…>…</button>
attempting click action
  waiting for element to be visible, enabled and stable
    element is not visible - waiting...
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
    at file:///.../free-games-claimer/epic-games.js:180:99 {
  name: 'TimeoutError'
}
```

**Comment by vogler** [comment]
> I'm running this on my MacBook idle. Seems to hit an error with the current Dying Light for the product not being supported on this platform. 

I'm also using macOS and I don't get this (however, Dying Light is not available for me in Germany).
You wrote 'platform' - do you mean the message 'Device not supported. This product is not compatible with your current device.'?

> Maybe pushing a custom User-Agent could help or just a check for the issue.

Both are implemented:
https://github.com/vogler/free-games-claimer/blob/351bf00c7b78a94b72d2a5fb1d9085b385ec41bb/epic-games.js#L27
https://github.com/vogler/free-games-claimer/blob/351bf00c7b78a94b72d2a5fb1d9085b385ec41bb/epic-games.js#L148-L149

**Comment by vogler** [comment]
> I manually clicked `Continue` when using `SHOW=1` and I hit this error

Probably #120 - did you try the updated code?

**Comment by sealldeveloper** [comment]
Yup, got it and working. Thank you!
