### ISSUE TITLE
Epic - Failed to claim log message but game was claimed

### ISSUE THREAD

**Issue by kennymc-c** [vogler/free-games-claimer#125]
An Epic game could not be claimed according to the log. A short time later I received a mail with the purchase confirmation. Apparently something is not recognized correctly.
Since some time I always get the captcha message when I am not connected via VNC. If I do that, no captcha appears any more. The next time without VNC connection it happens again. Unfortunately I can't change my IP so easily because of cable internet.
In addition, the time is shifted back by two hours, although -e TZ="Europe/Berlin" was set.

```
2023-04-20 16:10:04.075 started checking epic-games
Signed in as kennymc.c
Free games: [
  'https://store.epicgames.com/en-US/p/beyond-blue',
  'https://store.epicgames.com/en-US/p/never-alone-kisima-ingitchuna'
]
Current free game: Beyond Blue
  Not in library yet! Click GET.
page.waitForSelector: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('text=Thank you for buying') to be visible
============================================================
    at file:///fgc/epic-games.js:198:20 {
  name: 'TimeoutError'
}
  Failed to claim! To avoid captchas try to get a new IP address.
Current free game: Never Alone (Kisima Ingitchuna)
  Already in library! Nothing to claim.
```

**Comment by WiLuX-Source** [comment]
That's because they changed ui. It is now a div modal instead of an iframe

**Comment by WiLuX-Source** [comment]
Should be possible changing from iframe to a div

Here's how it looks on HTML Side
![image](https://user-images.githubusercontent.com/61833703/233435562-79a2e198-bacd-40ab-be23-82ef5dafb8a0.png)

**Comment by WiLuX-Source** [comment]
I don't have prime so I can't help you there. It is not related to this issue. I'll wait for main developer to answer to see when it'll be fixed if not i might make a pr.

**Comment by l-skyalker** [comment]
Instead of "Thank you for buying" it is "Thanks for your order!" now.
![image](https://user-images.githubusercontent.com/93336586/233448614-126febac-ca60-4b13-be03-52d895a014ad.png)

**Comment by vogler** [comment]
> That's because they changed ui. It is now a div modal instead of an iframe

See the PR, the text is checked on `page`, not `iframe` (which is still used for the order).

**Comment by vogler** [comment]
> In addition, the time is shifted back by two hours, although -e TZ="Europe/Berlin" was set.

All datetimes are based on ISO format, i.e. the timezone is always zero UTC offset.
https://github.com/vogler/free-games-claimer/blob/351bf00c7b78a94b72d2a5fb1d9085b385ec41bb/util.js#L22

https://www.reddit.com/r/sysadmin/comments/umg4ns/timestamp_logs_in_utc_rather_than_local_time_zones/

I get that it would be nicer for the log to show local time, but it comes with potential issues and broken datetimes when you forget to set the timezone correctly. Does docker pick it up from the host or do you always have to pass it as a variable?

**Comment by kennymc-c** [comment]
> Does docker pick it up from the host or do you always have to pass it as a variable?

The Docker integration of Unraid-OS adds this variable automatically with every container creation. The integration is similar to docker-compose but with a GUI. In this GUI you can't disable this behavior. At least I haven't found anything about it.

I think if the container is started with a correctly set timezone variable, it should be respected and not ignored. Or does having a timezone other than UTC interfere with certain processes and functions?
