### ISSUE TITLE
Make use of APIs in Epic Freebies.

### ISSUE THREAD

**Issue by WiLuX-Source** [vogler/free-games-claimer#127]
parse freebies with https://store-site-backend-static-ipv4.ak.epicgames.com/freeGamesPromotions
and put them in a order with a url.
example would be like [this](https://store.epicgames.com/purchase?offers=1-bd9fd28ca1214868922f2ab41d6d3b65-c3006006e4c74c4d8316ff09fb8dcc8d&offers=1-b13f6a1e5121469d8a825947b759339d-0cd43717a2224f33bb9a95f01d303474#/purchase/payment-methods)

It will make code more future proof.

so it is like creating a url with "store.epicgames.com/purchase?offers=1-{namespace}-{id}

With this way we only handle Authentication with Playwright & Claim it with 1 simple button click.

**Comment by WiLuX-Source** [comment]
we can just visit game pages for checking whether if its claimed or not.

**Comment by vogler** [comment]
Then there's no real advantage since you'd also have to deal with issues like #120 when you check the page for each game.

**Comment by vogler** [comment]
We can play around a bit. I just want to avoid adding more code / situations that complicate debugging / lead to more captchas without a clear advantage (like not checking each game page).
In #30 there were some comments on alternatives.
- Checking https://www.epicgames.com/account/v2/payment/ajaxGetOrderHistory is not sufficient since it only lists the last 10 orders, but the game may have been claimed before.
- Checking `data/epic-games.json` is not sufficient since a game may haven been claimed before using this tool.

**Comment by vogler** [comment]
Didn't notice any requests to their API whether a game is claimed or not.
Seems like it's checked in a local database in the browser that contains all owned games:
![image](https://user-images.githubusercontent.com/493741/234926398-8aaa6ee5-05e0-4f88-b9a5-2398d50cf199.png)

**Comment by vogler** [comment]
Check the PR. I'm always getting a captcha with it, even with a new IP.
Using the purchase URL like in your example seems to be problematic.

**Comment by WiLuX-Source** [comment]
Strange I dont get any captchas with it.

**Comment by WiLuX-Source** [comment]
Maybe another person can confirm if they get one?

**Comment by vogler** [comment]
Did you run the code from the PR?
![image](https://user-images.githubusercontent.com/493741/235294898-177f82a9-b808-4e5d-8bca-ef0313da9d5e.png)

**Comment by WiLuX-Source** [comment]
I didn't test it will let you know when i do it.

**Comment by WiLuX-Source** [comment]
Yes, The blank page is the end result but It shows thanks for your order for a little bit of time. I'm sure we can capture that by waiting a text just like we did with `Thanks for your order.`

**Comment by WiLuX-Source** [comment]
It might be `Thanks for your purchase` I don't really remember well.

**Comment by raulvasquez** [comment]
https://github.com/AuroPick/epic-free-games I noticed this repository, not sure if it would helpful vs the current method.

**Comment by WiLuX-Source** [comment]
@raulvasquez It can help for listing the game through api and the guy went through the effort and added all of the country codes as well. But still not solving our current problem.

**Comment by vogler** [comment]
@raulvasquez Thanks, I added an option `EG_COUNTRY` in 47be85f45cb8f2aa5c17350be152f836cdf3e5ad. I assume `country` should be enough to get the correct free games for the account's country and `locale` just changes the language of the description texts. Will have to wait until there is some difference (however, that is seldomly the case for `DE` vs. `US`).

**Comment by vogler** [comment]
Using `PWDEBUG=1` makes it show a captcha. Without it, you can't easily check what's going on, but looks like there really is just an empty page without any `Thanks ...`.
I then used the new `RECORD=1` and checked the `.har` in Chrome.
![image](https://github.com/vogler/free-games-claimer/assets/493741/dd0a1157-41d0-40a0-bfbd-3bfd1cc043ae)
This request response looks like something to wait for.
```json
{
  "cardinalInfo": null,
  "cardinalLookUpResponse": null,
  "confirmation": "F...",
  "message": null,
  "orderPending": null,
  "receiptResponse": {
    "orderId": "F...",
    "totalPrice": 0,
    "formattedTotalPrice": { "amount": "0.00", "symbol": "€", "placement": "f", "decimals": 2, "digits": 2 },
    "formattedCouponDiscount": { "amount": "0.00", "symbol": "€", "placement": "f", "decimals": 2, "digits": 2 },
    "formattedConvenienceFee": { "amount": "0.00", "symbol": "€", "placement": "f", "decimals": 2, "digits": 2 },
    "taxSettings": {},
    "orderStatus": "COMPLETED",
    "type": "PURCHASE",
    "formattedPresentmentAmount": { "amount": "0.00", "symbol": "€", "placement": "f", "decimals": 2, "digits": 2 },
    "totalTax": 0,
    "formattedPromotionDiscount": { "amount": "0.00", "symbol": "€", "placement": "f", "decimals": 2, "digits": 2 },
    "salesChannelId": "epic-store-web-purchase",
    "promotionDiscount": 0,
    "rewardDiscount": 0,
    "totalDiscounted": 0,
    "currency": "EUR",
    "sumPromotions": 0,
    "id": "QUICK_PURCHASE",
    "formattedSumPromotions": { "amount": "0.00", "symbol": "€", "placement": "f", "decimals": 2, "digits": 2 },
    "formattedTotalTax": { "amount": "0.00", "symbol": "€", "placement": "f", "decimals": 2, "digits": 2 },
    "rewardVoucher": null,
    "taxType": "",
    "formattedRewardDiscount": { "amount": "0.00", "symbol": "€", "placement": "f", "decimals": 2, "digits": 2 },
    "purchaseOrderPriceSummary": {
      "orderPrice": { "amount": 0, "currency": "EUR" },
      "purchasePrice": {
        "convenienceFee": { "amount": 0, "currency": "EUR" },
        "discountedPrice": { "amount": 0, "currency": "EUR" },
        "totalPrice": { "amount": 0, "currency": "EUR" }
      },
      "paymentAmount": { "amount": 0, "currency": "EUR" }
    },
    "paymentCurrencyCode": "EUR",
    "paymentCurrencyAmount": 0,
    "lineOffers": [
      {
        "quantity": 1,
        "entitlementSource": "AppEpicgamesCom",
        "formattedVoucherPrice": { "amount": "0.00", "symbol": "€", "placement": "f", "decimals": 2, "digits": 2 },
        "voucherDiscount": 0,
        "formattedBasePrice": { "amount": "0.00", "symbol": "€", "placement": "f", "decimals": 2, "digits": 2 },
        "offerIdx": 1,
        "sellerId": "o-rlswgtffm6ua68662gd37xv3lmq95q",
        "rewardDiscount": 0,
        "formattedDiscountedPrice": { "amount": "0.00", "symbol": "€", "placement": "f", "decimals": 2, "digits": 2 },
        "discountedPrice": 0,
        "price": {
          "convenienceFee": { "amount": 0, "currency": "EUR" },
          "discountedPrice": { "amount": 0, "currency": "EUR" },
          "totalPrice": { "amount": 0, "currency": "EUR" },
          "revenueWithoutTax": { "amount": 0, "currency": "USD" },
          "basePayout": { "amount": 0, "currency": "USD" },
          "basePrice": { "amount": 0, "currency": "EUR" }
        },
        "namespace": "676a89b2e8344c9db39a79724150cba6",
        "offerId": "5b99274688e9465aa9d5ca5cea176cfd",
        "basePrice": 0
      }
    ],
    "merchantGroup": "EGS_MKT",
    "voucherDiscount": 0,
    "convenienceFee": 0,
    "identityId": "...",
    "redeemRewardAmount": 0,
    "formattedTotalDiscounted": { "amount": "0.00", "symbol": "€", "placement": "f", "decimals": 2, "digits": 2 },
    "status": "COMPLETED",
    "morId": "...",
    "xEpicEnv": "PUBLIC"
  },
  "syncToken": null
}
```

**Comment by WiLuX-Source** [comment]
Page should say `Thank you...` then it should dissappear leaving you with blank page

**Comment by vogler** [comment]
> Page should say `Thank you...` then it should dissappear leaving you with blank page

I'm just getting a blank page:
https://github.com/vogler/free-games-claimer/assets/493741/ad0889f0-0bc2-499f-aa3d-c2f9cb57ba7b

However, waiting for the response above (see https://github.com/vogler/free-games-claimer/pull/130/commits/32922571720e400fde592cc61253bce478652333) works.

**Comment by vogler** [comment]
So far, #130 saves one `click()` and still needs testing of the open points.

**Comment by vogler** [comment]
https://github.com/vogler/free-games-claimer/pull/130/commits/4e8e8ee884adb254c8fcb63ecfb968f372f33fd7 URL construction somehow not reliable.

**Comment by vogler** [comment]
Tried #130 for [Death Stranding](https://store.epicgames.com/en-US/p/death-stranding) on a sep. account and it failed:
![image](https://github.com/vogler/free-games-claimer/assets/493741/3c96e39a-2a25-4122-9496-d837aa1316cc)
```
Current free game: DEATH STRANDING
  Not in library yet! Claim!
Unexpected confirm-order response. Message: We could not confirm your purchase at this time.  Please try again later.
{
  error: true,
  errorCode: null,
  message: 'We could not confirm your purchase at this time.  Please try again later.',
  messageVars: null,
  order: null,
  syncToken: '...'
}
```

**Comment by vogler** [comment]
Changed to main branch:
1. Device not supported -> Continue
2. EPIC GAMES STORE END USER LICENSE AGREEMENT
![image](https://github.com/vogler/free-games-claimer/assets/493741/90935001-0632-4f3f-9807-f2a60f1fb150)

https://github.com/vogler/free-games-claimer/blob/4e8e8ee884adb254c8fcb63ecfb968f372f33fd7/epic-games.js#L169-L174
Does not appear when using #130 which may be another issue.

However, that was not the problem and the issue persists.
Worked fine on main branch:
```
Free games: [ 'https://store.epicgames.com/en-US/p/death-stranding' ]
Current free game: DEATH STRANDING
  Not in library yet! Click GET.
  Claimed successfully!
```

**Comment by WiLuX-Source** [comment]
Well then we might only use the parse current free games with api and do the claiming with normally. I'm still busy and didn't try.

**Comment by vogler** [comment]
#130 loads https://store.epicgames.com/purchase?offers=1-d5241c76f178492ea1540fce45616757-b951f31da58449cd83d6cb1f4ca62d3a
```
Free games: [
  'Fallout: New Vegas - Ultimate Edition - https://store.epicgames.com/p/fallout-new-vegas--ultimate-edition'
]
Signed in as ...
  This game contains mature content recommended only for ages 18+
Current free game: Fallout: New Vegas - Ultimate Edition
  Not in library yet! Claim!
  purchaseURL: https://store.epicgames.com/purchase?offers=1-d5241c76f178492ea1540fce45616757-b951f31da58449cd83d6cb1f4ca62d3a
Unexpected confirm-order response. Message: We could not confirm your purchase at this time.  Please try again later.
{
  error: true,
  errorCode: null,
  message: 'We could not confirm your purchase at this time.  Please try again later.',
  messageVars: null,
  order: null,
  syncToken: '...'
}
````
![image](https://github.com/vogler/free-games-claimer/assets/493741/c66bfa69-bb01-4238-aa8f-036ed5eba8bc)
vs. main branch which loads https://store.epicgames.com/purchase?highlightColor=0078f2&offers=1-3428aaab2c674c98b3acb789dcfaa548-08834851d4a54f48b485e97caab98012&orderId&purchaseToken&showNavigation=true:
![image](https://github.com/vogler/free-games-claimer/assets/493741/55ace464-6dd7-4e12-a688-3670abd9202c)

However, those namespace/id values don't appear in https://store-site-backend-static-ipv4.ak.epicgames.com/freeGamesPromotions?country=DE&locale=en-US

**Comment by vogler** [comment]
Same problem for `Midnight Ghost Hunt` - https://store.epicgames.com/p/midnight-ghost-hunt:
https://store.epicgames.com/purchase?offers=1-d5241c76f178492ea1540fce45616757-9d5d8c66d58e412286a3f98139657ef4
https://store.epicgames.com/purchase?highlightColor=0078f2&offers=1-964f58c4c2074404bf9c359483ab1a48-0613000f1d164fc1b5dd3e5ad1376399&orderId&purchaseToken&showNavigation=true

**Comment by WiLuX-Source** [comment]
Hello there still away from my main pc,

What I can say is the safest bet would be parse games with json and do the rest of the things normally it is only a small boost but we'll get what we can get.

**Comment by vogler** [comment]
See above. You can base a PR on what I made. I think I won't spent time on it since it's too much brittle code for little gain.

**Comment by vogler** [comment]
@WiLuX-Source Any update? If not, I'll close this.

**Comment by WiLuX-Source** [comment]
@vogler you can close this issue we can discuss further when i make pr.
