### ISSUE TITLE
Issue with claiming this weeks Sims 4 bundle [This edition contains something you already have. Still interested?]

### ISSUE THREAD

**Issue by inkanyamba** [vogler/free-games-claimer#139]
Sorry if this has been mentioned or is already being worked on.

This week I had an issue with claiming the Sims 4 bundle. I think it's because I already have the base game or something.
This is shown in the log:

Free games: [
'https://store.epicgames.com/en-US/p/the-sims-4--the-daring-lifestyle-bundle'
]
Current free game: The Sims™ 4 The Daring Lifestyle Bundle
Not in library yet! Click GET.
page.waitForSelector: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('#webPurchaseContainer iframe') to be visible
============================================================
at file:///fgc/epic-games.js:159:18 {
name: 'TimeoutError'
}

I ran it in headed mode and the page shows a pop up with "This edition contains something you already have. Still interested?" Screen shot attached. 
<img width="1262" alt="Screenshot 2023-05-12 at 1 17 03 PM" src="https://github.com/vogler/free-games-claimer/assets/15939066/b2a7f62b-bcb2-428b-96c1-b76a9942bf85">

Pretty sure this pop up is what's causing the issue.

Thanks for creating and maintaining this!

**Comment by vogler** [comment]
Update your image / use `--pull=always` in your `docker run`. See #137.
