### ISSUE TITLE
[Question] Misjudgment | This game contains mature content recommended only for ages 18+

### ISSUE THREAD

**Issue by QIN2DIM** [vogler/free-games-claimer#14]
## Description
- In my case, this week's free games are in the library.
- The header browser starts normally and is displayed on the [《Insurmountable》](https://store.epicgames.com/en-US/p/insurmountable-b02c31) page.
- Then, I didn't observe the next browser behavior until it timeout quit.
- I restarted the program 3 times in the same way and all encountered the same problem, so I think it is most likely a bug.

## Log screenshot
![image](https://user-images.githubusercontent.com/62018067/163600091-12584d07-5ce8-4ed3-9acc-6623faef1766.png)

## My opinion

- I think `this game contains mature content and is only recommended for people over 18 years old` is a misjudgment. 
- I visited this page with a pure driver and no warning popped up. In other words there are no clickable (`Continue`) elements in the page. You can test it on this page [《Amnesia: Rebirth》](https://store.epicgames.com/en-US/p/amnesia-rebirth).

**Comment by vogler** [comment]
I just ran it and it claimed both games successfully:
```console
$ node epic-games
userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36
Not signed in anymore. Please login and then navigate to the 'Free Games' page.
Signed in.
Number of free games: 2
Current free game: Insurmountable
Not in library yet! Click GET.
Claimed successfully!
Current free game: XCOM® 2
Not in library yet! Click GET.
Claimed successfully!
```
I didn't get the message about mature content, but the code at this point only checks for a button with 'Continue':
https://github.com/vogler/free-games-claimer/blob/212930639f08c3f1a193e14bf39f715c0a09e90e/epic-games.js#L65-L68
So I assume in your case, it first counted > 0 for a button with 'Continue', but then when it wanted to click on it, the button was no longer there, or not in view.
Can you make a video what happens or run it with `PWDEBUG=1 node epic-games` and step through it?
I assume it's either some race condition or a EU vs. non-EU difference.

**Comment by jackblk** [comment]
Quick fix:

```javascript
 if (await page.locator('button:has-text("Continue")').count() > 0) { 
   console.log('This game contains mature content recommended only for ages 18+'); 
   await page.click('button:has-text("Continue")'); 
 } 
```

**Comment by vogler** [comment]
Thanks, it should have been like this from the start. It just found the word `Continue` on the page and then tried to click the non-existing button.
