### ISSUE TITLE
Guide on running this on a VPS?

### ISSUE THREAD

**Issue by frorayz** [vogler/free-games-claimer#140]
It would be really helpful if there was a guide on this for VPS. Specifically Ubuntu 22.04 VPS'es

**Comment by vogler** [comment]
I don't get what you envision. Just run it?
![image](https://github.com/vogler/free-games-claimer/assets/493741/589f47ca-3f10-4d54-b549-1111d5c79d9f)
https://www.oracle.com/cloud/free/ - 4 ARM CPUs, 24GB RAM, 200GB SSD

**Comment by frorayz** [comment]
> I don't get what you envision. Just run it? ![image](https://user-images.githubusercontent.com/493741/238136419-589f47ca-3f10-4d54-b549-1111d5c79d9f.png) https://www.oracle.com/cloud/free/ - 4 ARM CPUs, 24GB RAM, 200GB SSD

I meant without docker. My VNC is not working

**Comment by vogler** [comment]
See `I want to run without Docker or develop locally.` in the README for setup.
If you can't access VNC, you probably need to configure your VPS's firewall.

**Comment by vogler** [comment]
The Dockerfile is also based on Ubuntu 22.04, so you can just refer to that.
Here's the VNC package installed:
https://github.com/vogler/free-games-claimer/blob/8ee63c7a35bb3ed43ab7f59dfb121c89bb7c9368/Dockerfile#L18
