### ISSUE TITLE
`PG_CLAIMDLC` locator 'a' resolved to 2 elements

### ISSUE THREAD

**Issue by Nackophilz** [vogler/free-games-claimer#142]
Hi! Since the last update I don't get Telegram notifications anymore, my Docker configuration hasn't changed, only the version of your application

Here is the error for the notification:

```
error: Command failed: apprise tgram://*****:*****/***** -i html '-t FreeGames' -b 'prime-gaming failed: locator.getAttribute: Error: strict mode violation: locator('div[data-a-target="offer-list-IN_GAME_LOOT"] [data-a-target="item-card"]:has(p:text-is("Claim"))').first().locator('a') resolved to 2 elements:'
```

**Comment by Nackophilz** [comment]
I have the impression that it adds a ":/" which should not be there, however in my parameters, it is good

**Comment by vogler** [comment]
Seems like DLCs now have two `a` tags. Let me know if the fix does not work.

**Comment by Nackophilz** [comment]
Hey ! 

Good, notification work again 

But their is a problem for claimin DLC 

After the first DLC is claimed , he just freeze, then go to timeout : 

page.inputValue: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('input[type="text"]')
============================================================
    at file:///fgc/prime-gaming.js:286:33 {
  name: 'TimeoutError'
}
