### ISSUE TITLE
Epic: Accept End User License Agreement

### ISSUE THREAD

**Issue by EQUALIT-CG** [vogler/free-games-claimer#148]
Hello Vogler

I just found an issues but was easy to fix Once I connected via vcn but that said 

the new Epic game Fall out had a user agreement witch couldn't grab
 the game until the user agreement was ticked maybe you have an idea on a work around since not everyone will wanna vcn into it just to tick that 

![Screenshot 2023-05-28 at 22-58-07 noVNC](https://github.com/vogler/free-games-claimer/assets/56815873/ca2ec7bc-b47c-4db9-a335-80a97d1ccc7c)

**Comment by vogler** [comment]
> I was not using a tag so maybe i haven't updated
> Also i have now used the tag "latest" I tried using the tag "v1.4"

You shouldn't specify any tag; just make sure you run with `--pull=always` like it says in the README.
See https://vsupalov.com/docker-latest-tag/.

**Comment by EQUALIT-CG** [comment]
right but i was using a docker-compose and you don't pull them at all i just docker-compose up and it will auto pull for me

But that said you should be able to add tags because i wish to be on a version i choose if there a bug i wish to roll back or what ever just like any other app like unifi or radarr or anything really I can use latest witch is what i did but i should also be able to use a tag right...?

if i was testing something from lest say when a bug was and then was removed in a new version then wish to roll back is that not how it would work 

I'm also using a docker-compose so should be "--pull=always"

**Comment by EQUALIT-CG** [comment]
in the link they also say "Do not run any container with the latest tag. Been there, done that. Did not end very well."

Because it may come with bugs so i should be able to use tags to roll back no...?
so if v1.4 was a bug but v1.2 wasn't then i can roll back and view notes on what i'm missing out on / changes etc etc


it also says 
"Imagine your image building scripts are a bit off, or used incorrectly. Any developer who does not provide an image tag can overwrite the :latest image without meaning to."

witch is why i use tags so I Know and read what changes are before i update an image because if i let it auto update to the latest image I have not read the changes as well as if something was changed then i have no idea if this is my end or a change in the script etc etc etc

**Comment by vogler** [comment]
> i was using a docker-compose and you don't pull them at all i just docker-compose up and it will auto pull for me

`docker compose up` will not update. In this case you need to run `docker compose pull` before.
See https://stackoverflow.com/questions/37685581/how-to-get-docker-compose-to-use-the-latest-image-from-repository

> you should be able to add tags

I am. See https://github.com/vogler/free-games-claimer/releases
I don't tag releases that often because it costs time and so far there have been little major changes. It's more likely for you to have issues from an outdated image than me pushing untested breaking changes (not saying that that never happens, but you get the point).

> witch is why i use tags so I Know and read what changes are before i update an image

You can do that, but please check the latest version before opening issues.

**Comment by EQUALIT-CG** [comment]
> "docker compose up will not update. In this case you need to run docker compose pull before."

Hello I just like to add wrong it will auto pull when you start the container you don't need a pull if its auto I use alias but that said once again it will auto pull so if i change the tag i don't have to run "docker pull" because i have have a tag asing to this witch i will upload a video of it then you can see 

I'm not saying your wrong 

I was trying to understand why it wouldn't use a tag but that fine i can see it cost time and i understand that i don't understand the possess of that side of things. but may i please make a request if you can if you can' that fine but its just something i would like to ask.

I do understand that in some time from now you may not update this and will be come pointless i get that

But i do apologize for not running the "latest" image before posting PR

**Comment by vogler** [comment]
Not sure what your point is. If the tag does not exist yet, it will download it, but it won't update an untagged/latest image like `--pull=always` does.

There have been many small urgent changes - auto-update avoids false-positive issues.
GitHub Actions builds an image for every commit and you can pull any of them: https://github.com/vogler/free-games-claimer/pkgs/container/free-games-claimer/versions
