### ISSUE TITLE
Docker errors

### ISSUE THREAD

**Issue by XEGARE** [vogler/free-games-claimer#15]
Hello. All problems in the screenshot. Instead of `$(pwd)` specified an `absolute path`
![1651407543](https://user-images.githubusercontent.com/28856609/166145661-4b4d64c8-21f8-4c01-9630-8838786f42b6.png)

**Comment by jackblk** [comment]
`$(pwd)` is for *nix (mac/linux/WSL2...)

If you use powershell then use `${PWD}`

**Comment by jackblk** [comment]
Can you retry with the new one I just commented?

**Comment by XEGARE** [comment]
> Can you retry with the new one I just commented?
![1651583226](https://user-images.githubusercontent.com/28856609/166458411-b6cd117d-bb27-4b45-8808-2693a60540e1.png)

**Comment by QIN2DIM** [comment]
`${PWD}\\userDataDir`

**Comment by XEGARE** [comment]
${PWD}\\userDataDir:
```
docker run --rm -it -p 5900:5900 -p 6080:6080 -v "${PWD}\userDataDir:/fgc/userDataDir" --name free-games-claimer free-games-claimer

docker: Error response from daemon: ${PWD}\userDataDir%!(EXTRA string=is not a valid Windows path).
```
${PWD}\userDataDir:
```
npm ERR! code EJSONPARSE
npm ERR! path D:\Backup\GitHub\free-games-claimer/package.json
npm ERR! JSON.parse Unexpected token "s" (0x73) in JSON at position 378 while parsing near "...0:6080 -v \\\"${PWD}\\userDataDir:/fgc/user..."
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.
```

D:\\Backup\\GitHub\\free-games-claimer/userDataDir:
D:/Backup/GitHub/free-games-claimer/userDataDir:
`standard_init_linux.go:228: exec user process caused: no such file or directory`

I think the problem is in the docker container

**Comment by vogler** [comment]
I changed it to `$INIT_CWD` which is set by npm and platform-independent.
Works on macOS; IDK if Docker has a problem with the `/` instead of `\` on Windows. I'd guess no. Can you try?

---

Re `standard_init_linux.go:228: exec user process caused: no such file or directory`
This unhelpful message seems to have to do with Windows line endings: https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory

Best to delete/move `userDataDir` to have a clean slate and check after each run if it got populated (which it should if the volume was mounted correctly).

**Comment by vogler** [comment]
Here's some background on how git handles line endings: https://stackoverflow.com/questions/3206843/how-line-ending-conversions-work-with-git-core-autocrlf-between-different-operati/3209806#3209806
You checked out Windows line endings (CRLF) and built the image, then the `Dockerfile` runs the scripts `docker/*sh` with CRLF line endings but needs LF.
You need to change line endings to LF and build the image again. Either change the git config and checkout again or use some vscode/notepad++/dos2unix/etc to change them.

**Comment by vogler** [comment]
Ok, I added a call to dos2unix in `Dockerfile`. You just need to `git pull` and `npm run docker:build`.

**Comment by XEGARE** [comment]
1. Line Endings I changed yesterday for sh files. It did not help.

2. INIT_CWD not working
![1651645352](https://user-images.githubusercontent.com/28856609/166631781-d2ced2c9-efe2-474c-b631-a02492eeae24.png)

3. There are no more errors, but it does not log in. `node epic-games` also stops working after `docker`. Asks to login agaiт
![1651645626](https://user-images.githubusercontent.com/28856609/166632392-2a4d5572-c4e5-4ef1-9eda-f26871a9920b.png)

**Comment by vogler** [comment]
1. Ok, then I don't know. Did you build the image again? Is there some more verbose log file?
2. Forgot that it would need to be `%INIT_CWD%` on Windows. I added `cross-env`. Should work now.
3. Try a fresh `userDataDir` only for docker, login via http://localhost:6080 with password `secret`.
I also noticed issues with Docker corrupting `userDataDir`. `node epic-games` alone works fine, mixing it with Docker seems to work on macOS, on Windows it's likely incompatible since you're sharing it with an Ubuntu installation. However, just running via docker (and killing it) two times in a row also seems to break `userDataDir`.

**Comment by jackblk** [comment]
One more thing, try using Docker together with WSL2. It is much more compatible this way.

**Comment by vogler** [comment]
Yea, I also thought about just not supporting Windows' cmd, but let's see how hard it is to support. The path stuff is annoying, but only needs to be figured out once.

**Comment by XEGARE** [comment]
> 1. Ok, then I don't know. Did you build the image again? Is there some more verbose log file?
> 2. Forgot that it would need to be `%INIT_CWD%` on Windows. I added `cross-env`. Should work now.
> 3. Try a fresh `userDataDir` only for docker, login via http://localhost:6080 with password `secret`.
>    I also noticed issues with Docker corrupting `userDataDir`. `node epic-games` alone works fine, mixing it with Docker seems to work on macOS, on Windows it's likely incompatible since you're sharing it with an Ubuntu installation. However, just running via docker (and killing it) two times in a row also seems to break `userDataDir`.

1. Yes. Rebuild image. I don't have more logs.

2. Not working `cross-env`. Separately, `%INIT_CWD%` works, but `cross-env` does not
![image](https://user-images.githubusercontent.com/28856609/166645799-40ab8c8c-670f-47cf-9d7b-ae6f0962d49a.png)

3. Ok. Good

**Comment by XEGARE** [comment]
> One more thing, try using Docker together with WSL2. It is much more compatible this way.

WSL2 always on

**Comment by vogler** [comment]
1. It seems to work now, no?
2. Not sure why the var is not replaced. I changed it to `cross-env-shell` and removed the quotes. Can you check which is required and if it still works with spaces in the path?

**Comment by vogler** [comment]
> WSL2 always on

@jackblk meant running it in WSL2. You're running it in Windows Powershell.
But let's pull through and see if we can get it to work platform-independently.
Docker through WSL2 adds additional overhead for setup, as well as running it.

**Comment by XEGARE** [comment]
> 1. It seems to work now, no?
> 2. Not sure why the var is not replaced. I changed it to `cross-env-shell` and removed the quotes. Can you check which is required and if it still works with spaces in the path?

1. it works
2. I haven't been able to verify this. Due to INIT_CWD, it is required to use the same directory to build the docker container. Path spaces somehow affect the assembly and the container does not start.
![image](https://user-images.githubusercontent.com/28856609/166656493-860c1c11-55ea-4e43-9813-43dac8714f09.png)

**Comment by XEGARE** [comment]
Maybe use `docker run --rm -it -p 5900:5900 -p 6080:6080 -v userDataDir:/fgc/userDataDir --name free-games-claimer free-games-claimer`

`userDataDir` is volume for docker
![image](https://user-images.githubusercontent.com/28856609/166660232-11075855-fc3e-4411-b485-f6a510f4bad3.png)

**Comment by vogler** [comment]
Docker docs say it needs to be an absolute path. A relative path seems to map it inside the container.
At least on macOS `userDataDir` is empty if I use a relative path.

The build shouldn't be affected by spaces in the path.
You can change the `package.json` to just use `cross-env-shell` but keep the escaped quotes as before.

**Comment by XEGARE** [comment]
> Docker docs say it needs to be an absolute path. A relative path seems to map it inside the container. At least on macOS `userDataDir` is empty if I use a relative path.
> 
> The build shouldn't be affected by spaces in the path. You can change the `package.json` to just use `cross-env-shell` but keep the escaped quotes as before.

`/var/lib/docker/volumes` empty in macOS?

**Comment by vogler** [comment]
The files are not easily accessible: https://stackoverflow.com/questions/38532483/where-is-var-lib-docker-on-mac-os-x/65645462#65645462
So at least on macOS you need the absolute path to have easy access to the folder.
Did you try `\"$INIT_CWD/userDataDir\"` to fix the issue with spaces in the path?

**Comment by vogler** [comment]
1.1. to be able to delete stuff, the commit above just fixed this when running in docker:
![image](https://user-images.githubusercontent.com/493741/166948243-dd19e04c-6851-4a61-9e61-70a4f38b8510.png)
1.2. potentially to share the profile between host and container
2. How do you know? Maybe `cross-env-shell` removes the quotes. The message sounds like it has a problem with the arguments. Try renaming the folder back to `free-games-claimer` and run the same command again.

**Comment by XEGARE** [comment]
> 1.1. to be able to delete stuff, the commit above just fixed this when running in docker: ![image](https://user-images.githubusercontent.com/493741/166948243-dd19e04c-6851-4a61-9e61-70a4f38b8510.png) 1.2. potentially to share the profile between host and container 2. How do you know? Maybe `cross-env-shell` removes the quotes. The message sounds like it has a problem with the arguments. Try renaming the folder back to `free-games-claimer` and run the same command again.

Yes you are right. I have corrected. Now spaces in the path work.
`cross-env-shell docker run --rm -it -p 5900:5900 -p 6080:6080 -v \\\"$INIT_CWD/userDataDir:/fgc/userDataDir\\\" --name free-games-claimer free-games-claimer`
![1651776512](https://user-images.githubusercontent.com/28856609/167004571-825f0ae5-8d64-4fe7-89c5-5579a5c28fc3.png)

The `rm` command does not exist in Windows. There is `del / erase`.

**Comment by XEGARE** [comment]
Today when picking up a game I got stuck on `:has-text("Continue")` after clicking on the `"Get"` button.

Changed it to `button:has-text("Continue")` and it worked

**Comment by vogler** [comment]
> Yes you are right. I have corrected. Now spaces in the path work. 

Good, so this should be fine now.

> The `rm` command does not exist in Windows. There is `del / erase`.

Ah, right. I changed it to [rimraf](https://github.com/isaacs/rimraf).

**Comment by vogler** [comment]
> Today when picking up a game I got stuck on `:has-text("Continue")` after clicking on the `"Get"` button.
> 
> Changed it to `button:has-text("Continue")` and it worked

This has been fixed in #14.

**Comment by XEGARE** [comment]
> > Today when picking up a game I got stuck on `:has-text("Continue")` after clicking on the `"Get"` button.
> > Changed it to `button:has-text("Continue")` and it worked
> 
> This has been fixed in #14.

It’s different. I’m talking about it:
https://github.com/vogler/free-games-claimer/blob/59450ed05ca402025cfd25e9e2cb5fb728667eb1/epic-games.js#L78

What about escaping quotes for the path? You have not commited` \\\`. Doesn't it work on other systems?

**Comment by vogler** [comment]
Ah, good catch, fixed.
Sorry, didn't get the `\\\"` before, fixed.
Also confirmed on macOS - same behavior as you had above. 👍 

Note 59450ed05ca402025cfd25e9e2cb5fb728667eb1 - you can move `userDataDir` -> `data/browser`.
I guess you can close this then if it all works for you.

**Comment by XEGARE** [comment]
Everything is working. I am satisfied. I close. Have a good day.

**Comment by jackblk** [comment]
@vogler I improved the profile lock fix in this commit
https://github.com/vogler/free-games-claimer/commit/c90bd7574b8146d4ff2046f2677e47bf85f29b28

**Comment by vogler** [comment]
Huh, I had it there before and it didn't work, but prob. maybe the relative path was wrong.
