### ISSUE TITLE
[Docs] Run image in the cloud for free

### ISSUE THREAD

**Issue by Primajin** [vogler/free-games-claimer#150]
Hey there, I was able to run the docker image in the cloud for free and schedule it to run periodically using this repo and tutorial:

https://github.com/rafaelzimmermann/remote-docker
https://medium.com/codex/run-your-docker-containers-for-free-in-the-cloud-and-for-unlimited-time-361515cb0876

If you think it's worth, maybe it can be added to the docs.

Best Regards

**Comment by vogler** [comment]
I'm also running it on a free Oracle ARM VPS. Should mention it somewhere, yes.
The point of remote-docker is to setup everything (network, ssh?) without clicking around on their website?

**Comment by vogler** [comment]
![image](https://github.com/vogler/free-games-claimer/assets/493741/b7dd727c-c151-47c9-9ef3-e1264a4f3cfd)
Not sure if that's enough for you to be able to create a page on the wiki.

**Comment by Primajin** [comment]
> The point of remote-docker is to setup everything (network, ssh?) without clicking around on their website?

Correct, you just run one command and it sets up everything for you in a couple of minutes. Especially easy for people like me who are not super duper savvy with backend and DevOps infrastructure.

Cool I'll try the wiki out if I can edit now 👍🏻

**Comment by Primajin** [comment]
Works!
![image](https://github.com/vogler/free-games-claimer/assets/1742115/d5abc0b4-c87b-428c-a09d-e35ff77e8931)
