### ISSUE TITLE
Epic Games: captcha challenge

### ISSUE THREAD

**Issue by lacrima08** [vogler/free-games-claimer#155]
Hi,

I just try your app and Epic games store ask me sometimes for a captcha (9 pics captcha).

I had to resolve it for the bot to continue.

only on epic at this time, i haven't configured other platforms yet

Thanks for your work

**Comment by permster** [comment]
I just ran into this as well.  I ended up manually claiming it through the Epic Games Launcher app and it didn't prompt for the captcha.  Perhaps it only prompts through the browser?

**Comment by vogler** [comment]
I don't get any captcha challenges (see below). How are you running it? Is it fine by now? You usually get these challenges for ~6h and then it resets.
Possible factors: too many login attempts, country of account, country of IP, VPN, macOS/Win/Linux, docker/node, non-default options.

```console
$ SHOW=1 RECORD=1 node epic-games.js
2023-06-15 16:52:45.477 started checking epic-games
Signed in as ...
Free games: [ 'https://store.epicgames.com/en-US/p/payday-2-c66369' ]
  This game contains mature content recommended only for ages 18+
Current free game: PAYDAY 2
  Not in library yet! Click GET.
  Claimed successfully!
```

[1af4d114-24fa-4aa2-9ae7-ac78be9267b7.webm](https://github.com/vogler/free-games-claimer/assets/493741/bfe3782c-61c7-40c8-9ff6-8e3977b52a70)


```
$ RECORD=1 node epic-games.js
2023-06-22 16:37:57.880 started checking epic-games
Signed in as kigu1
Free games: [
  'https://store.epicgames.com/en-US/p/guacamelee-2-ac4977',
  'https://store.epicgames.com/en-US/p/guacamelee-stce-7cdbc8'
]
Current free game: Guacamelee! 2
  Not in library yet! Click GET.
  Claimed successfully!
Current free game: Guacamelee! Super Turbo Championship Edition
  Not in library yet! Click GET.
  Claimed successfully!
```

[74bb14ee-2bc8-412c-aeda-43d73913760e.webm](https://github.com/vogler/free-games-claimer/assets/493741/0807912e-e015-455e-9ced-38c01b302db2)

**Comment by vogler** [comment]
Still an issue or was it temporary? Everything works fine for me.

**Comment by andre-paulo98** [comment]
Haven't had issues lately

**Comment by vogler** [comment]
Feel free to reopen if there are still issues.

**Comment by MohammadAliAmir** [comment]
Hi @vogler, I get hCaptchas when claiming from epic games. Either through the docker container or manually through my WSL node setup. If I recall correctly only appears when claiming 18+ games. I will take a screen next time, already claimed it manually.

**Comment by MohammadAliAmir** [comment]
Forgot to reply back, here is the screen with the hCaptcha
![image](https://github.com/vogler/free-games-claimer/assets/37347364/527365f6-c66e-48d6-8f94-6348fe44ca09)
