### ISSUE TITLE
Prime-Gaming: TimeoutError "subtree intercepts pointer events"

### ISSUE THREAD

**Issue by Azogue99** [vogler/free-games-claimer#156]
When trying to execute for PRIME-GAMING it is giving me a TimeoutError, it does seems like it is not capable to do the click action.
Not sure if there is something im doing wrong, or just a bug.

After reading the log, it seems to be related with the error "subtree intercepts pointer events".
Found this over internet, not sure if it is usefull.

https://github.com/microsoft/playwright/issues/12298

Thanks <3
[TimeoutError.txt](https://github.com/vogler/free-games-claimer/files/11772399/TimeoutError.txt)

**Comment by vogler** [comment]
Can't reproduce this. Does it still happen for you? How are you running it? If you use a different resolution, that may be the issue.
