### ISSUE TITLE
Epic Games: timeout 'Thanks for your order!'

### ISSUE THREAD

**Issue by Nackophilz** [vogler/free-games-claimer#157]
Hey ! 

Just noticed i have this error in my docker when i want to redeem Epic Games (example for the last one) : 

```
Free games: [
  'https://store.epicgames.com/en-US/p/guacamelee-2-ac4977',
  'https://store.epicgames.com/en-US/p/guacamelee-stce-7cdbc8'
]
Current free game: Guacamelee! 2
  Not in library yet! Click GET.
page.waitForSelector: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('text=Thanks for your order!') to be visible
============================================================
    at file:///fgc/epic-games.js:212:20 {
  name: 'TimeoutError'
```

**Comment by vogler** [comment]
Can't reproduce. Recorded runs for the last two weeks didn't have any problems: https://github.com/vogler/free-games-claimer/issues/155#issuecomment-1602771667.

Did something in your setup change? Did you try running it again?

**Comment by Nackophilz** [comment]
Indeed, I tried again, I don't have the problem anymore, it must have been a temporary problem :) 
Thank you !
