### ISSUE TITLE
Amazon Gaming - Claim GOG game

### ISSUE THREAD

**Issue by Doublemyst** [vogler/free-games-claimer#158]
When on the amazon gaming page, the script isn't able to claim the GOG game. 

```
[AggregateError: All promises were rejected] {
  [errors]: [
    page.click: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Claim now")')
    ============================================================
        at file:///fgc/prime-gaming.js:130:29 {
      name: 'TimeoutError'
    },
    page.click: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Complete Claim")')
    ============================================================
        at file:///fgc/prime-gaming.js:130:73 {
      name: 'TimeoutError'
    },
    page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('div:has-text("Link game account")') to be visible
    ============================================================
        at file:///fgc/prime-gaming.js:130:122 {
      name: 'TimeoutError'
    }
  ]
}
```

I am not a developer, but it seems for me, that it is trying to find following strings:
"Claim now", "Complete Claim", "Link game account". I have watched what is going on inside the browser, and the script is opening the game via the "Claim" button, but to fully claim the game, it should activate the "Get game" button, but I think this string is not programmed in yet.

![grafik](https://github.com/vogler/free-games-claimer/assets/40290451/18879030-3e78-444c-ba2a-880b22de98b2)

When the button is pressed, there is an activation key, which should be inserted in the GOG page. And if the user is already signed it, after entering the code, and redeeming the game, it is added to GOG account.

**Comment by kennymc-c** [comment]
Already mentioned this here a few days ago: https://github.com/vogler/free-games-claimer/issues/126#issuecomment-1595000964 But since this issue was closed after the last change it may have been overlooked.

**Comment by luke-rie** [comment]
I changed the button to "Get game" and was able to claim the game, however there is another issue:
> Current free game: Prey
> TypeError: Cannot read properties of null (reading 'innerText')
>     at file:///home/user/repo/free-games-claimer/prime-gaming.js:131:87

 Since i currently dont have any other games to claim i am unable to fix it :(

**Comment by vogler** [comment]
Sorry, had no time to check issues here.

Yes, there are several changes to the page, at least for gog.com, maybe also others, while Legacy Games still works with the old code.

I adjusted it before, but had no time to test and commit it.
