### ISSUE TITLE
Prime Gaming OTP PG_OTPKEY not working

### ISSUE THREAD

**Issue by amosyuen** [vogler/free-games-claimer#162]
I set the prime gaming PG_OTPKEY following the instructions at https://github.com/vogler/free-games-claimer#automatic-login-two-factor-authentication. However, when it gets to prime gaming it fails to sign in. Epic Games OTP works fine for me.

Logs
```
2023-06-30 05:29:40.163 started checking prime-gaming
Not signed in anymore.
Login timeout is 180 seconds!
Using email and password from environment.
Two-Step Verification - enter the One Time Password (OTP), e.g. generated by your Authenticator App
page.waitForURL: Timeout 180000ms exceeded.
=========================== logs ===========================
waiting for navigation to "https://gaming.amazon.com/home?signedIn=true" until "load"
  navigated to "https://www.amazon.com/ap/mfa?ie=UTF8&arb=de8c04d2-8a45-4267-8bf5-314b89ece225&mfa.arb.value=de8c04d2-8a45-4267-8bf5-314b89ece225&mfa.arb.key=arb"
  navigated to "https://www.amazon.com/ap/mfa?ie=UTF8&arb=67ea8551-d21d-4419-9acb-c15b172a559a&mfa.arb.value=67ea8551-d21d-4419-9acb-c15b172a559a&mfa.arb.key=arb"
============================================================
    at file:///fgc/prime-gaming.js:81:16 {
  name: 'TimeoutError'
}
```

**Comment by vogler** [comment]
Can you use `RECORD=1` to record a video of what's happening? What does it navigate to?

**Comment by vogler** [comment]
Feel free to reopen with details.

**Comment by amosyuen** [comment]
Hi, sorry for delay in responding. I managed to get the recorded video. It looks like the error given in Amazon is `The one time password (OTP) you entered is not valid. Please try again.` I definitely followed the instructions given at https://github.com/vogler/free-games-claimer#automatic-login-two-factor-authentication where I copied the bolded key. I'm able to login fine using the same key scanned to my authenticator app.

**Comment by NaruZosa** [comment]
Remove the spaces and it works.
