### ISSUE TITLE
Epic Games login network error - captcha not loading

### ISSUE THREAD

**Issue by sirmaestro** [vogler/free-games-claimer#166]
Hey volger!

Thanks for creating this app, I've been looking for something like this. Unfortunately I'm getting some trouble logging in to Epic Games, seems like the browser can't load the captcha? Any idea what could be wrong? I've turned off adblock and such, so it should load.

![Screenshot 2023-07-06 210029](https://github.com/vogler/free-games-claimer/assets/20761638/3182d2d7-aba2-417e-bd78-287a7085f742)
![image](https://github.com/vogler/free-games-claimer/assets/20761638/3d8616a0-8f84-4767-afe6-9901115d1005)

**Comment by vogler** [comment]
Maybe you have some DNS filter that blocks it? PiHole, AdGuard, nextdns.io etc.
Does it load in your local browser?

**Comment by vogler** [comment]
Feel free to reopen with details.
