### ISSUE TITLE
cant type @

### ISSUE THREAD

**Issue by samilSEB** [vogler/free-games-claimer#169]
Hey, I just installes Docker,  done the "docker run --rm -it -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer" on the terminal. it asked for my email but i cant type in  an "@". It isnt possible in the http://localhost:6080 too. 
as long as the code runs i cant type @€µ or something that requires CTRL + ALT + ...

**Comment by vogler** [comment]
That sounds like an issue with your terminal or keyboard 😄 
Terminal I can imagine. What are you using?
Browser seems weird. Can you type it on other websites? Can you paste it?
