### ISSUE TITLE
SCREENSHOTS_ set as /dev/null (per comment) throws an error

### ISSUE THREAD

**Issue by Mirabis** [vogler/free-games-claimer#172]
## Description
Whenever specifying '/dev/null' for the SCREENSHOTS_DIR configuration value (as recommended in the comments) it still throws an error when attempting to screenshot. The notification being sent includes the following (example):
```
prime-gaming failed: ENOTDIR: not a directory, open /dev/null/prime-gaming/internal/{GAME}
```
### Priority
LOW: Because only the screenshot fails - everything else works.

### Line in Code
https://github.com/vogler/free-games-claimer/blob/22f673282b12d3f047c3c25e4d8650e299d9ae74/config.js#L23C78-L23C102

### Ask/Recommendation
Provide a boolean to (not) save screenshots or change the code to not error when that input is (to be) expected.

**Comment by vogler** [comment]
Sorry, forgot to test that.

```console
$ echo foo > /dev/null

$ echo foo > /dev/null/screenshot
zsh: not a directory: /dev/null/screenshot
```

Since `/dev/null` wouldn't work on Windows anyway, I added some logic to disable screenshots if `SCREENSHOTS_DIR=0` is set.
