### ISSUE TITLE
Unable to Connect to VNC on Arch Linux

### ISSUE THREAD

**Issue by maplepy** [vogler/free-games-claimer#173]
**Description:**
I am encountering issues with connecting to the VNC server and accessing noVNC while running the `free-games-claimer` container. Here are the details of the problem:

- When attempting to connect to `localhost:6080`, the page does not load.
- Trying to connect to the VNC server on port 5900 results in a black screen.
- I have followed the provided instructions and ensured that the container is running.

**Steps to Reproduce:**
1. Start the `free-games-claimer` container.
2. Access `localhost:6080` in a web browser.
3. Attempt to connect to the VNC server on port 5900.

**Expected Behavior:**
I expect to be able to access the VNC server and interact with the noVNC interface as described in the documentation.

**Actual Behavior:**
I am unable to connect to the VNC server or access the noVNC interface. Connecting to `localhost:6080` does not load the page, and connecting to the VNC server on port 5900 results in a black screen.

**Additional Information:**
- I have checked the container logs, and there are no error messages or warnings related to the VNC or noVNC setup.
- I have verified that the container is running and no other processes are using ports 5900 or 6080.

**Environment:**
- Operating System: Arch Linux
- Container Image: `ghcr.io/vogler/free-games-claimer:latest`

Any assistance or guidance in resolving this issue would be greatly appreciated.

Thank you.

```
 ✔ free-games-claimer Pulled                                                             0.8s
[+] Running 1/0
 ✔ Container fgc  Created                                                                0.0s
Attaching to fgc
fgc  | Xvfb display server created screen with resolution 1280x1280
fgc  | VNC is running on port 5900 (no password!)
fgc  | noVNC (VNC via browser) is running on http://localhost:6080
fgc  |
fgc  |
fgc  | 2023-07-18 13:29:00.924 started checking epic-games
fgc  | Not signed in anymore. Please login in the browser or here in the terminal.
fgc  | Open http://localhost:6080 to login inside the docker container.
fgc  | Login timeout is 180 seconds!
fgc  | Press ESC to skip the prompts if you want to login in the browser (not possible in headless mode).
fgc  |
fgc  | ? Enter email ‣
````

![image](https://github.com/vogler/free-games-claimer/assets/28269333/d0e28297-e6fa-4e02-bc5f-be9a7ceb1d9a)

**Comment by maplepy** [comment]
Tried using this docker-compose too: https://github.com/vogler/free-games-claimer/issues/43#issuecomment-1371754557

**Comment by maplepy** [comment]
![image](https://github.com/vogler/free-games-claimer/assets/28269333/dfabaf3a-e43a-433d-9d00-d9da992bd0b7)

**Comment by vogler** [comment]
There should be nothing special about the exposed ports. Can you access other containers' ports?
Try if you can access this in your browser: https://hub.docker.com/r/nginxdemos/hello/

**Comment by maplepy** [comment]
Yeah I can see any other port in my docker compose, sonarr, radarr, jellyfin, nextcloud, nginx, prowlarr, jackett etc. all work fine

**Comment by vogler** [comment]
Ok, interesting, then maybe it's the same issue as #149 (HAOS), but I thought I saw someone running it on Arch without problems.

**Comment by vogler** [comment]
Maybe it's a good idea for you to chime in there, I just added some comment how to debug further.

**Comment by maplepy** [comment]
Yeah I'll check the issue right now and give my input if I can :)

**Comment by maplepy** [comment]
Not sure if it's related, I'm not on `aarch` but `arch linux` and `endeavour os`

`uname -a`
`Linux summer 6.4.3-arch1-2 #1 SMP PREEMPT_DYNAMIC Sat, 15 Jul 2023 19:25:49 +0000 x86_64 GNU/Linux`

**Comment by maplepy** [comment]
I will try on a `` machine

**Comment by maplepy** [comment]
Seems like it's working fine on my ubuntu machine so I will use that now but yeah the vnc not working was weird on my arch linux machine

```docker
version: '3.6'

services:
  free-games-claimer:
    container_name: fgc
    image: ghcr.io/vogler/free-games-claimer
    ports:
      - "6080:6080"
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    volumes:
      - ./fgc/data:/fgc/data
    command: >
              bash -c "node epic-games.js; node gog.js" 
```

**Comment by maplepy** [comment]
Do you the diff of the whole ouput of `docker info` ?

![image](https://github.com/vogler/free-games-claimer/assets/28269333/1fed6d47-e0d4-4c50-b86c-4270784411f4)

**Comment by maplepy** [comment]
~ ❯ diff arch ubuntu
```diff
2d1
<  Version:    24.0.2
5,8d3
<  Plugins:
<   compose: Docker Compose (Docker Inc.)
<     Version:  2.20.0
<     Path:     /usr/lib/docker/cli-plugins/docker-compose
11,12c6,7
<  Containers: 13
<   Running: 13
---
>  Containers: 12
>   Running: 10
14,16c9,11
<   Stopped: 0
<  Images: 42
<  Server Version: 24.0.2
---
>   Stopped: 2
>  Images: 15
>  Server Version: 20.10.21
20,21c15
<   Using metacopy: true
<   Native Overlay Diff: false
---
>   Native Overlay Diff: true
31c25
<  Runtimes: io.containerd.runc.v2 runc
---
>  Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
34,36c28,30
<  containerd version: 0cae528dd6cb557f7201036e9f43420650207b58.m
<  runc version:
<  init version: de40ad0
---
>  containerd version:
>  runc version:
>  init version:
37a32
>   apparmor
39c34
<    Profile: builtin
---
>    Profile: default
41,42c36,37
<  Kernel Version: 6.4.3-arch1-2
<  Operating System: EndeavourOS
---
>  Kernel Version: 5.15.0-76-generic
>  Operating System: Ubuntu 22.04.2 LTS
45,48c40,43
<  CPUs: 12
<  Total Memory: 31.26GiB
<  Name: summer
<  ID: 08b1daba-8485-4600-92a8-9ee226565b58
---
>  CPUs: 2
>  Total Memory: 7.643GiB
>  Name: foxtrot
>  ID: EVTZ:K32K:JUGF:2T62:YUUD:34S6:T4C3:LJK6:D7DR:VLME:LRH5:B7T3
50a46,47
>  Registry: https://index.docker.io/v1/
>  Labels:
55d51
<
```

**Comment by vogler** [comment]
Let's continue this in #187.
