### ISSUE TITLE
help page.click: Timeout 20000ms exceeded

### ISSUE THREAD

**Issue by gabbelitoV2** [vogler/free-games-claimer#177]
i get this error how to fix it
i run node epic-games
![image](https://github.com/vogler/free-games-claimer/assets/128819414/bd9a69c7-a384-45e3-8a83-70bb9c8e304e)

**Comment by vogler** [comment]
Use `RECORD=1` to record a video and see what's going on. The locator hasn't changed, so either there's some popup (is it a new account?) or your hardware is too slow for the timeout.

**Comment by gabbelitoV2** [comment]
how to use RECORD=1

**Comment by gabbelitoV2** [comment]
when i download on latest releases 
then it works, but an error still occurred

**Comment by gabbelitoV2** [comment]
now it happened again

**Comment by gabbelitoV2** [comment]
![image](https://github.com/vogler/free-games-claimer/assets/128819414/cf796360-d133-48dd-9a3c-0adbce681b98)

**Comment by gabbelitoV2** [comment]
it was the latest in releases

**Comment by gabbelitoV2** [comment]
it's when you download that it doesn't work 
![image](https://github.com/vogler/free-games-claimer/assets/128819414/b9fad2b9-3aa3-4408-af26-8d1ce1f1eac8)

**Comment by gabbelitoV2** [comment]
something needs to be changed or something i think

**Comment by gabbelitoV2** [comment]
it is when the EPIC GAMES STORE END USER LICENSE AGREEMENT 
then it stops working I think

**Comment by gabbelitoV2** [comment]
I ran SHOW=1 and then I saw that it stopped there

**Comment by gabbelitoV2** [comment]
this ![image](https://github.com/vogler/free-games-claimer/assets/128819414/f106e280-a665-471e-b304-51016efc8734)

**Comment by vogler** [comment]
That's what I meant by new account. There is code that should handle this,
but maybe something changed. Can you share the DOM of the popup? You can
just go to that point in your local browser, inspect (ctrl-shift-c) the
license agreement popup and copy the HTML of the element.
Can't do it on my account since it's not shown anymore after you accept it.

gabbelitoV2 ***@***.***> schrieb am Mi., 9. Aug. 2023, 14:09:

**Comment by gabbelitoV2** [comment]
![image](https://github.com/vogler/free-games-claimer/assets/128819414/154141d9-5ef9-44e2-af2c-5598d9c1d891)
and
![image](https://github.com/vogler/free-games-claimer/assets/128819414/bd93d917-2455-49e2-a4eb-9ef6c5a02892)

is this correct?

**Comment by gabbelitoV2** [comment]
![image](https://github.com/vogler/free-games-claimer/assets/128819414/bee89baa-bef4-4ae1-8527-45a0b1b28868)
and
![image](https://github.com/vogler/free-games-claimer/assets/128819414/7803ec26-c0b6-4f06-b4a8-f7742d0284b7)

is this correct

**Comment by vogler** [comment]
Thanks!
https://github.com/vogler/free-games-claimer/blob/b5ead8ea21129830596f7058775c97e9832813e9/epic-games.js#L163-L168
Looks like nothing changed.

According to your log, you run an outdated version. There's no more `text=Thank you for buying`, so of course you'll get a timeout waiting for it.

**Comment by gabbelitoV2** [comment]
run on the latest version that I download on the green code button

**Comment by gabbelitoV2** [comment]
That's the one I downloaded on Releases and it works
it was the one on the green code button that I downloaded that didn't work

**Comment by gabbelitoV2** [comment]
oh i think i fixed it think i had the old version

**Comment by vogler** [comment]
Ok, I'll close this then.
