### ISSUE TITLE
Robot Request

### ISSUE THREAD

**Issue by MrIceman11** [vogler/free-games-claimer#178]
Hello,

first of all, thanks for the cool Docker container! I've been running the container for some time now. Unfortunately, the latest problem is that I get a robot query at the Ebic Games Store. (Attached is a picture) Is there a trick to get around this? Unfortunately, it does not work, if I solve the Puzzle, then comes `invalid session please reload page`. Maybe one of you has an idea what to do. 

Thanks a lot

![grafik](https://github.com/vogler/free-games-claimer/assets/63753470/b81f0664-58e6-4e6b-87e8-8fc8bc6dd07f)

**Comment by neomanyouth** [comment]
For what it's worth I've also started getting catpchas at this stage in the purchase on Epic, but solving then manually works fine.

**Comment by MrIceman11** [comment]
ok thanks, after i reinstalled the container it works again. 

Issue can be closed.

**Comment by MrIceman11** [comment]
Hi now i have the same error again. 

Does anyone have a solution yet?

Thangs

**Comment by MrIceman11** [comment]
Hi now i have the same error again. 

Does anyone have a solution yet?

Thangs

**Comment by vogler** [comment]
Closing this in favor of some other one. No point in having the same issue 5x.
