### ISSUE TITLE
Use nocaptchaai.com for hcaptcha challenges?

### ISSUE THREAD

**Issue by gabbelitoV2** [vogler/free-games-claimer#179]
I have found an hcaptcha solver that is free you get 200 a day then after 24 hours you get 200 new ones
https://nocaptchaai.com/
you could put it in the code

**Comment by vogler** [comment]
There's code for using https://www.nopecha.com:
https://github.com/vogler/free-games-claimer/blob/b5ead8ea21129830596f7058775c97e9832813e9/epic-games.js#L20-L21

However, you shouldn't get any captcha challenge. It'd be better to find out the reason why you get them (too many failed logins per IP?), rather than trying to work around it.

**Comment by gabbelitoV2** [comment]
> 

okay

how do you get it in the code

**Comment by vogler** [comment]
You should be able to just add any extension when the browser is open (e.g. when waiting for login).

**Comment by gabbelitoV2** [comment]
![image](https://github.com/vogler/free-games-claimer/assets/128819414/e6cc5aad-4170-4f92-a003-080b1db966b9)
that's what I did but it doesn't solve the hcaptcha

**Comment by vogler** [comment]
If you want to do it like that, you need to add back the `nopecha` directory which was removed [in this commit](https://github.com/vogler/free-games-claimer/commit/ec2d31ed793ac0b14d8a6265ec68e0e80abc5854).

**Comment by gabbelitoV2** [comment]
have done it

but I can only add the extension myself

**Comment by gabbelitoV2** [comment]
I can add https://nocaptchaai.com/ myself

or will it disappear if I restart the computer?

**Comment by gabbelitoV2** [comment]
can you not put in nocaptchaai.com for me it says I have vpn on NopeCHA even though I don't

**Comment by gabbelitoV2** [comment]
the other works https://nocaptchaai.com/

**Comment by vogler** [comment]
Playwright doesn't support loading extensions in Firefox: https://github.com/microsoft/playwright/issues/7297

Was there a problem with just manually adding the extension in the browser? As long as you don't delete `data/browser` it should keep working.

If you want to integrate it in the code you can:
1. change the browser back to Chromium and load the extension
2. try one of the workarounds in https://github.com/microsoft/playwright/issues/7297 for loading the extension in Firefox

However, I'd recommend looking into why you are getting a captcha challenge in the first place.
Do you share your IP (CGNAT etc.)? Do you get captcha challenges in your normal browser?

**Comment by yoshimo** [comment]
If the connection offers both Ipv4 and v6 do you use the v6 one? Many isps share one v4 adress for multiple users by default.

**Comment by vogler** [comment]
Whatever Firefox will do, I guess it should prefer IPv6.
You can check https://ipv6-test.com, but it's not very reliable for me.
