### ISSUE TITLE
be more verbose about missing linked accounts for Prime

### ISSUE THREAD

**Issue by yoshimo** [vogler/free-games-claimer#180]
Instead of printing multiple lines like

```
Current DLC: League of Legends - BONK! Emote
  Missing account linking: Link account

```

it would be great if you grouped them by missing account-type and extended it to  "Link Riot Games account"

**Comment by vogler** [comment]
Store should be mentioned now.
<img width="588" alt="image" src="https://github.com/vogler/free-games-claimer/assets/493741/b1fcecca-4892-4e33-a981-d7d9163e86b9">

Is grouping that helpful? You can just search for e.g. 'Riot Games' and it will highlight all the DLCs for that store.

**Comment by vogler** [comment]
Added some grouped output, but haven't tested it 🙈
