### ISSUE TITLE
Unable to claim unrated games

### ISSUE THREAD

**Issue by Blu-Tiger** [vogler/free-games-claimer#184]
Game with the warning page
"contains content that is unrated and may not be appropriate for all ages."
fail the claim.

**Comment by vogler** [comment]
Context?
You mean https://store.epicgames.com/en-US/p/black-book?
Not a problem here:
```
SHOW=1 DRYRUN=1 node epic-games.js
2023-08-18 22:11:17.970 started checking epic-games
Signed in as kigu1
Free games: [
  'https://store.epicgames.com/en-US/p/black-book',
  'https://store.epicgames.com/en-US/p/dodo-peak-159276'
]
  This game contains mature content recommended only for ages 18+
Current free game: Black Book
  Not in library yet! Click GET.
  DRYRUN=1 -> Skip order!
Current free game: Dodo Peak
  Not in library yet! Click GET.
  DRYRUN=1 -> Skip order!
```

**Comment by Blu-Tiger** [comment]
Exactly but for some reason fails, I thought it wasn't implemented yet, i will try looking at the logs

**Comment by Blu-Tiger** [comment]
Exactly but for some reason fails, I thought it wasn't implemented yet, it was the captcha an I didn't notice, sorry to bother.

**Comment by vogler** [comment]
Was the captcha challenge mentioned in the log? If yes, you can close this.

Seems like people have been getting more captcha challenges recently. You can add your setup/environment in one of those recent issues.
