### ISSUE TITLE
can't pull docker image in China

### ISSUE THREAD

**Issue by shanlanCoding** [vogler/free-games-claimer#186]
I am a user from China due to our national firewall. When I use Docker Pull, I am prompted not found, and I have tried proxy services with the same prompt.
Is there any other way to download images?
In addition, when I use the command line you provided to pull the image, the Docker will prompt "unknown flag: -- pull", as shown in the following figure:
![image](https://github.com/vogler/free-games-claimer/assets/44717382/74db3965-c9ac-410c-a366-3e8e375ca3fd)

Chinese：
我是来自中国的用户，由于我们国家防火墙的原因。我使用docker pull的时候提示not found，我尝试过代理服务同样是这个提示。

请问还有其他的下载镜像的方法吗？

另外我使用你提供的命令行拉取镜像会被docker提示“unknown flag: --pull”，如下图：

**Comment by vogler** [comment]
> I am a user from China due to our national firewall. When I use Docker Pull, I am prompted not found, and I have tried proxy services with the same prompt.

I guess you have to figure that out yourself since I can't try anything for you.
Apparently there are mirrors of the Docker registry for access in China:
https://stackoverflow.com/questions/28957330/acclerate-docker-pull-in-china-asia/47569760#47569760
Alternatively, use a proxy or VPN:
https://stackoverflow.com/questions/30434897/unable-to-connect-to-docker-hub-from-china

> Docker will prompt "unknown flag: -- pull"

Maybe your Docker version is too old? The flag just makes it pull updates before every run. You can also manually `docker pull` yourself. However, you're using two different URLs: docker.io in you `docker pull` and ghcr.io in your `docker run` command.

**Comment by shanlanCoding** [comment]
> > I am a user from China due to our national firewall. When I use Docker Pull, I am prompted not found, and I have tried proxy services with the same prompt.
> 
> I guess you have to figure that out yourself since I can't try anything for you. Apparently there are mirrors of the Docker registry for access in China: https://stackoverflow.com/questions/28957330/acclerate-docker-pull-in-china-asia/47569760#47569760 Alternatively, use a proxy or VPN: https://stackoverflow.com/questions/30434897/unable-to-connect-to-docker-hub-from-china
> 
> > Docker will prompt "unknown flag: -- pull"
> 
> Maybe your Docker version is too old? The flag just makes it pull updates before every run. You can also manually `docker pull` yourself. However, you're using two different URLs: docker.io in you `docker pull` and ghcr.io in your `docker run` command.
> 
> Is ghcr.io blocked as well?

Thank you for your reply. Regarding the issue of not being able to pull the image, I have already pulled it through an overseas online docker learning website and pushed it to our domestic private image server, so the first issue has been resolved.

Regarding the issue of 'Docker will prompt' unknown flag: -- pull ', it should be that my Docker version is too old and I do not intend to use this parameter.

Now I have configured config.env and the startup command is: 'Docker run -- rm - p 6080:6080- v fgc:/fgc/data -- env file=/fgc/config.env ec6dd9a5995d node epic games' 
Prompt after startup:
```
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080

node[17]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xbf9890 node::Abort() [node]
 2: 0xbf990e  [node]
 3: 0xc689ae  [node]
 4: 0xc68a91 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xbb70c3  [node]
 6: 0xbb78db node::Start(int, char**) [node]
 7: 0x7feaba7b0d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7feaba7b0e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
```

The screenshot is as follows:
![image](https://github.com/vogler/free-games-claimer/assets/44717382/8843e1f8-1f6b-4de9-ab65-ada8076fb930)

This is a screenshot of the content of the env file:
![1692582750043](https://github.com/vogler/free-games-claimer/assets/44717382/4af114ff-a32f-49f1-9a0d-61b421ee4ecc)

Looking forward to your reply and wishing you a happy life

**Comment by vogler** [comment]
```
node[17]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
```

Looks like you have some limit on the number of processes. You can check `ulimit -a`. See https://github.com/nodejs/help/issues/1754.
You can try `docker run --privileged`, see https://docs.docker.com/engine/reference/commandline/run/#privileged.

Some people say the problem was resolved for them by upgrading docker:
- https://github.com/browserless/chrome/issues/2862
- https://github.com/nodejs/node/issues/43064

What `docker version` are you using?

**Comment by shanlanCoding** [comment]
this is my docker info :
```
***@***.*** config]# docker info
Containers: 8
&nbsp;Running: 1
&nbsp;Paused: 0
&nbsp;Stopped: 7
Images: 6
Server Version: 1.13.1
Storage Driver: overlay2
&nbsp;Backing Filesystem: xfs
&nbsp;Supports d_type: true
&nbsp;Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
&nbsp;Volume: local
&nbsp;Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc docker-runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:&nbsp; (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 8891bca22c049cd2dcf13ba2438c0bac8d7f3343 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
&nbsp;seccomp
&nbsp; WARNING: You're not using the default seccomp profile
&nbsp; Profile: /etc/docker/seccomp.json
&nbsp;selinux
Kernel Version: 3.10.0-1160.76.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 6
Total Memory: 5.661 GiB
Name: localhost.localdomain
ID: 275V:XDYX:DQ2Z:ZU6I:CYDH:AULS:H56D:TICM:NHNA:X5YY:DZPZ:OLP7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
&nbsp;127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)



```
&nbsp;


两载
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月21日(星期一) 下午5:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vogler/free-games-claimer] can&#39;t pull docker image in China (Issue #186)





结节[17]: ../src用户名:/node_platformunique_ptr<long无符号《国际互联网》node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): 断言（0）==（uv_thread_create（t.get,start_thread,this））失败了。
看起来你对进程的数量有一些限制。您可以检查ulimit -a. 看见用户评论#1754.
你可以试试Docker运行--特权，请看https://docs.docker.com/engine/reference/commandline/run/特权.

有人说这个问题是通过升级Docker为他们解决的：

浏览器/铬#2862

nodejs/node#43064

什么Docker版本你在用吗？

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by shanlanCoding** [comment]
Thank you for your help. I have already solved my problem. I added the '-- privileged' command as follows:
`docker run --rm -p 6080:6080 -v fgc:/fgc/data  --env-file=/fgc/config.env --privileged ec6dd9a5995d node epic-games`

**Comment by Pray3** [comment]
> -- privileged

-- privileged is work ,Thank you for your help.
i added in docker-compose.yml as follows:
```shell
browserless:  # marked
        image: browserless/chrome  # marked
        restart: always  # marked
        privileged: true
```
