### ISSUE TITLE
[Store] Xbox Live Gold monthly free games

### ISSUE THREAD

**Issue by vogler** [vogler/free-games-claimer#19]
https://www.xbox.com/en-US/live/gold#gameswithgold
Usually two Xbox One and one Xbox 360 game per month?
Also interesting for people who use Game Pass Ultimate without an Xbox since some games are playable on PC and you can collect games before getting an Xbox.

**Comment by klept0** [comment]
scrape reddit subreddit /r/GreatXboxDeals for title:'free' - they are posted there monthly

**Comment by vogler** [comment]
The monthly games are already listed reliably at the URL above.
You mean for other temporarily free games? The ones with 'free' in the title I tried didn't work for me anymore or I already had them. If there's a list of currently available free games, one could add it. Going through a feed (how far?) of maybe outdated URLs seems like too much overhead.

**Comment by klept0** [comment]
I was thinking of how I use IFTTT to notify me of the links directly - Ill test it out when you are ready and thanks for the work!

**Comment by kennymc-c** [comment]
If this gets implemented it would also be good to check all Xbox store regions. Sometimes one or two regions have different games, especially Japan and South Korea. Most of the time claiming works with accounts from other regions as well. There's a list which shows when this happened in the past: https://xbox.fandom.com/wiki/List_of_Games_with_Gold

**Comment by OJ7** [comment]
DekuDeals is a pretty good source for this information by using filters, but you need to have an account and specify which subscription you have if you want GWG.

With an account, shows all games available to keep with subscription(s): https://www.dekudeals.com/games?filter[price_range][min]=&filter[price_range][max]=0.00&filter[discount]=discounted

And then different regions can be checked to find which ones are free there.

The following can be used to find games that are discounted to free without the need of a subscription (if you aren't logged in):
- [Xbox Series](https://www.dekudeals.com/games?filter[price_range][min]=&filter[price_range][max]=0&filter[discount]=discounted&filter[format]=digital&filter[platform]=xbox_series&include[all_platforms]=true)
- [Xbox One](https://www.dekudeals.com/games?filter%5Bprice_range%5D%5Bmin%5D=&filter%5Bprice_range%5D%5Bmax%5D=0&filter%5Bdiscount%5D=discounted&filter%5Bformat%5D=digital&include%5Ball_platforms%5D=true&filter%5Bplatform%5D=xbox_one)

**Comment by vogler** [comment]
There's a bit of 'microsoft games' code for `PG_REDEEM`, but likely not that useful for Xbox Live Gold:
https://github.com/vogler/free-games-claimer/blob/feadfc5acf6dfe1fc05493c8c2eaa1d84e7696d0/prime-gaming.js#L205C11-L227

**Comment by vogler** [comment]
Thanks!

The xbox branch is based on the psn one? Can you rebase it on main such that PRs can be independent? Otherwise we have to do psn first.

I currently don't have Xbox GPU, but maybe I'll start the subscription again soon.
