### ISSUE TITLE
Send Notification For Captcha

### ISSUE THREAD

**Issue by kevinmatthe** [vogler/free-games-claimer#191]
It seems to be sending notification only after all games was claimed(or tried) currently.
However, when using crontab to start a docker container, I could only receive captcha info after timout exceeded, and was not able to Resolve it in VNC;
Is it supposed to add a notification that sends after meeting captcha?(or any other situation requires VNC)

**Comment by kevinmatthe** [comment]
It seems to be set in code, however it's not working, I'll check this

**Comment by kevinmatthe** [comment]
I got a fix in this PR #195 (I'm not familiar in front-end develop, so if there's any problem, please just directly point out~

**Comment by vogler** [comment]
The async/await shouldn't make a difference.
Did you already get a captcha during login?
You probably stay logged in and just got a captcha during checkout, and there's not `notify` there.
I can add one there as well.
