### ISSUE TITLE
GoG Giveaway fails with Cannot read properties of null 

### ISSUE THREAD

**Issue by yoshimo** [vogler/free-games-claimer#198]
Right now you can grab a free copy of
https://www.gog.com/en/game/hero_of_the_kingdom_ii for 65h
but it does give me only:

```
TypeError: Cannot read properties of null (reading '1')
    at file:///fgc/gog.js:95:43
````

**Comment by KairuByte** [comment]
Are you ensuring you're running latest? The mentioned game was successfully grabbed on two accounts this morning at about 16:05am UTC.

**Comment by vogler** [comment]
Works for me. Feel free to reopen.

**Comment by romquenin** [comment]
Hello, i've just installed FGC on docker (synology) and i'm getting the same error 

```
2024-08-26 16:29:13.853 started checking gog
Signed in as usermodified
--- Exception:
TypeError: Cannot read properties of null (reading '1')
    at file:///fgc/gog.js:102:62
```

Note that the first time i ran the GOG's node, it claimed the available game properly

**Comment by vogler** [comment]
Works for me:
![image](https://github.com/user-attachments/assets/979ab17f-4661-47a8-a27a-2c7f98d353e9)

Is 'usermodified' really your user name or did something with the login not work?
Can you run it with `RECORD=1`  to see what's going on?

**Comment by MXF2468** [comment]
Hi.  I have the same error.  Correct user name.  Sorry for the dumb question, but where do I put RECORD=1 in docker run --rm -it -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer

At the end gives me an error.  Sorry, I don't usually do command-line stuff.  Thanks.

**Comment by vogler** [comment]
> At the end gives me an error.

@MXF2468 Anywhere but at the end :) If a program accepts named (-x/--xyz) and unnamed (xyz, here the image) options, the unnamed ones usually have to be at the end.

README:
> You can pass variables using -e VAR=VAL, for example docker run -e EMAIL=foo@bar.baz -e NOTIFY='tgram://bottoken/ChatID' ... or using --env-file fgc.env where fgc.env is a file on your host system (see [docs](https://docs.docker.com/engine/reference/commandline/run/#env)).
