### ISSUE TITLE
GOG: Trusted Partners

### ISSUE THREAD

**Issue by yoshimo** [vogler/free-games-claimer#200]
![grafik](https://github.com/vogler/free-games-claimer/assets/17909/6c228f69-144a-4cfb-846c-68c226f59c71)

Claiming free games checks this box too.
It would be great to have FGC disable this optionally like the promotions newsletter.

**Comment by KairuByte** [comment]
Ah, yeah I forgot about this issue. When people shared links to auto claim, they always shared a second link to allow you to turn that back off. Might be a good idea to implement that.

**Comment by vogler** [comment]
> they always shared a second link to allow you to turn that back off.

Do you have the link?
