### ISSUE TITLE
Amazon Prime Gaming in game content claims fail

### ISSUE THREAD

**Issue by KairuByte** [vogler/free-games-claimer#208]
It appears that the in game content claims have all started using the "multi week" claims, where you need to click not only into the games page, but also "claim" on the specific reward you want in order to actually reach the claiming page. If you watch the bot work, you'll see what I mean because it stalls for a long while waiting for the content it expects.

**Comment by yoshimo** [comment]
The new sub pages create errors like


`Current DLC: Shadow Fight 3 - Legendary Keys
[AggregateError: All promises were rejected] {
  [errors]: [
    page.click: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Get in-game content")')
    ============================================================
        at file:///fgc/prime-gaming.js:347:33 {
      name: 'TimeoutError'
    },
    page.click: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Claim your gift")')
    ============================================================
        at file:///fgc/prime-gaming.js:347:87 {
      name: 'TimeoutError'
    },
    page.click: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Claim now")')
    ============================================================
        at file:///fgc/prime-gaming.js:347:137 {
      name: 'TimeoutError'
    }
  ]
}
Current DLC: The Crew Motorfest - Freedom Bundle
[AggregateError: All promises were rejected] {
  [errors]: [
    page.click: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Get in-game content")')
    ============================================================
        at file:///fgc/prime-gaming.js:347:33 {
      name: 'TimeoutError'
    },
    page.click: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Claim your gift")')
    ============================================================
        at file:///fgc/prime-gaming.js:347:87 {
      name: 'TimeoutError'
    },
    page.click: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Claim now")')
    ============================================================
        at file:///fgc/prime-gaming.js:347:137 {
      name: 'TimeoutError'
    }
  ]
}
`

**Comment by Primajin** [comment]
Yeah it looks for a button called "Claim now" - however the button is just called "Claim" now and thus it fails.

**Comment by Mrgaton** [comment]
`[AggregateError: All promises were rejected] {
  [errors]: [
    page.click: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('button:has-text("Get in-game content")')

        at free-games-claimer\prime-gaming.js:352:33,
    page.click: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('button:has-text("Claim your gift")')

        at free-games-claimer\prime-gaming.js:352:87,
    page.click: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('button:has-text("Claim now")')

        at free-games-claimer\prime-gaming.js:352:137
  ]
}
[AggregateError: All promises were rejected] {
  [errors]: [
    page.click: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('button:has-text("Get in-game content")')

        at free-games-claimer\prime-gaming.js:352:33,
    page.click: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('button:has-text("Claim your gift")')

        at free-games-claimer\prime-gaming.js:352:87,
    page.click: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('button:has-text("Claim now")')

        at free-games-claimer\prime-gaming.js:352:137
  ]
}`

same :C

**Comment by Mrgaton** [comment]
![image](https://github.com/vogler/free-games-claimer/assets/68958481/5fe22849-4361-4080-95fc-08cc1948fa89)
Also it doesnt claim this things

**Comment by KairuByte** [comment]
I'm seeing the same issue after updating to latest code. I confirmed prime-gaming.js has the two changes listed in the PR, but the bot still sits on the pre-claim page.

**Comment by Primajin** [comment]
Hmm even with the newest image it still looks for "Claim Now" not "Claim" 🤔 

```
[AggregateError: All promises were rejected] {
  [errors]: [
    page.click: Timeout 15000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Get in-game content")')
    ============================================================
        at /fgc/prime-gaming.js:352:33 {
      name: 'TimeoutError'
    },
    page.click: Timeout 15000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Claim your gift")')
    ============================================================
        at /fgc/prime-gaming.js:352:87 {
      name: 'TimeoutError'
    },
    page.click: Timeout 15000ms exceeded.
    =========================== logs ===========================
    waiting for locator('button:has-text("Claim now")')
    ============================================================
        at /fgc/prime-gaming.js:352:137 {
      name: 'TimeoutError'
    }
  ]
}
```

**Comment by Primajin** [comment]
OK I think I found the issues:

1. The latest image is only published under `:main` not under `:latest`.

![Screenshot 2023-12-22 161837](https://github.com/vogler/free-games-claimer/assets/1742115/33071a92-74ff-42ab-b4a3-67755ce9b2a1)

This works much better and it recognizes when I don't have an account linked:

![Screenshot 2023-12-22 161910](https://github.com/vogler/free-games-claimer/assets/1742115/d583248f-fd9e-447d-90e5-9624e63dca1b)

However eventually it still fails on a couple of titles with one of two errors:

![Screenshot 2023-12-22 161820](https://github.com/vogler/free-games-claimer/assets/1742115/3f4beb3b-ac42-4ba4-8208-884958e0473b)
![Screenshot 2023-12-22 162428](https://github.com/vogler/free-games-claimer/assets/1742115/4eabcf39-06c5-4926-b95f-47b5e72afa2c)

This is because our friends at Amazon sometimes use a button and sometimes use an anchor link in the HTML:

![Screenshot 2023-12-22 162726](https://github.com/vogler/free-games-claimer/assets/1742115/00e42279-0ca7-4fa3-a1a2-5c065da4ac10)
![Screenshot 2023-12-22 162604](https://github.com/vogler/free-games-claimer/assets/1742115/0b3f5cdc-eb3b-4c16-90b3-56e950146456)

So I guess we need to make the script versatile enough to check for either a button or a link with the given text.

**Comment by Mrgaton** [comment]
![image](https://github.com/vogler/free-games-claimer/assets/68958481/f57cc095-157b-4d17-b1bd-e08aa9fdb06b)
yes still not claiming it

**Comment by vogler** [comment]
> The latest image is only published under `:main` not under `:latest`.

Probably due to #229. However, the code looks like it should publish `main` as `latest`:
https://github.com/vogler/free-games-claimer/blob/9f97805517041e60dddd90274c02834165ae6a1f/.github/workflows/docker.yml#L32-L36

Don't use `latest` since it has no meaning, just use `--pull=always`.

**Comment by vogler** [comment]
> So I guess we need to make the script versatile enough to check for either a button or a link with the given text - or instead look for the css class `.tw-button`

Why not `span:has-text()` instead of the css class?

**Comment by Primajin** [comment]
OK I tested it again and now it should work with #274 . I changed the selector to account for both types of buttons and in case there are more than one account link buttons, it will take the first one.


Fixes:
![Screenshot 2023-12-23 112602](https://github.com/vogler/free-games-claimer/assets/1742115/c3fb53e9-a181-467f-92b4-9e25a014a6e1)

Fixes:
![Screenshot 2023-12-23 112249](https://github.com/vogler/free-games-claimer/assets/1742115/b2a61423-122c-4ce3-bfc0-c239eed27095)

![Screenshot 2023-12-23 115421](https://github.com/vogler/free-games-claimer/assets/1742115/58777674-fce2-469c-9896-3a7790c44dab)

**Comment by vogler** [comment]
Can check/merge after lunch.

**Comment by Primajin** [comment]
> > So I guess we need to make the script versatile enough to check for either a button or a link with the given text - or instead look for the css class `.tw-button`
> 
> Why not `span:has-text()` instead of the css class?

Yeah I guess that could also work

**Comment by vogler** [comment]
@sealldeveloper I ignore the timeout now. However, it would be better to add a case for this. For which item does this happen - what is there instead of a code or account linking?
