### ISSUE TITLE
Epic Games: timeout waitFor `a:has(span:text-is("Free Now"))`

### ISSUE THREAD

**Issue by AytoMaximo** [vogler/free-games-claimer#210]
I can successfully log in to Epic Games; however, it can't find a certain locator for free games. Here's the terminal log:

```
2023-09-17 08:27:00.676 started checking epic-games
Signed in as Ayto Maximo
locator.waitFor: Timeout exceeded 60000ms.
=========================== logs ===========================
waiting for locator('a:has(span:text-is("Free Now"))').last() to be visible
============================================================
    at file:///fgc/epic-games.js:124:25 {
  name: 'TimeoutError'
}
2023-09-17 08:28:05.502 started checking prime-gaming
```

**Comment by vogler** [comment]
Can't reproduce:
```console
$ DRYRUN=1 node epic-games.js
2023-09-17 10:39:39.202 started checking epic-games
Signed in as *
Free games: [ 'https://store.epicgames.com/en-US/p/911-operator-585edd' ]
  This game contains mature content recommended only for ages 18+
Current free game: 911 Operator
  Not in library yet! Click GET.
  DRYRUN=1 -> Skip order!
```

Try running it with `SHOW=1 PWDEBUG=1` to see what's going on and step through in the debugger.
I guess either the page doesn't load completely/fast enough or the language is different (however, don't know why it should be). What region is the account?

**Comment by AytoMaximo** [comment]
> Try running it with `SHOW=1 PWDEBUG=1` to see what's going on and step through in the debugger.

With these params it can't run at all:

```
PS C:\Users\admin> docker run -e SHOW=1 -e PWDEBUG=1 --rm -it -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer
latest: Pulling from vogler/free-games-claimer
Digest: sha256:0d16ca7896ae79a50d71aea36cd86c520bb031b84fdcdc7a87bf5a8537430969
Status: Image is up to date for ghcr.io/vogler/free-games-claimer:latest
Version: https://github.com/vogler/free-games-claimer/tree/44d712e333c6952d4aadc6a9a7b4865a4511227b
Build: Mon, 11 Sep 2023 07:42:01 +0000
Xvfb display server created screen with resolution 1920x1080
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080

2023-09-18 06:13:57.413 started checking epic-games
node:internal/process/esm_loader:48
      internalBinding('errors').triggerUncaughtException(
                                ^

browserType.launchPersistentContext:
╔═══════════════════════════════════════════════════╗
║ No chromium-based browser found on the system.    ║
║ Please run the following command to download one: ║
║                                                   ║
║     npx playwright install chromium               ║
║                                                   ║
║ <3 Playwright Team                                ║
╚═══════════════════════════════════════════════════╝
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1422/firefox/firefox -no-remote -wait-for-browser -foreground -profile /fgc/data/browser -juggler-pipe --hide-crash-restore-bubble about:blank
<launched> pid=211
[pid=211][out] console.warn: services.settings: Ignoring preference override of remote settings server
[pid=211][out] console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
[pid=211][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.261835) [GFX1-]: glxtest: libpci missing
[pid=211][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.261835) |[1][GFX1-]: glxtest: libEGL missing (t=0.261903) [GFX1-]: glxtest: libEGL missing
[pid=211][out]
[pid=211][out] Juggler listening to the pipe
============================================================
    at async file:///fgc/epic-games.js:25:17

Node.js v20.6.0
2023-09-18 06:14:01.061 started checking prime-gaming
node:internal/process/esm_loader:48
      internalBinding('errors').triggerUncaughtException(
                                ^

browserType.launchPersistentContext:
╔═══════════════════════════════════════════════════╗
║ No chromium-based browser found on the system.    ║
║ Please run the following command to download one: ║
║                                                   ║
║     npx playwright install chromium               ║
║                                                   ║
║ <3 Playwright Team                                ║
╚═══════════════════════════════════════════════════╝
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1422/firefox/firefox -no-remote -wait-for-browser -foreground -profile /fgc/data/browser -juggler-pipe about:blank
<launched> pid=633
[pid=633][out] console.warn: services.settings: Ignoring preference override of remote settings server
[pid=633][out] console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
[pid=633][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.197806) [GFX1-]: glxtest: libpci missing
[pid=633][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.197806) |[1][GFX1-]: glxtest: libEGL missing (t=0.197905) [GFX1-]: glxtest: libEGL missing
[pid=633][out]
[pid=633][out] Juggler listening to the pipe
============================================================
    at async file:///fgc/prime-gaming.js:18:17

Node.js v20.6.0
2023-09-18 06:14:04.601 started checking gog
node:internal/process/esm_loader:48
      internalBinding('errors').triggerUncaughtException(
                                ^

browserType.launchPersistentContext:
╔═══════════════════════════════════════════════════╗
║ No chromium-based browser found on the system.    ║
║ Please run the following command to download one: ║
║                                                   ║
║     npx playwright install chromium               ║
║                                                   ║
║ <3 Playwright Team                                ║
╚═══════════════════════════════════════════════════╝
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1422/firefox/firefox -no-remote -wait-for-browser -foreground -profile /fgc/data/browser -juggler-pipe about:blank
<launched> pid=1037
[pid=1037][out] console.warn: services.settings: Ignoring preference override of remote settings server
[pid=1037][out] console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
[pid=1037][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.197298) [GFX1-]: glxtest: libpci missing
[pid=1037][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.197298) |[1][GFX1-]: glxtest: libEGL missing (t=0.197361) [GFX1-]: glxtest: libEGL missing
[pid=1037][out]
[pid=1037][out] Juggler listening to the pipe
============================================================
    at async file:///fgc/gog.js:16:17

Node.js v20.6.0
```

While my region is not primarily English-speaking, I'm uncertain about the actual language your hidden browser uses to open the Epic Games site. Even though my Windows is set up in English, all websites initially open in English for me.

**Comment by vogler** [comment]
Ok, apparently `PWDEBUG=1` does not work in the docker image; #217.

> I'm uncertain about the actual language your hidden browser uses to open the Epic Games site.

It should be English.

Maybe you have some network-level filters (AdGuard DNS, Pi-hole etc.)? VPN shouldn't matter, but who knows.

Further options:
- Set `RECORD=1` to record a video (in `record` in the `fgc` docker volume)
- Watch what's happening via noVNC
- Run without docker and use `PWDEBUG=1` (if it's not already resolved by not running in docker)

**Comment by PriZZZrak** [comment]
I have same issue. in vnc open page: https://store.epicgames.com/en-US/free-games. and its all. nothing happens after.

**Comment by AytoMaximo** [comment]
About watching what's happening via noVNC:
![image](https://github.com/vogler/free-games-claimer/assets/14392087/1d993a5a-4be8-4eb4-86e5-86b4121549c7)

I see this page.

**Comment by Comamndershephard** [comment]
+1 to getting this to, use to work great, I did also upgrade to the latest version of unraid as well.

=========================== logs ===========================
waiting for locator('a:has(span:text-is("Free Now"))').last() to be visible
============================================================
    at file:///fgc/epic-games.js:125:25 {
  name: 'Error'
}
node:internal/process/esm_loader:48
      internalBinding('errors').triggerUncaughtException(
                                ^

browserContext.close: Target page, context or browser has been closed
    at async file:///fgc/epic-games.js:265:1 {
  name: 'Error'
}

Node.js v20.6.0
--- Exception:
locator.waitFor: Page closed
=========================== logs ===========================
waiting for locator('a:has(span:text-is("Free Now"))').last() to be visible
============================================================
    at file:///fgc/epic-games.js:125:25 {
  name: 'Error'
}
node:internal/process/esm_loader:48
      internalBinding('errors').triggerUncaughtException(
                                ^

browserContext.close: Target page, context or browser has been closed
    at async file:///fgc/epic-games.js:265:1 {
  name: 'Error'
}

Node.js v20.6.0
--- Exception:
locator.waitFor: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('a:has(span:text-is("Free Now"))').last() to be visible
============================================================
    at file:///fgc/epic-games.js:125:25 {
  name: 'TimeoutError'
}

**Comment by vogler** [comment]
I changed the default resolution from 1280x1280 to 1920x1080 here: [e30216c](https://github.com/vogler/free-games-claimer/commit/e30216c9b86a1d057442641b71547cad35267041), https://github.com/vogler/free-games-claimer/issues/183#issuecomment-1709993432 - try setting `WIDTH=1280 HEIGHT=1280` again.
Playwright should scroll the element into view, but maybe that does not work for you for some reason.
I don't know how this could depend on the host, but what resolution do you have there?

---

@AytoMaximo 
> I see this page.

Can't see the scrollbar of the inner Firefox (did all of the page load?). Can you scroll down to the 'Free Now' buttons that it waits for?

> Also, I can't seem to launch this via node.js because I don't understand how to pass environment variables in Windows. 

See https://github.com/vogler/free-games-claimer#configuration--options -> https://kinsta.com/knowledgebase/what-is-an-environment-variable/#how-to-work-with-environment-variables: `set "VAR_NAME=var_value"`

> Additionally, I can't find the env config file in File Explorer.

There is none (don't want to ship a git-ignored file). You create `data/config.env` and put definitions there.

**Comment by Comamndershephard** [comment]
I tried setting the res back to 1280, no difference, viewing via vnc it logs in and then does nothing, but logging in myself it seem like there is no free game to purchase could that cause it to bug out

**Comment by vogler** [comment]
> logging in myself it seem like there is no free game to purchase could that cause it to bug out

<img width="1272" alt="image" src="https://github.com/vogler/free-games-claimer/assets/493741/7a1ac4d4-77fc-4671-b01d-e784be4f1347">

How does it look like for you then?

**Comment by Comamndershephard** [comment]
Interesting, I don't see 911 operator. Logged out and tried a different browser that I hadn't used for an epic log in before and it still is missing.

![Untitled222](https://github.com/vogler/free-games-claimer/assets/111734884/649142b1-6d36-47d1-bdb9-6862aa5b3e44)

**Comment by Comamndershephard** [comment]
I think you are correct sir, I search 911 on epic no results, I'm in Australia must be an epic licensing thing, as I can see that same game on steam store. I shall wait until the next game come up and see what happens then.

thanks for the help

**Comment by AytoMaximo** [comment]
Ok, looks like we just have to wait until the next offerings :)

**Comment by AytoMaximo** [comment]
Yeah, I have two free games as of today, and the script is working. However, there's a new problem for me now... #183
