### ISSUE TITLE
restarting container fails

### ISSUE THREAD

**Issue by jumoog** [vogler/free-games-claimer#23]
when i restart the container i get this error:
**ozone_platform_x11.cc(246)] Missing X server or $DISPLAY**

**Comment by vogler** [comment]
Can you give some background? Why do you need to restart it? Why does it behave differently when restarted?

**Comment by jumoog** [comment]
i added a livecheck and sometimes it stopped working. When it happens i restart it.

**Comment by jumoog** [comment]
it's related to https://github.com/puppeteer/puppeteer/issues/8148
