### ISSUE TITLE
Epic no longer loging in

### ISSUE THREAD

**Issue by DuzAwe** [vogler/free-games-claimer#236]
Epic login form never auto-fills. I can log in via VNC by providing the email and the script seems to take over again. Works fine for GOG

**Comment by ezek1el** [comment]
I concur. No longer logging in automatically.

```
Exception:
locator.innerHTML: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('#user span').first()
============================================================
    at file:///fgc/epic-games.js:117:51 {
  name: 'TimeoutError'
}
--- Exception:
locator.innerHTML: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('#user span').first()
============================================================
    at file:///fgc/epic-games.js:117:51 {
  name: 'TimeoutError'
}
--- Exception:
locator.innerHTML: Page closed
=========================== logs ===========================
waiting for locator('#user span').first()
============================================================
    at file:///fgc/epic-games.js:117:51 {
  name: 'Error'
}
--- Exception:
locator.innerHTML: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('#user span').first()
============================================================
    at file:///fgc/epic-games.js:117:51 {
  name: 'TimeoutError'
}
```

**Comment by carrothu-cn** [comment]
Same problem when setting up epic account.

**Comment by 4n4n4s** [comment]
@vogler elements just for account on top right seem to be gone somehow. Strange thing is when you open it in normal browser they are there.

**Comment by p6002** [comment]
Same here, gotify sending some strange notification:
<img width="401" alt="image" src="https://github.com/vogler/free-games-claimer/assets/74392057/10a53024-60bf-4349-b77a-d88d60e518d7">

**Comment by mattleh** [comment]
possible solution would be to replace:
user = await page.locator('#user span').first().innerHTML();
with:
user = await page.getByLabel("Account Menu").getAttribute('Title');

but i'm not sure if the returned value is the same.

**Comment by vogler** [comment]
They changed the layout. Should be fixed now.

**Comment by p6002** [comment]
It seems to be working. 
It would be nice if ctrl+alt+delete buttons via noVNC would restart the container/service.
Currently I get a capcha notification on my watch, but when I'm home, the session has expired and I have to log into VM to restart the container so I can fill in the capcha.

**Comment by vogler** [comment]
@p6002 New issue/discussion?
However, I don't see how that should work. Either you solve the captcha right away or you don't in which case it will time out and the container will stop (so also no more VNC).
Until #183 is solved, I would just run it directly with `node`, then there's no captcha.

**Comment by ezek1el** [comment]
Looks like it is working again. Thanks!

**Comment by p6002** [comment]
> Either you solve the captcha right away or you don't in which case it will time out and the container will stop (so also no more VNC).

You're right, that's why there should be some option to restart the container, for example via the button in the upper right corner of noVNC ctrl+alt+del which currently does nothing.

**Comment by Albirew** [comment]
weird, i still have this issue even after a `git pull` and a `docker compose rm`...

```
2023-11-01 09:47:38.825 started checking epic-games
locator.innerHTML: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('#user span').first()
============================================================
    at file:///fgc/epic-games.js:107:51 {
  name: 'TimeoutError'
}
```

**Comment by p6002** [comment]
It works for few days after last issue.

**Comment by Albirew** [comment]
PS: i noticed a difference between before and now:
before:
`    at file:///fgc/epic-games.js:117:51 {`
now:
`    at file:///fgc/epic-games.js:107:51 {`
a 10 lines change.

**Comment by vogler** [comment]
Yea, no need to build the image, it's built on every push. The `docker-compose.yml` is just an example and likely won't change, so no need for git. The only thing you need to do is pull the new image, so `docker compose pull && docker compose up -d`.
