### ISSUE TITLE
timout error on logged on epic-games node in cmd

### ISSUE THREAD

**Issue by rtzon59** [vogler/free-games-claimer#237]
getting 'TimoutError' on node epic-games cmd check
"20000 ms exceeded"

**Comment by vogler** [comment]
Can you post the full log? It should include in which line it timed out.
(I assume no docker, running on Windows?)

**Comment by k3nj1** [comment]
hi @vogler 
not the user that opened the issue still this may help
posting the timeout in the docker container

Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080
2023-10-27 09:07:24.160 started checking epic-games
locator.innerHTML: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('#user span').first()
============================================================
    at file:///fgc/epic-games.js:107:51 {
  name: 'TimeoutError'
}
2023-10-27 09:08:36.575 started checking prime-gaming
Signed in as "Redacted"
Number of already claimed games (total): 37
Number of free unclaimed games (Prime Gaming): 0
Number of free unclaimed games (external stores): 0
2023-10-27 09:08:44.164 started checking gog
Signed in as "Redacted"
Currently no free giveaway!

**Comment by vogler** [comment]
Looks like you're running an outdated version. This has been fixed in #236.

**Comment by k3nj1** [comment]
image version in use is: 
ghcr.io/vogler/free-games-claimer:latest@sha256:ec6dd9a5995d57a7671f16a2bb3273e5eb9f0d079d23260b3a3ed589e06b5706
freshly updated when the test was done in the morning when the test was done in the morning

**Comment by vogler** [comment]
I don't see that hash anywhere here: https://github.com/vogler/free-games-claimer/pkgs/container/free-games-claimer/versions
Can you link to it?
Your log says `locator('#user span')` which was removed in https://github.com/vogler/free-games-claimer/commit/d73a523fe7f76608af5db4e72b567f058814fea1, so it can't be the current version.
