### ISSUE TITLE
GOG Timeout Error

### ISSUE THREAD

**Issue by QAQ5555** [vogler/free-games-claimer#240]
#started checking gog
#Signed in as ***
#Current free game: Blacksad: Under the Skin - https://gog.com/en/game/blacksad_under_the_skin
#--- Exception:
#locator.waitFor: Timeout 60000ms exceeded.
#=========================== logs ===========================
#waiting for locator('#giveaway:not(.is-loading)') to be visible
#============================================================
#at file:///fgc/gog.js:103:54 {
#name: 'TimeoutError'
#}
#sleeping

The free game has ended but it has not been detected and cannot be saved until it times out.

**Comment by televisi** [comment]
I received the same error on gog.
By the way, great script! thank you!

**Comment by Targunitoth** [comment]
It seems like a problem of GOG with Firefox, when you are logged in:
![grafik](https://github.com/vogler/free-games-claimer/assets/7016413/dbcbbcca-b8c4-4d22-b38f-a8d1a7a6cae2)
It loads if you are logged out or open the page with Crome:
![grafik](https://github.com/vogler/free-games-claimer/assets/7016413/20e25993-2252-4303-9893-0477e87eadd1)

**Comment by mgrimace** [comment]
I've been experiencing the same error, and in the meantime as a workaround I've been using GOG's autoclaim link: https://www.gog.com/giveaway/claim

Also in Discussion #242, it appears to be a simple .json output with `""` means claimed and if you visit the link a second time it should say `"already claimed"`. Might be useful to integrate this into the script if the current process is no longer working.

**Comment by 4n4n4s** [comment]
Same issue here. The bug is where a screenshot is taken of the banner we should skip that check.

**Comment by televisi** [comment]
> I've been experiencing the same error, and in the meantime as a workaround I've been using GOG's autoclaim link: https://www.gog.com/giveaway/claim
> 
> Also in Discussion #242, it appears to be a simple .json output with `""` means claimed and if you visit the link a second time it should say `"already claimed"`. Might be useful to integrate this into the script if the current process is no longer working.

Sorry, how do you that in the script? Unless you were referring to a manual website access?

**Comment by mgrimace** [comment]
> Sorry, how do you that in the script? Unless you were referring to a manual website access every second day?

Manually by visiting the link. It might be beneficial to use it in the script but I don’t know enough about coding to make that PR myself.

**Comment by vogler** [comment]
@mgrimace That's already what it does:
https://github.com/vogler/free-games-claimer/blob/3ddf1720bb10d1995bcf36a924805d5349ff8b63/gog.js#L107-L113

It just hangs to make a nicer screenshot...
https://github.com/vogler/free-games-claimer/blob/3ddf1720bb10d1995bcf36a924805d5349ff8b63/gog.js#L102

Commented it out for now which should fix the timeout.
Let me know when there's a new giveaway, then we can try to have a nice screenshot as well :)
