### ISSUE TITLE
Unreal engine login time out

### ISSUE THREAD

**Issue by wielorzeczownik** [vogler/free-games-claimer#248]
### Description:
There was an analogous problem with Epic Games itself so I'm betting that the changes to Epic also introduced logging changes for the Unreal engine

```
--- Exception:
page.click: Timeout 1080000ms exceeded.
=========================== logs ===========================
waiting for locator('text=Sign in with Epic Games')
============================================================
    at /fgc/unrealengine.js:62:18 {
  name: 'TimeoutError'
}
```

**Comment by vogler** [comment]
Yea, probably. Maybe https://github.com/vogler/free-games-claimer/commit/d73a523fe7f76608af5db4e72b567f058814fea1 and https://github.com/vogler/free-games-claimer/commit/a374d483451f1fa19c0f9f461e32cb37a4b46fd7 are enough.
