### ISSUE TITLE
Notifications only.

### ISSUE THREAD

**Issue by p6002** [vogler/free-games-claimer#259]
Could you add an option for notifications only? 
It's several times faster for me to manually add a game to my account in my browser than for the software to do it. 
Currently I get a notification on gotify that I should go into VNC, log in and the session has already expired, log into docker, restart the container, get the capcha notification again, go in through VNC, fill in the capcha and add the game. After all, it makes no sense. 
Maybe it would be better to get only a notification with the game title, and a link to epic to add manually? It will be several times faster.

**Comment by vttc08** [comment]
I agree, with on mobile and away from server, there is also turning on VPN and navigating captcha on mobile VNC app. It's also a cat and mouse game between Epic and this project on browser detection and as of now in docker installs, the captcha doesn't work. Where with a saved session on mobile/desktop browser, the process is instant with no captcha.

There is a simple step to get notification only. Just edit one line in [epic-games.js](https://github.com/vogler/free-games-claimer/blob/5919d37efaabad98c303e087c4874cffb58b3cb9/epic-games.js#L231), change the `'catpcha challenge ...'` part with `url` without quotations, this will send a notification with the epic game store url and you can add the game manually. The js file is location in the `/fgc` folder of the container. However, the change will not persist in new container update unless the developer add the change to the new image.

![image](https://github.com/vogler/free-games-claimer/assets/24880171/2b73f814-ee4e-4975-b617-fa40b8a20cf0)

**Comment by vogler** [comment]
@p6002 Yea, doesn't make sense to use it like that if you get captchas.

@vttc08 Good idea, I'll add the link.

**Comment by vogler** [comment]
Let me know if there are problems or if you propose some different message.

**Comment by NeoMod** [comment]
Just to leave a note for completeness: as per https://github.com/vogler/free-games-claimer/issues/402#issuecomment-2510818082 the included format for the "game url link" is not working. 

The `Game link ${url}` code works perfectly with Apprise (tested with NTFY) as per vttc08 suggestion.

I did take the liberty to forward a merge request integrating this fix; I left this comment here just in case someone else lands on this topic searching the issue.
