### ISSUE TITLE
[Question] embedded hCAPTCHA Solver

### ISSUE THREAD

**Issue by QIN2DIM** [vogler/free-games-claimer#26]
Maybe I can provide an embedded hCAPTCHA Solver?

**Comment by QIN2DIM** [comment]
Or I can compile the binary, read the file locally and perform the binary task.

**Comment by vogler** [comment]
Ideally it shouldn't show you a captcha. I noticed they show it more often now if you run it a couple of times in a row, but getting a new IP helps in those cases.

Which solver is it? There are several online services, but usually require spending some money or solving captchas to get points. The ones I tried also weren't that good at hcaptcha.

There's also https://www.npmjs.com/package/hcaptcha-solver, but it just randomly selects tiles. Idk how long it needs to solve it, 2^9 are 512 options, so I guess it could take 5-10min or more.

**Comment by QIN2DIM** [comment]
> 5-10min or more.

It depends on how you define solver.

If you only need me to do image classification tasks, the model can process hundreds of images a second and supports multi-core parallelism. If you need it to work on the lifecycle of hcaptcha from pop-up to disappear, this process can take 8 ~ 30s.

**Comment by vogler** [comment]
I was talking about this npm package - they just try random combinations.

I'm open for PRs if you come up with something that works well. What would you use that needs compiling? Binary blob with checksum for convenience would be ok, but the source needs to be available somewhere as well.

**Comment by vogler** [comment]
I'm not that into machine learning, so I don't know how hard it would be to classify and match it to the text. The last captcha I had for example was 'toy frog` vs. 'frog in grass' vs. 'frog under water' - so pretty subtle.

**Comment by QIN2DIM** [comment]
I don't think compiling binaries is the best option. But I am relatively new to TypeScript, otherwise it is most elegant to use the native language API to implement it. 

It's also possible to use containers to distribute this service, but I'm having a hard time decoupling it at the moment.

**Comment by vogler** [comment]
Regarding decoupling: Playwright can make a screenshot of the captcha and save it to a file in a shared volume or send it via some socket connection.

Which framework (TensorFlow etc.) do you want to use?

**Comment by QIN2DIM** [comment]
As a matter of fact, I've already taken care of all the work. For the current project, there are only three things need to do:
1. Get Challenge Images [9] and Challenge Prompt [en]
2. POST request localhost API, Get results of List[bool] 
3. IF true，click

**Comment by vogler** [comment]
You can open a pull request, then I'll try to implement the things above.

**Comment by vogler** [comment]
I just added some more options in https://github.com/vogler/free-games-claimer/issues/2#issuecomment-1027858090.

**Comment by vogler** [comment]
I added the https://www.nopecha.com extension in d67fb59355b710d9c5f4812ce893efb86526fb9f.
Just got hcaptcha challenges for the two new games and it solved them in a couple of tries, probably <10s.
The extension gives you 20 credits each day which should be enough even if there are multiple games to claim each day.

Let me know how it works for you. I like that it's relatively simple.

**Comment by vogler** [comment]
Closing this since there are usually no captchas anymore with non-headless Firefox.
If there are problems with captchas, nopecha can be loaded again as a low-effort solution.
