### ISSUE TITLE
Unexpected token '||='

### ISSUE THREAD

**Issue by jtrull101** [vogler/free-games-claimer#264]
Whether using the docker container or locally , I have been seeing this problem:

file:///{PATH}/free-games-claimer/gog.js:
89
  db.data[user] ||= {};
                ^^^

SyntaxError: Unexpected token '||='
←[90m    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)←[39m
←[90m    at async link (internal/modules/esm/module_job.js:63:21)←[39m

Same behavior for prime, gog, and epic

**Comment by jtrull101** [comment]
Last successful fetch was "2023-11-03 06:30:29.881" according to the epic-games.json log

**Comment by vogler** [comment]
Can't reproduce. Looks like you use some very old version of node. ||= was added in v15:
https://stackoverflow.com/questions/69515305/logical-or-assignment-not-working-on-nodejs

The docker image has a newer version, so idk how that should be possible.

**Comment by vogler** [comment]
Are you still on bullseye or which OS are you using?
https://packages.debian.org/search?keywords=nodejs

See https://nodejs.org/en/download/ for how to install a newer version.

**Comment by jtrull101** [comment]
Running on Win 11. Node version reported by gitbash is v14.17.3
The date of the last fetch coincides with some angular work I was doing on my local environment with that node version. Thank you for looking into this

**Comment by vogler** [comment]
But maybe a good idea to check the node version in the script if that's possible without tripping up the lexer already for old versions.

**Comment by vogler** [comment]
Yea, as expected, doesn't work:
![image](https://github.com/vogler/free-games-claimer/assets/493741/f92ad4de-2dd5-4e75-8d84-969126d2be0e)
![image](https://github.com/vogler/free-games-claimer/assets/493741/66843cbe-5f64-411d-a436-a227fb74e848)
https://tio.run/#javascript-node

**Comment by vogler** [comment]
Put the constraint in `package.json` such that it could be checked for #219 or `npx`.
