### ISSUE TITLE
How to hide terminal on Windows?

### ISSUE THREAD

**Issue by Mrgaton** [vogler/free-games-claimer#268]
Tengo planeado ejecutar el script cada vez que ejecute el ordenador en mi pc  y no quiero que se me abra todo siempre asi que una opcion para que solo salga cuando no funcione seria ideal

**Comment by vogler** [comment]
¿Por qué escribes en español?

> I plan to run the script every time I run the computer on my PC and I don't want everything to always open so an option so that it only appears when it doesn't work would be ideal

I don't understand what you want. I assume you are on Windows and put a batch script in Autostart. Then the terminal will open and show the output. You can

- create a shortcut and in the properties say that it should open minimized
- not start it that way but use a Windows service or whatever.

**Comment by vogler** [comment]
Feel free to follow up, I'll close this.
