### ISSUE TITLE
how to get VNC or noVNC working on HomeAssistantOS?

### ISSUE THREAD

**Issue by GodzillaTV** [vogler/free-games-claimer#271]
I have Free Games Claimer as an add-on on my HomeassistantOS. Unfortunately, I can neither connect via VNC nor via noVNC. But that would be very useful to me, as I need to log in to Prime Gaming properly. At the moment, the browser only loads and terminates after about 3 minutes with the error: Rejected the connection. How can I get at least one of the two to work?

**Comment by vogler** [comment]
See #149. Weird, unresolved issue with HAOS.
Fast fix: run the scripts without Docker or on a different OS.
I'll close this. You can subscribe to #149.
