### ISSUE TITLE
no issue only help

### ISSUE THREAD

**Issue by halloworld007** [vogler/free-games-claimer#272]
sorry i am new in docker linux

howto can pull the file from docker and use the keys?

i start with
docker run --rm -it -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer
howrto can data?

many thx

**Comment by vogler** [comment]
For example:
```console
$ docker run --rm -it -v fgc:/fgc/data alpine
/ # cd /fgc/data
/fgc/data # ls
prime-gaming.json
/fgc/data # cat prime-gaming.json
```
If you have the Docker Desktop UI, you can also browse volumes and download files there.
Also see https://stackoverflow.com/questions/35406213/how-to-copy-data-from-docker-volume-to-host
