### ISSUE TITLE
v1.6 Docker Image

### ISSUE THREAD

**Issue by EthanC** [vogler/free-games-claimer#278]
Really glad to see the [latest release](https://github.com/vogler/free-games-claimer/tree/v1.6)!

I noticed there are Docker-specific changes, but a new image has not been uploaded. Creating an Issue just in case this isn't intended :)

**Comment by EthanC** [comment]
Hm, closing this Issue as I see an image with the `main` tag was uploaded. `latest` is not yet updated.

**Comment by vogler** [comment]
I'll try to tag this as `latest` instead. However, the docker tags (and also releases) don't really mean much. If you run the command from the readme it will just always pull the latest build, i.e., latest commit.
See the discussion https://github.com/vogler/free-games-claimer/issues/261#issuecomment-1870413198.

**Comment by tjorim** [comment]
But updaters won't know if it changed. E.g. in Unraid it also won't show (by default `latest`).
