### ISSUE TITLE
apprise windows error

### ISSUE THREAD

**Issue by viperdriver2000** [vogler/free-games-claimer#285]
I am currently using the script on Windows. I have created a small batch script for this purpose.

It is working fine so far. Occasionally, there is a capture prompt from Epic, but that's okay.

I have configured it to receive a notification via apprise, but it is not working.

> Current free game: Marvel's Guardians of the Galaxy
>   Not in library yet! Click GET.
>   Claimed successfully!
> error: Command failed: apprise 'ntfy://[USERNAME]:[PASSWORD]@192.168.84.56:8150/free-games-claimer' -i html -b epic-games ([USERNAME]):<br>- <a href="https://store.epicgames.com/en-US/p/marvels-guardians-of-the-galaxy">Marvel&#039;s Guardians of the Galaxy</a> (claimed)
> 
> node:internal/errors:956
>   const err = new Error(message);
>               ^
> 
> Error: Command failed: apprise 'ntfy://[USERNAME]:[PASSWORD]@192.168.84.56:8150/free-games-claimer' -i html -b epic-games ([USERNAME]):<br>- <a href="https://store.epicgames.com/en-US/p/marvels-guardians-of-the-galaxy">Marvel&#039;s Guardians of the Galaxy</a> (claimed)
> 
>     at genericNodeError (node:internal/errors:956:15)
>     at wrappedFn (node:internal/errors:510:14)
>     at ChildProcess.exithandler (node:child_process:422:12)
>     at ChildProcess.emit (node:events:519:28)
>     at maybeClose (node:internal/child_process:1105:16)
>     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
>   code: 1,
>   killed: false,
>   signal: null,
>   cmd: `apprise 'ntfy://[USERNAME]:[PASSWORD]@192.168.84.56:8150/free-games-claimer' -i html -b epic-games ([USERNAME]):<br>- <a href="https://store.epicgames.com/en-US/p/marvels-guardians-of-the-galaxy">Marvel&#039;s Guardians of the Galaxy</a> (claimed)`
> }
> 
> Node.js v21.5.0

When I manually execute the command, I also receive an error.
> The system cannot find the specified file.

If I change the command to this, it works. 
> apprise ntfy://[USERNAME]:[PASSWORD]@192.168.84.56:8150/free-games-claimer -i html -b "epic-games ([USERNAME]):<br>- <a href="https://store.epicgames.com/en-US/p/marvels-guardians-of-the-galaxy">Marvel&#039;s Guardians of the Galaxy</a> (claimed)"

However, I can't find the part in the code where I need to make adjustments. Can someone help me with this?
thanks

**Comment by niscolas** [comment]
Encountered the same error, although it just worked again afterwards, I didn't make any changes. Not sure what may be the cause, but seems to be either an edge-case situation or not 100% repro rate
