### ISSUE TITLE
check if there are new games to claim before launching browser?

### ISSUE THREAD

**Issue by QIN2DIM** [vogler/free-games-claimer#29]
## Feature

Why not determine if the promotion entity is already in the library before the claim-task is executed?

I think handling this pre-work before launching the browser would greatly improve workflow efficiency (If the identity token is cached).

## Description

Key: the namespace of a promotion is a unique value.

- [get_order_history (with cookies)](https://www.epicgames.com/account/v2/payment/ajaxGetOrderHistory?locale=en-US)
- [get_promotions](https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=en-US)

Pseudo code
```python
def promotions_filter(self):
    # Get historical order data (10 items)
    order_history = self.explorer.game_manager.get_order_history(self._ctx_cookies)
    # Get weekly free game promotion data
    promotions = self.get_promotions()
    # Marks the in-library status of the promotion
    for promotion in promotions:
        # Check order.orderStatus == "COMPLETED" and promotion.namespace == order.namespace
        promotion.in_library = order_history.get(promotion.namespace, False)
        # Skip tasks that correspond to promotions already in the library
        self.task_queue_pending.put(promotion)
```

**Comment by vogler** [comment]
I like the idea, but not sure yet if it's worth it.

Cons:
- extra code that can break and needs to be maintained

Pros:
- if there's no new game to claim:
  - finish faster
  - don't need to launch the browser which may be relevant for people who don't run it in docker

**Comment by vogler** [comment]
Mh, the [get_promotions](https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=en-US) json you posted only contains one of the games from the order history (Hundred Days - Winemaking Simulator):

```console
$ cat orderHistory.json | jq '.orders[].items[] | {description, namespace}'
{
  "description": "Gloomhaven",
  "namespace": "bc079f73f020432fac896d30c8e2c330"
}
{
  "description": "The Captain",
  "namespace": "301980d060324bb29202677f468c6c44"
}
{
  "description": "Spirit of the North",
  "namespace": "6098a8c7375c43458a22163a637c0c2f"
}
{
  "description": "Realm Royale Reforged Epic Launch Bundle",
  "namespace": "5fcf6f3031c547f789e29c18b422ca67"
}
{
  "description": "Realm Royale Reforged",
  "namespace": "5fcf6f3031c547f789e29c18b422ca67"
}
{
  "description": "Hundred Days - Winemaking Simulator",
  "namespace": "4d8b727a49144090b103f6b6ba471e71"
}
{
  "description": "Submerged: Hidden Depths",
  "namespace": "6006c7c9d8534b0ca4605ea3a759f3e1"
}
{
  "description": "Knockout City™",
  "namespace": "5bb3d43818ae4188850fe1dbad9d57a5"
}
{
  "description": "Destiny 2: Bungie 30th Anniversary Pack",
  "namespace": "428115def4ca4deea9d69c99c5a5a99e"
}
{
  "description": "Rumbleverse™ - Boom Boxer Content Pack",
  "namespace": "0bef9383794a4d779ba0628084b14cba"
}
```

**Comment by QIN2DIM** [comment]
> extra code that can break and needs to be maintained ... might have to re-login

Just do a front-end detection, run in pluggable form, can not let it affect the operation of the core business.

<p align="center">
<img  width="55%" src="https://user-images.githubusercontent.com/62018067/193205240-831d2267-c95c-43e1-b6a8-9fd454a7609f.svg">
</p>


GET https://www.epicgames.com/account/personal with cookies, IF resp.status == 200, return TRUE

**Comment by QIN2DIM** [comment]
> Mh, the [get_promotions](https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=en-US) json you posted only contains one of the games from the order history

I don't know what you mean 0.0

**Comment by QIN2DIM** [comment]
[get_promotions](https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=en-US) is updated every week. But usually it will include a limited time free game of the week. If the time has passed, it is usually removed from the form.

```python
def get_promotions(
    self, ctx_cookies: typing.List[dict]
) -> typing.List[typing.Dict[str, typing.Union[str, bool]]]:
    """
    Get weekly free game data

    <Upcoming games> promotion["promotions"]["upcomingPromotionalOffers"]
    <Weekly games> promotion["promotions"]["promotionalOffers"]
    :param ctx_cookies:
    :return:
    """
    detailed = []
    headers = {
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.36",
        "cookie": ToolBox.transfer_cookies(ctx_cookies),
    }
    scraper = cloudscraper.create_scraper()
    response = scraper.get(self.URL_PROMOTIONS, headers=headers)

    try:
        data = response.json()
    except JSONDecodeError:
        pass
    else:
        elements = data["data"]["Catalog"]["searchStore"]["elements"]
        promotions = [e for e in elements if e.get("promotions")]
        # Get mall promotion data
        for promotion in promotions:
            if promotion["promotions"]["promotionalOffers"]:
                image_url = ""
                try:
                    query = promotion["catalogNs"]["mappings"][0]["pageSlug"]
                    url = self.URL_PRODUCT_PAGE + query
                except IndexError:
                    url = self.URL_PRODUCT_PAGE + promotion["productSlug"]
                try:
                    image_url = promotion["keyImages"][-1]["url"]
                    Explorer.cdn_image_urls.append(image_url)
                except (KeyError, IndexError, AttributeError):
                    pass
                # Implement Promotion Interface
                detailed.append(
                    {
                        "url": url,
                        "title": promotion["title"],
                        "image_url": image_url,
                        "in_library": None,
                        "namespace": promotion["namespace"],
                    }
                )

    return detailed
```

**Comment by vogler** [comment]
You can open a PR. It's not trivial to make it useful without adding lots of extra code.

1. How do we refresh cookies if we don't open the browser?
2. How do we get the cookies without opening the browser?
    1. https://playwright.dev/docs/api/class-browsercontext#browser-context-cookies - could save them into some file after every run that opened the browser.
    2. https://playwright.dev/docs/api/class-browsercontext#browser-context-request - contains the cookies in the request, but needs a browser context, so we would first launch a headless browser to make the request and if there's something new we would need to re-launch non-headless to claim. Not great performance-wise.

What could be easily implemented is to check against the saved games in `data/epic-games.json`, but then you have problems if you start using multiple accounts. Could make the root keys the accounts though.

**Comment by vogler** [comment]
Closing this since the potential speedup is not worth the extra code and possible points of failure.
