### ISSUE TITLE
Prime gaming error

### ISSUE THREAD

**Issue by Mrgaton** [vogler/free-games-claimer#295]
Number of already claimed games (total): 3
Number of free unclaimed games (Prime Gaming): 2
Current free game: Behind the Frame: The Finest Scenery VR
Current free game: APICO
Number of free unclaimed games (external stores): 3
Current free game: Atari Mania
  External store: epic games store
Current free game: Yars: Recharged
  External store: epic games store
Current free game: Lost Lands: Sand Captivity - Collector's Edition
  External store: legacy games
--- Exception:
[AggregateError: All promises were rejected] {
  [errors]: [
    page.inputValue: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('input[type="text"]')

        at C:\Users\Mrgaton\AppData\Local\Temp\free-game-clamer\prime-gaming.js:186:46 {
      name: 'TimeoutError'
    },
    page.textContent: Timeout 60000ms exceeded.
    Call log:
      - waiting for locator('[data-a-target="ClaimStateClaimCodeContent"]')

        at C:\Users\Mrgaton\AppData\Local\Temp\free-game-clamer\prime-gaming.js:186:85 {
      name: 'TimeoutError'
    }
  ]
}

**Comment by vogler** [comment]
Works fine for me. Do you still have this issue?

**Comment by Mrgaton** [comment]
No, this was very old
