### ISSUE TITLE
probleme instalation

### ISSUE THREAD

**Issue by nicm91** [vogler/free-games-claimer#304]
Hello 
The installation via home assistant has crashed since I can neither start the module nor uninstall it each time I get an error message => "Failed to uninstall extension Another job is running for job group container_addon_db21ed7f_free_games_claimer".

**Comment by arturzamik** [comment]
hello

**Comment by vogler** [comment]
You'll have to ask the homeassistant people.
If you don't have login info configured, the terminal will wait for you to enter it, however, it has a timeout, so the container should stop running in any case.
