### ISSUE TITLE
How to run "SHOW=1 node epic-games" on a Windows CMD

### ISSUE THREAD

**Issue by t3hsuppli3r** [vogler/free-games-claimer#314]
It seems those "SHOW=1 node epic-games" and "EMAIL=foo@bar.baz SHOW=1 node epic-games" works only on Linux/macOS OOTB.

Is there a workaround that will let me login with the browser under Windows CMD ?

![image](https://github.com/vogler/free-games-claimer/assets/161611271/06046183-206b-435c-ac1e-9951333908d1)

**Comment by jaxparrow07** [comment]
CMD has a different syntax for environment variables.

The `SHOW=1` goes like this ( have to run one by one )
```cmd
set SHOW=1
set EMAIL=""
<node js command here>
```
 If you want to execute them on a single line/execution. You'll have to append `call` before the calling function so the variables take effect.

 ```cmd
 set SHOW=1 && set EMAIL="" && call <node js command here>
 ```

**Comment by EnduringGuerila** [comment]
> ```batchfile
> set SHOW=1
> set EMAIL=""
> <node js command here>
> ```

This worked just fine as 3 separate commands.


> ```batchfile
> set SHOW=1 && set EMAIL="" && call <node js command here>
> ```

I couldn't get the single line to work in CMD or powershell

**Comment by jaxparrow07** [comment]
> > ```batchfile
> > set SHOW=1
> > set EMAIL=""
> > <node js command here>
> > ```
> 
> This worked just fine as 3 separate commands.
> 
> 
> > ```batchfile
> > set SHOW=1 && set EMAIL="" && call <node js command here>
> > ```
> 
> I couldn't get the single line to work in CMD or powershell
> 
> also, the email should not be in quotes as the quotes get pasted into the email field

What's the output when you try the single-line command? And what windows version are you on. 

I appreciate you for pointing out the quotes.

**Comment by nahuelranieri** [comment]
I'm commenting here so I don't open another request, but maybe it could help the rest:

`set` is a CMD-only command, so if you try to emulate it in Powershell (as I did) it won't work. I think it's important to point this out because Powershell doesn't return any error if you use set.

Anyway you can always create a `config.env` file inside the data folder and set your variables there.

**Comment by vogler** [comment]
I linked this article in the Readme that explains how to set them for every OS/Terminal:
https://github.com/vogler/free-games-claimer/blob/c8cf7362fa2ff92386eee4dc847784d95d7f5195/README.md?plain=1#L64
Specifically https://kinsta.com/knowledgebase/what-is-an-environment-variable/#how-to-work-with-environment-variables.
Maybe I should make that more prominent or add a FAQ section.

**Comment by lightningHoneypot** [comment]
> > ```batchfile
> > set SHOW=1
> > set EMAIL=""
> > <node js command here>
> > ```
> 
> This worked just fine as 3 separate commands.
> 
> > ```batchfile
> > set SHOW=1 && set EMAIL="" && call <node js command here>
> > ```
> 
> I couldn't get the single line to work in CMD or powershell
> 
> also, the email should not be in quotes as the quotes get pasted into the email field

It's odd really, I think I can do it in Powershell, it displays the browser, on CMD it does not show it.



> I linked this article in the Readme that explains how to set them for every OS/Terminal:
> 
> https://github.com/vogler/free-games-claimer/blob/c8cf7362fa2ff92386eee4dc847784d95d7f5195/README.md?plain=1#L64
> 
> 
> Specifically https://kinsta.com/knowledgebase/what-is-an-environment-variable/#how-to-work-with-environment-variables.
> Maybe I should make that more prominent or add a FAQ section.

For Powershell

```powershell
# Setting the environment variable SHOW to "1" 
$env:SHOW="1"
# Setting the environment variable EMAIL to an empty string 
$env:EMAIL=""
# Call the Node.js command, example: node gog
node gog
```
if you want only single line
```powershell
$env:SHOW = "1"; $env:EMAIL=""; node gog
```

Also note that if you had already signed in with your accounts, you can safely not enter the `EMAIL` variable.
