### ISSUE TITLE
Headless non docker - How do I login?

### ISSUE THREAD

**Issue by XmemphistoX** [vogler/free-games-claimer#322]
I'm running this headless in Debian without Docker.  I am not sure how to enter or see captcha when it asks.  The docker method mentions going to a webpage thats hosted on the Docker image.  However that isn't setup with a headless normal install.

After running SHOW=1 node epic-games I am getting the following "Looks like you launched a headed browser without having a XServer running"

Im not sure how to get around this.  Is it safe to say that headless mode is not viable without Docker?

**Comment by vogler** [comment]
> Is it safe to say that headless mode is not viable without Docker?

If you have to solve a captcha, yes.
Login is also possible via env vars or the terminal.
