### ISSUE TITLE
GOG - current giveaway not being recognised by the script

### ISSUE THREAD

**Issue by DragRedSim** [vogler/free-games-claimer#326]
The current layout of the main page is not compatible with the script as-is; the script is unable to find an HTML element matching `.giveaway-banner__title`, as the page does not contain such an element.

At the time of posting, the giveaway for Warhammer 40,000: Gladius - Relics of War has slightly over six days to run.

**Comment by Xrdem** [comment]
Same..Also epic games not login..
![Capture](https://github.com/vogler/free-games-claimer/assets/116120205/44126dc9-cee9-405c-8896-89835c3db421)

**Comment by floxigen** [comment]
epic-games failed: locator.getAttribute: Timeout 60000ms exceeded.

**Comment by floxigen** [comment]
Epic works but I still have error for gog

**Comment by ccsimplyspolit** [comment]
gog failed: locator.innerText: Timeout 60000ms exceeded.
