### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by yohudood** [vogler/free-games-claimer#33]
when i run the prime script i get this error wat do i have to do to get it working?

C:\Users\%username%\free-games-claimer-main> node prime-gaming
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/107.0.5304.18 Safari/537.36
Signed in.
Number of already claimed games (total): 7
Number of free unclaimed games (Prime Gaming): 0
Number of free unclaimed games (external stores): 0
file:///C:/Users/%username%/free-games-claimer-main/prime-gaming.js:145
  db.data.runs.push(run);
               ^

TypeError: Cannot read properties of undefined (reading 'push')
    at file:///C:/Users/%username%/free-games-claimer-main/prime-gaming.js:145:16

Node.js v19.0.1

**Comment by vogler** [comment]
Thanks, should be fixed. Delete `data/prime-gaming.json` and try again.

This addition
https://github.com/vogler/free-games-claimer/blob/0df7bf35ba9bf1260b7ddab06f2d75e35d42a186/util.js#L19
led to

https://github.com/vogler/free-games-claimer/blob/0df7bf35ba9bf1260b7ddab06f2d75e35d42a186/prime-gaming.js#L14
not setting `db.data.runs` for an empty `data/prime-gaming.json`.

**Comment by yohudood** [comment]
there is no prime-gaming.json in the data folder

**Comment by yohudood** [comment]
> Right, the exception happened before `db.write()`. Then just run again :)

it still wont create the prime-gaming.json

**Comment by vogler** [comment]
Do you have some details? Does it throw an exception? Are you running the new code?

**Comment by yohudood** [comment]
it is working now forgot the new util.js file
