### ISSUE TITLE
epic-games login shows blank page

### ISSUE THREAD

**Issue by Bukkake-crypto** [vogler/free-games-claimer#338]
Node epic-games now give me a blank page.

Before it would allow me to type only the email and the script would just stop after that any way to fix it?

**Comment by vogler** [comment]
Seems like this is due to 'Tracking Protection' now enabled by default after the last Playwright/Firefox update c0eb6dbb0bb6c64e268ae70b9e37586c92a59366.
![image](https://github.com/vogler/free-games-claimer/assets/493741/9c6800c9-a42d-415c-8488-68b7492e20c7)

**Comment by vogler** [comment]
Ok, no, with a new $BROWSER_DIR everything works fine even with 'Enhanced Tracking Protection' on.

**Comment by voruti** [comment]
works
