### ISSUE TITLE
Unable to go past "Verify you are a human" check

### ISSUE THREAD

**Issue by Kraker01** [vogler/free-games-claimer#34]
Hi everyone, 
i'm trying to get this script working using Docker (the latest versiona available, downloaded today) and followring your instructions (i'm not a programming expert). 
I've managed to login using http://localhost:6080 and using my Facebook credentials. The script is getting stuck in the next part, where Epic Games store is asking "One more step". I'm clicking on "I'm a human" (or something similar) but the script simply stops there. 

Is there any workaround? Am i missing something?

**Comment by Vordlex** [comment]
Same here, but I can't login with google or with an normal account (error on hcaptcha that always throws a error, even when I'm resolving the catpcha), I tried to replace "browser" folder with my original browser folder that is logged in, but it didn't worked as well, I'm just unlogged.

**Comment by vogler** [comment]
I also had problems with the captcha recently. Not sure if it's a change on their side or because I updated Chromium.
Can you check what version you're using? For example by uncommenting https://github.com/vogler/free-games-claimer/blob/e1cd3117b6db9e745137992c85e73f78ad75d7ae/epic-games.js#L60
or checking https://playwright.dev/docs/browsers#managing-browser-binaries

I then switched to firefox which didn't show any captchas. However, it has problems waiting for the iframe. It works with `waitForTimeout`, but that's not a good solution. I can open a PR if you want to fiddle with it yourself.
Maybe it makes sense to switch, I think there were some benefits using Firefox for the Docker image as well.

**Comment by Kraker01** [comment]
> I also had problems with the captcha recently. Not sure if it's a change on their side or because I updated Chromium. Can you check what version you're using? For example by uncommenting
> 
> https://github.com/vogler/free-games-claimer/blob/e1cd3117b6db9e745137992c85e73f78ad75d7ae/epic-games.js#L60
> 
> or checking https://playwright.dev/docs/browsers#managing-browser-binaries
> 
> I then switched to firefox which didn't show any captchas. However, it has problems waiting for the iframe. It works with `waitForTimeout`, but that's not a good solution. I can open a PR if you want to fiddle with it yourself. Maybe it makes sense to switch, I think there were some benefits using Firefox for the Docker image as well.

i don't know how or why, but uncommenting that line and loggin trhough Facebook fixed everything, now it's working but i'm going to open a new issue

**Comment by h4llm3n** [comment]
Having the same issue here on a VPS hosted at Oracle.

![image](https://user-images.githubusercontent.com/22115081/204857917-cf70a58e-19fa-4b83-923b-d133f344e8e1.png)

That seems a bit strange. :)

**Comment by viperdriver2000** [comment]
i have the same problem

**Comment by viperdriver2000** [comment]
someone found a solution?

**Comment by vogler** [comment]
Sorry, busy with work. It's working fine in firefox, I'll commit my changes later.

**Comment by h4llm3n** [comment]
> Sorry, busy with work. It's working fine in firefox, I'll commit my changes later.

But there is only Chrome in it, I guess?

**Comment by vogler** [comment]
Currently, yes, but Playwright supports Chromium, WebKit, and Firefox, so it's not a big change, just need to check what's up with prime gaming.

**Comment by vogler** [comment]
I changed it to firefox for epic-games now.
I didn't have to delete `data/browser`, but probably better to do it to remove the chromium data.
Haven't tested the docker container yet.
Let me know if you run into problems.
