### ISSUE TITLE
Disable proxy when starting Firefox

### ISSUE THREAD

**Issue by BlueHtml** [vogler/free-games-claimer#346]
Hello, I am in China and must directly access Epic to log-in and claim the game, otherwise an error message will appear. 

Can we add an environment variable to make Firefox not use proxies?

**Comment by vogler** [comment]
I don't understand what you mean. The used firefox doesn't do anything with proxies.
Which setting do you want to change?
Since the browser profile is reused, you can also just change settings as needed.

**Comment by BlueHtml** [comment]
* I made a `user.js` file to tweak Firefox settings. I added a line of code to it, `user_pref("network.proxy.type", 0);`, which tells Firefox to stop using a proxy server.
