### ISSUE TITLE
How to run container everyday?

### ISSUE THREAD

**Issue by ceszkraft** [vogler/free-games-claimer#347]
Hey guys I'm pretty new here and I ran the container and it works perfectly but it closes automatically when it hit the end (GOG).
Should I run it everytime to take the games? **How could I automatically run the container everyday for example?** Any ideas?

Thanks!

**Comment by wielorzeczownik** [comment]
Hey, it all depends on what operating system you are using. If you are using Linux, you can add the following snippet to cron, of course supplementing it with the necessary environment variables:
```
0 11 * * * docker run --rm -it -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer
```
This provision will result in the container starting at 11am every day.
