### ISSUE TITLE
elementHandle.screenshot: Element is not attached to the DOM

### ISSUE THREAD

**Issue by PawiX25** [vogler/free-games-claimer#355]
#### Description

When executing `node prime-gaming.js`, the following error occurs:

```
C:\Users\Paweł\free-games-claimer>node prime-gaming.js
2024-08-01 22:19:10.171 started checking prime-gaming
Signed in as PawiX
Number of already claimed games (total): 0
Number of free unclaimed games (Prime Gaming): 22
Current free game: Blast Brigade vs. the Evil Legion of Dr. Cread
--- Exception:
elementHandle.screenshot: Element is not attached to the DOM
Call log:
  - taking element screenshot
  - waiting for fonts to load...
  - fonts loaded
  - attempting scroll into view action
  - waiting for element to be stable

    at C:\Users\Paweł\free-games-claimer\prime-gaming.js:159:16 {
  name: 'Error'
}
```

#### Additional Information

- **Environment**: 
  - OS: Windows 11
  - Node.js version: v20.16.0
  - Script version: I pulled the latest changes from the repository before running the script.
---

Please let me know if any additional details are needed or if there's any other way I can assist.

**Comment by vogler** [comment]
Thanks, can reproduce. Have to check what changed. All external games are now also listed as internal.

**Comment by vogler** [comment]
I updated the locators which also resolved the screenshot issue for me.
Still need to come up with a proper solution for scrolling to load all games. I increased the `waitUntilStable` timeout from 2s to 5s but it still sometimes didn't load all the games for me.
