### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by KocPernik1337** [vogler/free-games-claimer#374]
--- Exception:
locator.innerText: Target page, context or browser has been closed
Call log:
  - waiting for locator('aside button').first()

    at C:\XXX\free-games-claimer-main\epic-games.js:160:40

**Comment by vogler** [comment]
Bundles didn't have `button[data-testid="purchase-cta-button"]`, that's why the locator was changed to `aside button`.
Seems like they now changed the page for bundles again.

**Comment by KocPernik1337** [comment]
how to fix that?

**Comment by vogler** [comment]
Should be fixed already. See the commit that closed this issue.
