### ISSUE TITLE
Bundles are not recognized as being in the library

### ISSUE THREAD

**Issue by ZelloxTV** [vogler/free-games-claimer#375]
Hello, it doesn't recognize that the bundle is in the library. Can someone help me with epic games?
![Screenshot_6](https://github.com/user-attachments/assets/643d5e72-dab8-4fea-9fe4-93fe7efdc165)
![Screenshot_7](https://github.com/user-attachments/assets/c2c00194-6322-4ab9-9052-77a5a6d9f740)

**Comment by vogler** [comment]
https://github.com/vogler/free-games-claimer/commit/fef5b97e3b70d3387233e612d8ed6709437d9cd4#diff-d449836a1265b178db184b204653735df165e83a1b95401942c324ace2b501adR160
Mh, on Thursday that was enough for me, but now had the same issue.

Waiting for some text (with e or i) now - not a nice solution, but fine for now.

**Comment by getsouvikdas** [comment]
![7d](https://github.com/user-attachments/assets/24b36398-69fd-4ecd-a3f7-6ea0002c1ebf)
any solutions ?

**Comment by getsouvikdas** [comment]
any solution? 
![7d](https://github.com/user-attachments/assets/b6e59d02-a914-4040-8921-785feb700894)

**Comment by vogler** [comment]
@getsouvikdas Strange. How do your page and DOM look like?
![image](https://github.com/user-attachments/assets/17f1eb16-0abd-4462-a45c-1f08421e8ad4)
![image](https://github.com/user-attachments/assets/a5e1f849-ca39-46d6-acc2-09e4d2d3f613)
![image](https://github.com/user-attachments/assets/2c63c0a8-f454-4c05-8b06-64d048563ed9)

The only thing that comes to mind is if you reduce `WIDTH` so much that the text is no longer left of the button:
![image](https://github.com/user-attachments/assets/4a365b4e-27ed-4f1a-86c7-cf7fa8c0d4b1)

**Comment by getsouvikdas** [comment]
you are correct, i had reduced width. I have Increased it and its working.
