### ISSUE TITLE
[RFC] headless firefox works for epic-games

### ISSUE THREAD

**Issue by vogler** [vogler/free-games-claimer#39]
Just tried headless mode in firefox and had no captcha problem for epic-games:

![image](https://user-images.githubusercontent.com/493741/208704901-b7c02ef9-11a7-430b-84d5-2d18298249d1.png)

Should have tried Firefox instead of Chrome earlier...
Maybe some people can confirm that it works reliably, then we can change the default to be headless and only show the browser for login. Maybe it makes sense to have a smaller docker image without the xvfb stuff if we know that login including 2FA can be handled reliably via the terminal.

Related: #2, #9, #11

**Comment by vogler** [comment]
Data point: Just had a captcha during login for headless and then no captcha with `SHOW=1`.

**Comment by Arketsu** [comment]
after the last update I have 0!!!!!! issues with epic. I can't believe this is the only functional claimer in GitHub. Changing to firefox was a great idea. only issue I had was with amazon prime because of the 2 factor but I logged in with the (show)version and had 0 problems after that.

**Comment by vogler** [comment]
> only issue I had was with amazon prime because of the 2 factor but I logged in with the (show)version and had 0 problems after that.

You can open an issue if it's reproducible.

**Comment by vogler** [comment]
I'll close this. Have been claiming headless for months now without any captchas.
