### ISSUE TITLE
cp: -r not specified; omitting directory '/config/addons_config/free_games_claimer/config.env'

### ISSUE THREAD

**Issue by codeclinic** [vogler/free-games-claimer#404]
Even though I have added my credentials in the yaml file, I get this log output everytime, just looping.....

Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Free Games Claimer (NoVNC not working)
 automatically claims free games on the Epic Games Store, Amazon Prime Gaming and GOG
-----------------------------------------------------------
 Add-on version: 1.6
 You are running the latest version of this add-on.
 System: Home Assistant OS 14.0  (aarch64 / raspberrypi5-64)
 Home Assistant Core: 2024.12.0
 Home Assistant Supervisor: 2024.11.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
/etc/cont-init.d/00-global_var.sh: executing
CMD_ARGUMENTS='node epic-games ; node prime-gaming ; node gog'
CONFIG_LOCATION='/config/addons_config/free_games_claimer/config.env'
Timezone set from Etc/UTC to Europe/Berlin
/etc/cont-init.d/01-config_yaml.sh: executing
Setting permissions for the config.yaml directory
Load environment variables from /config/addons_config/free_games_claimer/config.env/config.yaml if existing
If accessing the file with filebrowser it should be mapped to /homeassistant/addons_config/free-games-claimer/config.yaml
---------------------------------------------------------
Wiki here on how to use : github.com/alexbelgium/hassio-addons/wiki/Add‐ons-feature-:-add-env-variables
EG_EMAIL='xxxxxxxxxxxxxxxxxx'
EG_PASSWORD='xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
/etc/cont-init.d/01-custom_script.sh: executing
Execute /config/addons_autoscripts/free-games-claimer.sh if existing
---------------------------------------------------------
If accessing the file with filebrowser it should be mapped to /config/addons_autoscripts/free-games-claimer.sh
Wiki here : github.com/alexbelgium/hassio-addons/wiki/Add-ons-feature-:-customisation
... no script found, exiting
/etc/cont-init.d/20-folders.sh: executing
Creating config location ...
Copying files if needed...
/etc/cont-init.d/99-run.sh: executing
[15:04:39] WARNING: A default config.env file was copied in /config/addons_config/free_games_claimer. Please customize according to https://github.com/vogler/free-games-claimer/tree/main#configuration--options and restart the add-on
cp: -r not specified; omitting directory '/config/addons_config/free_games_claimer/config.env'
Error : /etc/cont-init.d/99-run.sh exiting 1
Starting the upstream container

And that's all it does. The web interface isnt accessible either.

**Comment by vogler** [comment]
You should open an issue there.
The problem seems to be this:
https://github.com/alexbelgium/hassio-addons/blob/3e274378aef2be45a56b911818a9e190e5856cd3/free_games_claimer/rootfs/etc/cont-init.d/99-run.sh#L23
For you, it is a directory, but it should be a file.

**Comment by codeclinic** [comment]
> For you, it is a directory, but it should be a file.

Thanks.
Is there anyway I can make this a file myself? What is the location of the file I need to copy?
