### ISSUE TITLE
GOG TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by Kaschtelator** [vogler/free-games-claimer#414]
--- Exception:

TypeError: Cannot read properties of null (reading '1')

    at file:///fgc/gog.js:102:62

**Comment by sudoShiba** [comment]
i have the same error

**Comment by sudoShiba** [comment]
i see there is already a pull request on this though
https://github.com/vogler/free-games-claimer/pull/411

**Comment by vogler** [comment]
Duplicate of #398.
