### ISSUE TITLE
claim games only from epic whithout amazon prime?

### ISSUE THREAD

**Issue by D3FALT404** [vogler/free-games-claimer#42]
Is there any way to disable lunching prime-gaming? Btw amazing project.

**Comment by D3FALT404** [comment]
nvm I have edited docker image but it would be nice to have file where you can disable it

**Comment by vogler** [comment]
You don't need to change the image, but can just append `node epic-games` to the `docker run` command.
Mentioned it in the readme.

https://github.com/vogler/free-games-claimer/blob/21a2bc01a4712276c8ac1861ef493d05a127eb3f/Dockerfile#L62
This is the default command the container will run, but you could give it anything, for example `bash` to get a shell into the container.
