### ISSUE TITLE
Can not login due to hcaptcha

### ISSUE THREAD

**Issue by Lexxior** [vogler/free-games-claimer#45]
I try to enter my credentials via browser and I get a hcaptcha trigger
But before I can login, it just reloads the hcaptcha, marking it as failed - saying "Incorrect response. Please refresh the page."
Making it impossible to login

**Comment by vogler** [comment]
I assume you mean epic-games.
That happened to me before as well after too many login attempts. Getting a new IP helped.
Are you running the latest version?

**Comment by Lexxior** [comment]
I tried with a VPN, same outcome
Yes, in docker with the latest version

**Comment by Lexxior** [comment]
There is no other way to achieve this as I have a static IP on my network

**Comment by vogler** [comment]
I think their timeout is several hours. You can try logging in with your usual browser to see if it is really an issue with your IP. Maybe a successful login there will reset it. It's unclear to me what the heuristics they use are exactly.

**Comment by vogler** [comment]
Then you were running an old image. You don't need to install or set anything in the container.
How do you run it? The command shown in the readme should pull the latest image and not leave any containers behind.
