### ISSUE TITLE
History/DevLog

### ISSUE THREAD

**Issue by EQUALIT-CG** [vogler/free-games-claimer#47]
Hello

I think the History/DevLog part first line needs to be fixed

when someone reads that looks as if doesn't work anymore etc etc as this may or may not get updated etc etc for times or not.
just think it could be worded better

"resolved" epicgames-freebies-claimer {https://github.com/Revadike/epicgames-freebies-claimer} hcaptcha take a look at https://github.com/Revadike/epicgames-freebies-claimer/issues/172 as to how we managed to resolved it etc etc

If you chose not to that fine

**Comment by vogler** [comment]
https://github.com/vogler/free-games-claimer/commit/78a14569c8e88edebbc6a1a64f8e84ef33a7b539
```patch
- does not work anymore
+ had problems
```
Is that better? It was just my notes when I started this repo. I think the other project still has problems with captchas, no?

**Comment by EQUALIT-CG** [comment]
Aye bro no your all good i just wasn't what other would read it as if you know what i mean but up to you


![Screenshot 2023-01-14 at 03-56-01 vogler_free-games-claimer Claims free games on the Epic Games Store Amazon Prime Gaming and GOG](https://user-images.githubusercontent.com/56815873/212375704-eaf9b3fb-e25e-4c4b-832b-4d0b67fc0749.png)
