### ISSUE TITLE
How does one update the docker container?

### ISSUE THREAD

**Issue by andre-paulo98** [vogler/free-games-claimer#51]
I installed it using the `docker run --rm -it -p 6080:6080 -v fgc:/fgc/data ghcr.io/vogler/free-games-claimer` method, and recently Epic Games changed the page layout (https://github.com/vogler/free-games-claimer/commit/cecc54082f08944b5fcefd2caffcb1ab04c4fb29).
I'm just seeing timeouts, with the error `waiting for locator('h1 div').first()`, which is probably because I'm running on the same version since I installed it.

How does one update the container to the latest version?

**Comment by vogler** [comment]
Currently can't test it, but you can try using `--pull=always`. I'll update the readme if that works.

See
- https://stackoverflow.com/questions/57587094/can-i-make-docker-do-a-pull-when-performing-a-run
- https://github.com/docker/cli/pull/1498
- https://docs.docker.com/engine/reference/commandline/run/

**Comment by andre-paulo98** [comment]
Can confirm that it works. For reference, the next time the command is executed, if there are no updates, the output will be:
```
latest: Pulling from vogler/free-games-claimer
Digest: sha256:170a0a185f010ae7ecf9b400cd22c5cb6959d1a11f96b3281eef2748e1316d2d
Status: Image is up to date for ghcr.io/vogler/free-games-claimer:latest
```
