### ISSUE TITLE
Epic games error timeout

### ISSUE THREAD

**Issue by scorthyn** [vogler/free-games-claimer#54]
hey, can someone help me why this happens? It says he logged me in and displays the free games then after this happens:

locator.innerText: Timeout 20000ms exceeded.
=========================== logs ===========================
waiting for locator('h1 div').first()

**Comment by vogler** [comment]
You need to run an up-to-date image. See #51.

**Comment by scorthyn** [comment]
Im sorry i dont understand, im running with node btw not docker, do I need to edit something in the epic-games.js or config.js ?

**Comment by vogler** [comment]
Ok, then you need to do a `git pull`. You can check with `git log` that you have the latest updates from two days ago.

(Wondering if the scripts should check and notify about updates...)

**Comment by scorthyn** [comment]
Ok i manually updated the files and its now working, can u just tell me what command do I need to do so the script updates before checking every store? i created a .bat file with node eic-games.js gog.js and amazon prime.js but im not sure if this is the optimized way to do it lol, sorry about this and also thank you!

**Comment by vogler** [comment]
If you have git installed on Windows, you can just add `git pull` at the beginning of the .bat file which will make it first get any changes to the code.

**Comment by scorthyn** [comment]
All working correctly and it checks for updates at the start :D thank you!
