### ISSUE TITLE
How to edit options? (to setup the NOTIFY function)

### ISSUE THREAD

**Issue by Johnnym3334** [vogler/free-games-claimer#57]
Hello, firstly thank you very much for this program. It is precisely what I have been looking for! Pardon me for asking what is likely a very simple question. I have messed with it for quite a while and properly set it up so that it runs on windows 11 using docker. By typing in the script "docker run --rm -it -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer" on a windows cmd prompt I am able to get the program to run successfully with no issues and set it up so it does it automatically every time I turn on my PC. My question is how to edit/find the options listed in the chart under configuration/options. If I can be pointed in the right direction that should suffice, I am just VERY novice to this and don't know where to look/start. I am wanting to set up the NOTIFY function specifically but without knowing how to even find the options I have no idea how to begin. Thank you very much for helping me learn and pardon if this is a dumb question! :)

**Comment by starkayc** [comment]
It's in the notification section in the [README ](https://github.com/vogler/free-games-claimer#notifications) but you basically add `-e NOTIFY='discord://webhook_id/webhook_token'` to your command. So final command is `docker run --rm -it -p 6080:6080 -e NOTIFY='discord://webhook_id/webhook_token -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer`.  You can find different notification services at [Apprise Docs](https://github.com/caronc/apprise#productivity-based-notifications) if you're using something else other than discord.

**Comment by Johnnym3334** [comment]
got it!!! thanks :) that was able to set me up with the notify function properly. A lot left to learn but that's a start!

**Comment by vogler** [comment]
Also see https://github.com/vogler/free-games-claimer/issues/52#issuecomment-1422223188 for further explanation.
You can also `docker run -it ghcr.io/vogler/free-games-claimer apprise ...` to play around with apprise inside the container.
