### ISSUE TITLE
page.waitForURL: Navigation failed because page was closed!

### ISSUE THREAD

**Issue by sealldeveloper** [vogler/free-games-claimer#58]
When logging into prime gaming I get this error:

```
page.waitForURL: Navigation failed because page was closed!
=========================== logs ===========================
waiting for navigation to "https://gaming.amazon.com/home?signedIn=true" until "load"
============================================================
    at file:///.../free-games-claimer/prime-gaming.js:83:16
```

No idea why.

**Comment by vogler** [comment]
Can you provide more context?
Did you sign in via the terminal or browser or not at all?
This line should just wait until you're logged in.
https://github.com/vogler/free-games-claimer/blob/f873d95a8987bde3069aa6873a82aaa20df8aac4/prime-gaming.js#L83
Did you close the page or kill the script? Then this is normal.

**Comment by sealldeveloper** [comment]
> Can you provide more context?
> Did you sign in via the terminal or browser or not at all?
> This line should just wait until you're logged in.
> https://github.com/vogler/free-games-claimer/blob/f873d95a8987bde3069aa6873a82aaa20df8aac4/prime-gaming.js#L83
> Did you close the page or kill the script? Then this is normal.

I entered correct account details, I entered the details in the terminal email and password sections. I did not use browser mode as headless mode isn't being used and adding the `show` parameter after didn't change the result either. I didn't close the page or kill the script.

 The script fails once I enter the details.

No clue...

**Comment by sealldeveloper** [comment]
Here is a complete (censored) output:
```
2023-02-14 01:40:47.537 started checking prime-gaming
Not signed in anymore.
Press ESC to skip if you want to login in the browser (not possible in default headless mode).
√ Enter email ... example@example.com
√ Enter password ... ***







page.waitForURL: Navigation failed because page was closed!
=========================== logs ===========================
waiting for navigation to "https://gaming.amazon.com/home?signedIn=true" until "load"
============================================================
    at file:///.../free-games-claimer/prime-gaming.js:83:16
```

Pressing `ESC` to go to the browser has this result (with the command `node prime-gaming show`):

```
2023-02-14 01:42:10.298 started checking prime-gaming
Not signed in anymore.
Press ESC to skip if you want to login in the browser (not possible in default headless mode).
× Enter email ...
Waiting for you to login in the browser.
Please run `node prime-gaming show` to login in the opened browser.
```
as default headless mode is what is currently running.

**Comment by vogler** [comment]
https://github.com/vogler/free-games-claimer/blob/acbfa9156e201c3d8dac1c3905381147be019c68/prime-gaming.js#L59-L62
This now got an empty text even for successful logins which made it quit. Should be fixed now.
