### ISSUE TITLE
[NOTIFICATIONS] Telegram notification won't work

### ISSUE THREAD

**Issue by Nackophilz** [vogler/free-games-claimer#63]
Hi!

I followed the instructions of apprise for the notification via Telegram. Unfortunately it doesn't seem to work

I have the TOKEN API provided by "BotFather" I have my chat id, but I can't receive anything.

Someone have this issue ?

**Comment by vogler** [comment]
My telegram notifications work fine, config looks something like this: `NOTIFY = 'tgram://1..2:A..s/%4..3/'`.
The script is just calling `apprise`:
https://github.com/vogler/free-games-claimer/blob/95598887cc6d8bf50c11e70f9d3ee668da62069d/util.js#L92
Using Docker? You can test apprise in the container with `docker run --rm -it ghcr.io/vogler/free-games-claimer apprise 'tgram://..'`.

**Comment by vogler** [comment]
https://github.com/caronc/apprise/wiki/Notify_telegram
> Type /start now in the same dialog box to enable and instantiate your brand new bot.

I think I had to do this in the chat of the bot, not in the BotFather chat (like the description makes it sound).

**Comment by Nackophilz** [comment]
When I try to use it with a python script I made with the learned library, it works

But not in my docker . Do I have to call learned in the variables?

I defined the NOTIFY variable, but there may be something else I didn't see?

**Comment by vogler** [comment]
> Do I have to call apprise in the variables?

No, just set the services you want to use.

> I defined the NOTIFY variable, but there may be something else I didn't see?

Did you set it correctly with `-e NOTIFY=...`? See https://github.com/vogler/free-games-claimer/discussions/59.

**Comment by Nackophilz** [comment]
Yes, not in this way because I am on UNRAID, but the command it sends is good

Do we have notification, when there is nothing to claim ? Or a notify test maybe ?

**Comment by vogler** [comment]
It sends a notification if you need to log in:
https://github.com/vogler/free-games-claimer/blob/95598887cc6d8bf50c11e70f9d3ee668da62069d/epic-games.js#L85
You could use a fresh volume (e.g. `-v fgc2:/fgc/data`) to try it.

**Comment by Nackophilz** [comment]
I see that in your screenshot on the presentation of the project, when you send hi, it answers you with a list of available games, and that are already taken, it would work for us? Or is there any other configuration to do?

**Comment by vogler** [comment]
> when you send hi, it answers you with a list of available games

No, I just made that screenshot after I implemented notifications. They're one-way, the script can't react to the chat.
The format of the notifications is the same as on the screenshot, you just get them when you run the scripts.

You can check what was already claimed in `data/*.json`.

**Comment by Nackophilz** [comment]
Oh okay got it ! 

That would be great to interact with it in that way haha ^^ 

Thank you for your help !

**Comment by vogler** [comment]
So what was the issue?
Maybe relevant for someone else on Unraid.

**Comment by Nackophilz** [comment]
So, there is no issue ! 
In fact, this Morning that work , he send notification only on new claim ^^
