### ISSUE TITLE
GOG Error 'TypeError: Cannot read properties of null (reading '1')'

### ISSUE THREAD

**Issue by sealldeveloper** [vogler/free-games-claimer#64]
Full Command Log:
```
2023-02-17 04:16:59.405 started checking gog
Signed in as 'username'
TypeError: Cannot read properties of null (reading '1')
    at file:///.../free-games-claimer/gog.js:90:58
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:442:9)
```

Line of code the error resides from:
`const title = text.match(/Claim (.*) and don't miss/)[1];`

Specifically the array item selection `[1]`

**Comment by sealldeveloper** [comment]
Fixed it! Game titles being too long cuts the `and don't miss` from the title so the regex fails. I'll send a PR to fix it shortly.

**Comment by sealldeveloper** [comment]
Noticed this was fixed recently, scrap the PR

**Comment by vogler** [comment]
Maybe I'll try to add some info (log + notify in case of error) when running an outdated version.
You're on Windows with the git repo checked out? Wondering if anyone is running it without git available (for Docker I could just add it).

**Comment by sealldeveloper** [comment]
> Maybe I'll try to add some info (log + notify in case of error) when running an outdated version.
> You're on Windows with the git repo checked out? Wondering if anyone is running it without git available (for Docker I could just add it).

I have git installed, repo updated (just used `git pull`)
