### ISSUE TITLE
language is DE instead of EN

### ISSUE THREAD

**Issue by ladiko** [vogler/free-games-claimer#65]
As i couldn't find any hint towards it, i wanted to point it out at least once for others. prime-gaming,js didn't claim anything at first

```cmd
C:\Users\ladiko\Downloads\free-games-claimer>node prime-gaming.js
2023-02-17 21:34:07.022 started checking prime-gaming
Signed in as ladiko
Number of already claimed games (total): 0
Number of free unclaimed games (Prime Gaming): 0
Number of free unclaimed games (external stores): 0
``` 

So i `set SHOW=1` and inside the firefox window, I changed the language to EN in the upper right website menu and Tada!:

```cmd
C:\Users\ladiko\Downloads\free-games-claimer>node prime-gaming.js
2023-02-17 21:36:09.249 started checking prime-gaming
Signed in as ladiko
Number of already claimed games (total): 14
Number of free unclaimed games (Prime Gaming): 1
Current free game: Real Bout Fatal Fury 2: The Newcomers
Number of free unclaimed games (external stores): 0
```

Seems like this website setting is stored within the session storage of the included frefox bundle as it doesn't affect my normal browser's language setting. If i set it back to DE it won't read any values again. So it's good to know if total games is zero, I know the language has to be switched:

```cmd
C:\Users\ladiko\Downloads\free-games-claimer>node prime-gaming.js
2023-02-18 04:58:51.869 started checking prime-gaming
Signed in as ladiko
Number of already claimed games (total): 0
Number of free unclaimed games (Prime Gaming): 0
Number of free unclaimed games (external stores): 0
```

Once the language is set, i can unset SHOW and it't fine. Maybe it can be made a setting or at least a hint is shown if total is zero. A written hint in readme.md might help one or the other.

**Comment by vogler** [comment]
https://github.com/vogler/free-games-claimer/blob/957ba6d7ca26379a6868cf26d94fdab322bcd09f/prime-gaming.js#L19
This line should make sure that all text is english. The question is why yours was set to german. Did you sign in in the browser?

**Comment by ladiko** [comment]
I can't remember what I did first time, i started with the docker version, but removed it all as it was a big lump so i went for just installing node etc. and using cmd instead. hmm but login might have been inside the browser as i had issues while using docker and the command line login before. So it's my fault, okay.

**Comment by vogler** [comment]
> i started with the docker version, but removed it all as it was a big lump

You mean because the image is 1.12GB or something else? You can try https://podman.io if you don't want Docker running all the time.
But node is fine, the docker image is just for convenience.

> as i had issues while using docker and the command line login before

Via cmd or inside a Docker Desktop terminal? However, both should be fine.

> So it's my fault, okay.

Only if you manually switched it to german 😄 - otherwise it should work.
Maybe you encountered an issue that other people have as well. I have all my OS set to english, maybe `locale: "en-US"` is not enough for a german Windows.
Maybe there's some language value in session storage or cookies that needs to be set as well.

**Comment by ladiko** [comment]
Yes, the docker image is a waste of space while nodejs is a useful lightweight runtime.

So to be sure, I started from zero and it was my fault:

```cmd
C:\Users\ladiko\Downloads>rmdir /s /q free-games-claimer

C:\Users\ladiko\Downloads>git clone --quiet https://github.com/vogler/free-games-claimer

C:\Users\ladiko\Downloads>cd free-games-claimer

C:\Users\ladiko\Downloads\free-games-claimer>npm install --silent

C:\Users\ladiko\Downloads\free-games-claimer>npx --quiet playwright install firefox

C:\Users\ladiko\Downloads\free-games-claimer>node prime-gaming.js
2023-02-18 21:27:24.709 started checking prime-gaming
Not signed in anymore.
Press ESC to skip if you want to login in the browser (not possible in default headless mode).
√ Enter email ... a@bc.de
√ Enter password ... ********
Signed in as ladiko
Number of already claimed games (total): 15
Number of free unclaimed games (Prime Gaming): 0
Number of free unclaimed games (external stores): 0
```

**Comment by vogler** [comment]
> Yes, the docker image is a waste of space while nodejs is a useful lightweight runtime.

I also run it without docker, but most people prefer docker for easy setup. At some point it was also needed to hide the browser inside the container since epic-games showed captchas in headless mode.

> Ohh and login works flawless for all three, just in case of wrong login data, the timeout (if any exists) is quite long.

Timeout is infinite during login. Maybe I should change it to 5min to not accumulate scheduled processes hanging on login.
Which store? I think I only added code to detect wrong login data for prime-gaming.

**Comment by ladiko** [comment]
I entered "a" as email and password and none of gog, epic or prime ever ended without pressing Ctrl +C. I even let epic run overnight.

**Comment by vogler** [comment]
Yes, it just waits until you log in. To be fixed in https://github.com/vogler/free-games-claimer/issues/69.
