### ISSUE TITLE
Prime-gaming headless prompt is not progressing after entering email

### ISSUE THREAD

**Issue by kennymc-c** [vogler/free-games-claimer#66]
When I try to login in headless mode (SHOW=0) I get the prompt to enter email but after I press enter nothing happens and I have to quit docker. When doing this via VNC the login pages seems to load fine.

```
docker run --rm --pull=always --name='free-games-claimer' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e HOST_HOSTNAME="smartserver" -e HOST_CONTAINERNAME="free-games-claimer-headless" -e 'NOTIFY'='pover://xxx@xxx' -e 'SHOW'='0' -l net.unraid.docker.managed=dockerman -v '/mnt/user/appdata/free-games-claimer/':'/fgc/data':'rw' 'voglerr/free-games-claimer' node prime-gaming
latest: Pulling from voglerr/free-games-claimer
Digest: sha256:c42489e7695c98e91bd6c386ed3c5f75b0db472407c1103ff6e614a9985128d3
Status: Image is up to date for voglerr/free-games-claimer:latest
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080

2023-02-18 11:27:40.471 started checking prime-gaming
Not signed in anymore.
Press ESC to skip if you want to login in the browser (not possible in default headless mode).
? Enter email › a@b.com
```

EDIT: I just checked that when connected via VNC the focus is on the address bar and not the login field. Could this be the problem?

**Comment by vogler** [comment]
> I just checked that when connected via VNC the focus is on the address bar and not the login field. Could this be the problem?

No, playwright takes care of filling inputs regardless of focus.

It happens for both headless and non-headless?
Can you check where it gets stuck? You can kill it with Ctrl-C and see the exception or step through it with `PWDEBUG=1`.

https://github.com/vogler/free-games-claimer/blob/957ba6d7ca26379a6868cf26d94fdab322bcd09f/prime-gaming.js#L42-L47

I don't see how it should stop after the email prompt. What terminal are you using? Does the icon in front of the prompt change after you press enter?
![image](https://user-images.githubusercontent.com/493741/219864869-880464b2-9d62-4bc2-b305-3263fbcb1141.png)

**Comment by kennymc-c** [comment]
This is what I get with `PWDEBUG=1` and `SHOW=1`. I get the same result with `SHOW=0`. I can't connect via VNC and noVNC with this.

```
docker run --rm --pull=always --name='free-games-claimer' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e HOST_HOSTNAME="smartserver" -e HOST_CONTAINERNAME="free-games-claimer" -e 'NOTIFY'='pover://xxx@xxx' -e 'SHOW'='1' -l net.unraid.docker.managed=dockerman -v '/mnt/user/appdata/free-games-claimer':'/fgc/data':'rw' -e 'PWDEBUG'='1' -p '6080:6080/tcp' -e 'VNC_PASSWORD'='xxx' 'voglerr/free-games-claimer' node prime-gaming
latest: Pulling from voglerr/free-games-claimer
Digest: sha256:c42489e7695c98e91bd6c386ed3c5f75b0db472407c1103ff6e614a9985128d3
Status: Image is up to date for voglerr/free-games-claimer:latest
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080

2023-02-18 12:19:15.898 started checking prime-gaming
node:internal/process/esm_loader:100
    internalBinding('errors').triggerUncaughtException(
                              ^

browserType.launchPersistentContext: 
╔═══════════════════════════════════════════════════╗
║ No chromium-based browser found on the system.    ║
║ Please run the following command to download one: ║
║                                                   ║
║     npx playwright install chromium               ║
║                                                   ║
║ <3 Playwright Team                                ║
╚═══════════════════════════════════════════════════╝
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/firefox-1372/firefox/firefox -no-remote -wait-for-browser -foreground -profile /fgc/data/browser -juggler-pipe about:blank
<launched> pid=196
[pid=196][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.644443) [GFX1-]: glxtest: libpci missing
[pid=196][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.644443) |[1][GFX1-]: glxtest: libEGL missing (t=0.644499) [GFX1-]: glxtest: libEGL missing
[pid=196][out] 
[pid=196][out] Juggler listening to the pipe
============================================================
    at async file:///fgc/prime-gaming.js:16:17

Node.js v19.6.0
```

I'm using Unraid's 6.11.5 Webterminal. The icon is still a ? after entering my email
![Bildschirm­foto 2023-02-18 um 13 47 52](https://user-images.githubusercontent.com/14995555/219866655-aef89b4c-27b9-4d3c-bd8c-6fa1de5fbcf2.png)

Login to Epic and GOG worked fine with this.

I also tried it on macOS terminal via SSH to Unraid and native via docker for macOS. Same result everywhere.

**Comment by vogler** [comment]
> This is what I get with `PWDEBUG=1` and `SHOW=1`. I get the same result with `SHOW=0`. I can't connect via VNC and noVNC with this.

`SHOW=1` is the default in the docker image. There's not really any reason to set it to 0. non-headless = `PWDEBUG || SHOW`.

I just checked that the inspector (`PWDEBUG=1`) apparently doesn't work in the image since there are some libraries missing (getting the same exception and wrong mention of chromium).

> The icon is still a ? after entering my email

It should be a green checkmark like in my screenshot.

> Login to Epic and GOG worked fine with this.

This is weird since they are using the exact same code.

Do you use a different email for them?
Does it work if you set `PG_EMAIL`?

**Comment by kennymc-c** [comment]
The email is the same for all accounts. With `PG_EMAIL` something strange happens: First you are directly prompted for the password as expected. But then I noticed that you enter it in plain text and it is not made unrecognizable with asterisks as it was before with the other platforms. After this the same behavior as before: The question mark remains and nothing happens. If I also enter the password as a variable, I get stuck at the OTP code prompt.
I tried it again with a completely new volume and started the container without additional commands. Now I had the same problem as well with Epic and GOG. No idea why it worked before, although I did it the same way.

**Comment by vogler** [comment]
You're missing `-it` in your `docker run` command 😄
Without an interactive terminal, you just see the output, but can't input anything (that's why the password was plain text - you were just writing into the terminal's output).

**Comment by stalsma** [comment]
An additional note regarding -it.  If configuring as a scheduled task, my environment (Docker on Synology) returned an error:
> the input device is not a TTY
when running with -it.

So after running the command the first time from prompt (w -it), I had to remove it in order to get the scheduled task to work.  (Might be worth adding a note in docs?)

**Comment by vogler** [comment]
> (Might be worth adding a note in docs?)

[This](https://github.com/vogler/free-games-claimer/discussions/56) is linked as an example where it mentions dropping `-it`.
