### ISSUE TITLE
[Feature Request] Timeout & notification when not logged in

### ISSUE THREAD

**Issue by kennymc-c** [vogler/free-games-claimer#69]
I noticed that the container does not timeout when you are not logged in. You always get stuck at the Epic login and the container keeps running forever. This is not very handy when running it as a script in the background. I currently solved this with a `timeout 30` before `docker run`, but of course that's not a nice solution. If there are problems only with Epic, Prime and GOG are ignored.
Better would be a timeout that can be defined by an environment variable when user input is expected. Additionally, a push notification should be sent when login data has to be entered again and the timeout has been reached.

**Comment by vogler** [comment]
I'm adding some `LOGIN_TIMEOUT` with a default of 3min. Should be enough time to login manually and not too much wait for scheduled runs.
Notification is already there, just need to cancel the prompts somehow.

**Comment by kennymc-c** [comment]
Just tested the notifications but got nothing for GOG although I was not logged in. Epic and Prime worked fine.

**Comment by vogler** [comment]
What did your log say? Notification is sent right after `Waiting for you to login in the browser`. The relevant code is pretty much the same:
![image](https://user-images.githubusercontent.com/493741/220734296-a3c5d6d9-9c11-4aa8-9a50-50c411c0a251.png)

**Comment by kennymc-c** [comment]
It is probably related to Pushover since I could get it to work at least a few times after it stopped again.

**Comment by vogler** [comment]
For faster testing of notifications you can `docker run ... apprise ...`.
https://github.com/vogler/free-games-claimer/blob/38c5402df040c81f330b706db118a45c3652d6f3/util.js#L104

**Comment by kennymc-c** [comment]
I tried it a few times in a row directly via apprise and everything arrived immediately. I think it could be related to the full command with all three platforms. After this I noticed notification problems with Epic and Prime as well even when just running one platform.

**Comment by vogler** [comment]
Sounds like a timing issue. Likely the process is killed before the notification is sent. Are you still using a timeout or some other signal? Did you set `SHOW=0`?

**Comment by kennymc-c** [comment]
Seems to work fine and the latest image from today but only without `SHOW=0`. When this is set, I am missing the last notification. The default `SHOW=1` value doesn't make sense for me when running this as a background script without any expected user interaction to follow and it will also result in a second notification which I don't get when using `SHOW=0`.

Can the title of the notifications be changed or at least be named like the repository? At the moment they are all called Apprise Notification and what I figured out this can not be configured within the notification url and has to be a separate parameter.

**Comment by vogler** [comment]
> Can the title of the notifications be changed or at least be named like the repository? At the moment they are all called Apprise Notification and what I figured out this can not be configured within the notification url and has to be a separate parameter.

I added an option `NOTIFY_TITLE`. Default is empty since the title is only useful for something like Pushover, but too much noise for something like Telegram:
![image](https://user-images.githubusercontent.com/493741/221053316-511d10f8-49af-405d-a061-042d433e65aa.png)

**Comment by vogler** [comment]
> Seems to work fine and the latest image from today but only without `SHOW=0`. When this is set, I am missing the last notification.

Race condition should be fixed since `notify` is now awaited before `process.exit`.

> The default `SHOW=1` value doesn't make sense for me when running this as a background script without any expected user interaction to follow

It's only the default for docker since there you want to be able to check/interact via VNC. There's no advantage to run with `SHOW=0` in the container: it's not really faster, it may be detected and lead to captchas (currently not the case), and you can't see anything or login via VNC.

> and it will also result in a second notification which I don't get when using `SHOW=0`.

The timeout when not logging in? This is expected.

**Comment by kennymc-c** [comment]
> I added an option `NOTIFY_TITLE`.

Thanks for this fast fix!

> Race condition should be fixed since `notify` is now awaited before `process.exit`.

Thanks again, now I get all notifications with `SHOW=0`

> There's no advantage to run with `SHOW=0` in the container: it's not really faster, it may be detected and lead to captchas (currently not the case), and you can't see anything or login via VNC.

Then I don't understand why you can change the default `SHOW` value at all when it just leads to more problems and only blanks the VNC output. My original assumption was that `SHOW=0` is for running the container in an unattended script where there will never be any user input. Shouldn't it work when the vnc output is not blanked anymore, deactivate any prompts and maybe name it unattended?

> The timeout when not logging in? This is expected.

Yes, this is why I used `SHOW=0` to get rid of the second notification from the additional timeout of the manual browser login which in my case wouldn't work anyway (see above).

**Comment by vogler** [comment]
> Then I don't understand why you can change the default SHOW value at all when it just leads to more problems and only blanks the VNC output.

It's for running the scripts locally without docker where the default is `SHOW=0`.

> My original assumption was that SHOW=0 is for running the container in an unattended script where there will never be any user input.

`SHOW` is just for showing the browser or not. There is no unattended mode - if you're not logged in, you can set environment variables, login via the prompts or via the browser. After you've logged in once, it should stay logged in, so effectively run unattended.

> Yes, this is why I used SHOW=0 to get rid of the second notification from the additional timeout of the manual browser login which in my case wouldn't work anyway (see above).

If you don't login it will time out and you'll get another notification. If you don't want to claim for a certain store you should not run it to avoid timeout & notification.

I'm open for other ideas.
