### ISSUE TITLE
Canceling the prime gaming check

### ISSUE THREAD

**Issue by Spp595** [vogler/free-games-claimer#72]
I want to use this container only for epic games, is there any variable to disable checking for other services?

**Comment by vogler** [comment]
README.md:
> if you only want to claim games for one of the stores, you can override the default command by appending e.g. `node epic-games` at the end of the `docker run` command.

So:
`docker run --rm -it -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer node epic-games`

So far, there are no options for it since the scripts work standalone.
