### ISSUE TITLE
Unraid: how to run only specific stores?

### ISSUE THREAD

**Issue by shomilsaini** [vogler/free-games-claimer#73]
Command fails on using 

node epic-games; node gog

in post arguments on UnRaid in Docker.
![image](https://user-images.githubusercontent.com/46788173/220984662-82aa8f7b-93ce-4bf4-9f00-03c831b09fd2.png)

Thanks

**Comment by vogler** [comment]
I don't know UnRaid. Is Post Arguments the right field? Do you have some error log?
https://forums.unraid.net/topic/58700-passing-commandsargs-to-docker-containers-request/

**Comment by adibue** [comment]
@shomilsaini Looks like it's working this way just fine for me. I get the error `node not found` when running it the first time, but it still works according to the logs:

> 2023-02-23 17:49:50.387 started checking epic-games
> Open http://localhost:6080 to login inside the docker container.
> Login timeout is 180 seconds!
> Using email and password from environment.
> Enter the security code to continue - This appears to be a new device, browser or location. A security code has been sent to your email address at ...
> Signed in as someguywholovesfreegames
> Free games: [ 'https://store.epicgames.com/en-US/p/duskers-672fdc' ]
> Current free game: Duskers
>   Already in library! Nothing to claim.

**Comment by kennymc-c** [comment]
I'm having the same problem in Unraid. Log when trying to start the container:

```
docker run
  -d
  --name='free-games-claimer'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="smartserver"
  -e HOST_CONTAINERNAME="free-games-claimer"
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://192.168.1.201:6080'
  -p '6080:6080/tcp'
  -v '/mnt/user/appdata/free-games-claimer/':'/fgc/data':'rw' 'voglerr/free-games-claimer' node prime-gaming; node gog
b98a08dd4436e4a103ee5a9759548163c1973b02d6acd1889000ce5591eda0ad
sh: line 1: node: command not found
```

Pasting the same command without -d and a different container name in a script and running it via User Scripts works for the first command. Log ends with `bash: node: command not found`

**Comment by shomilsaini** [comment]
it works fine for first store - in your case epic but will not run the gog store or the 2nd store.
documentation is not clear on how to use 2/3 stores. Docs only mention about using either 1 store or all.
I will post logs soon.

https://github.com/vogler/free-games-claimer/blob/main/README.md#how-to-run

![image](https://user-images.githubusercontent.com/46788173/220991154-12d21d54-8d16-4f15-a391-e9ba4996b146.png)


Thanks

**Comment by shomilsaini** [comment]
I have just reduced the TIMEOUT & LOGIN_TIMEOUT for container as a work around and it will run all stores but will fail for Prime store.

Also, EMAIL and PASSWORD fields are mandatory(not sure why?) so it tries to login with them but fails on prime as I have intentionaly used gobbledygook in them as I do not have amazon prime and I don't want to keep logging in with my real amazon account.


Thanks

**Comment by adibue** [comment]
> it works fine for first store - in your case epic but will not run the gog store or the 2nd store. documentation is not clear on how to use 2/3 stores. Docs only mention about using either 1 store or all. I will post logs soon.
> 
> https://github.com/vogler/free-games-claimer/blob/main/README.md#how-to-run
> 
> ![image](https://user-images.githubusercontent.com/46788173/220991154-12d21d54-8d16-4f15-a391-e9ba4996b146.png)
> 
> Thanks

True that. Sorry, I didn't notice. Couldn't get it to work either 🤷‍♂️

**Comment by guipace** [comment]
Just stopping in to add a plus one to this issue.

**Comment by vogler** [comment]
This is some issue with Unraid on how to pass the command correctly.
Here's how it looks for me with zsh:
![image](https://user-images.githubusercontent.com/493741/220994974-c3ebd2fa-b905-4245-b2dc-89bc9f3d33e5.png)

Maybe it's the shell. Try putting it in quotes: ... 'node epic-games; node gog'.

> sh: line 1: node: command not found

Indicates that it's not being executed in the container, but on your host.

> Also, EMAIL and PASSWORD fields are mandatory(not sure why?)

No, they're optional for automatic login.

**Comment by guipace** [comment]
> Also, EMAIL and PASSWORD fields are mandatory(not sure why?) 

Seems like this is not and issue with the application but with the unraid community applications docker template that was created by [this guy](https://forums.unraid.net/profile/161066-nackophilz/).

**Comment by Nackophilz** [comment]
Hi!

I'm the one who made the template for Unraid, I'm thinking, to select the node we want, couldn't we make an environment variable?

For example :

-e STORE: "all" -e STORE: "epic-games;gog"


I don't know if it's possible, or not, but it could be interesting, it's true that I made the template for Unraid without thinking about the command after the docker run

**Comment by adibue** [comment]
> Ok, you apparently can't pass some shell expression like `node epic-games; node gog` as the command. You can use `bash -c "node epic-games.js; node gog.js"`: ![image](https://user-images.githubusercontent.com/493741/220997888-868d6f5c-a011-4772-b7ef-1594fc4e0108.png)

Thank you for this answer. This works great!

**Comment by guipace** [comment]
> Hi!
> 
> I'm the one who made the template for Unraid, I'm thinking, to select the node we want, couldn't we make an environment variable?
> 
> For example :
> 
> -e STORE: "all" -e STORE: "epic-games;gog"
> 
> I don't know if it's possible, or not, but it could be interesting, it's true that I made the template for Unraid without thinking about the command after the docker run

Thanks for your work in adding this to Unraid!

**Comment by Nackophilz** [comment]
> > Also, EMAIL and PASSWORD fields are mandatory(not sure why?)
> 
> Seems like this is not and issue with the application but with the unraid community applications docker template that was created by [Nackophilz](https://forums.unraid.net/profile/161066-nackophilz/).

I made it mandatory by reflex, since most people put the same password and the same email for many things, but indeed, I can remove the obligation to fill them! 
What do you think it's better ?  :)

**Comment by guipace** [comment]
I can also confirm that `bash -c "node epic-games.js; node gog.js"` in the `Post Arguments` field works, but agree that an argument such as @Nackophilz suggested would be a better user experience.

@Nackophilz, I would suggest removing the requirement for those arguments. In my case I use a password manager and none of my passwords are the same. Just one use case as an example.

**Comment by Nackophilz** [comment]
> I can also confirm that `bash -c "node epic-games.js; node gog.js"` in the `Post Arguments` field works, but agree that an argument such as @Nackophilz suggested would be a better user experience.
> 
> @Nackophilz, I would suggest removing the requirement for those arguments. In my case I use a password manager and none of my passwords are the same. Just one use case as an example.

Yes, I will update the template, I will also remove the "--pull=always" since Unraid has an update monitor built in :)

**Comment by Nackophilz** [comment]
Anyway, thanks for your great work @vogler, it's a real pleasure to use your tool !

You will make many people in the Unraid community happy!

**Comment by vogler** [comment]
> For example :
> 
> -e STORE: "all" -e STORE: "epic-games;gog"
> 
> I don't know if it's possible, or not, but it could be interesting, it's true that I made the template for Unraid without thinking about the command after the docker run

Currently the scripts are all standalone but pretty similar.
My idea was to extract the shared framework into an `index.js` which can call the code for the individual stores (e.g. depending on some option as you proposed). The existing files can call the code from there such that you can still execute them individually so that existing setups don't break.
This new file could then also guide through and save the configuration, either on the command line or maybe some webserver (integrated server-mode with scheduling might be nice to have anyway).

**Comment by Nackophilz** [comment]
Meanwhile, if I understood the system, putting: 
bash -c "node epic-games.js; node gog.js"

In the post arguments, means for the docker, that we only want to use the epic-games and GOG stores right?

I can update the template to add this as an instruction if needed :)

**Comment by vogler** [comment]
> means for the docker, that we only want to use the epic-games and GOG stores right?

yes

**Comment by guipace** [comment]
@Nackophilz, do you see any files for this app in your unraid appdata directory? I don't have a `fgc` directory in there and noticed the `/fgc/data` mapping seems different than any other template I've seen:
`/mnt/user/appdata/fgc" Mode="rw" Description="Data path" Type="Path" Display="always" Required="true" Mask="false`
That doesn't seem to be a valid path. I could be wrong.

**Comment by Nackophilz** [comment]
> @Nackophilz, do you see any files for this app in your unraid appdata directory? I don't have a `fgc` directory in there and noticed the `/fgc/data` mapping seems different than any other template I've seen: `/mnt/user/appdata/fgc" Mode="rw" Description="Data path" Type="Path" Display="always" Required="true" Mask="false` That doesn't seem to be a valid path. I could be wrong.

Yes on my side I have the FGC folder which is created without any problem, with two folders in it and my configuration files for each store :)

I just add the default path to "/mnt/user/appdata/fgc" in the template

**Comment by Nackophilz** [comment]
New template updated come here for issue now : https://github.com/Nackophilz/unraid_templates/issues

Sorry @vogler i dont want to disturb you !

**Comment by vogler** [comment]
Can this Unraid template be generated (maybe via a GitHub Action)? Seems like a source of issues to keep it up to date manually. There's already a [docker-compose.yml](https://github.com/vogler/free-games-claimer/blob/main/docker-compose.yml) as a template for Portainer.

**Comment by Nackophilz** [comment]
> Can this Unraid template be generated (maybe via a GitHub Action)? Seems like a source of issues to keep it up to date manually. There's already a [docker-compose.yml](https://github.com/vogler/free-games-claimer/blob/main/docker-compose.yml) as a template for Portainer.

I dont think so, i have to update manually each time (or i dont know how to do it ^^) 

I fix almost all issue on the template (sorry wrong first publish haha)

I will update it if needed to suite you're requirement :)

**Comment by unkindlykiller** [comment]
im curious how you update it now? i mean somehow this has showed up in the unraid application store.

**Comment by vogler** [comment]
> Yes, I will update the template, I will also remove the "--pull=always" since Unraid has an update monitor built in :)
https://github.com/vogler/free-games-claimer/issues/73#issuecomment-1442253162

@Nackophilz re @unkindlykiller: maybe put it back? I don't know how often the update monitor runs.

**Comment by Nackophilz** [comment]
> > Yes, I will update the template, I will also remove the "--pull=always" since Unraid has an update monitor built in :)
> > [#73 (comment)](https://github.com/vogler/free-games-claimer/issues/73#issuecomment-1442253162)
> 
> @Nackophilz re @unkindlykiller: maybe put it back? I don't know how often the update monitor runs.

Unraid monitor each day for update on the container, if you put --pull:always, on the extra parameter, he will update himself, but , unraid still monitor for update, and then ask you to update on the webgui :) 

So there is no benefit ( on unraid ) to put that option :) 

But users Can add it if they want :)

**Comment by vogler** [comment]
> and then ask you to update on the webgui (even if you already updated) :)

Ok, strange.

**Comment by vogler** [comment]
I'll close this then since it seems to work.

@Nackophilz How to you update the template, do you need to upload this XML file somewhere or is it pulled? Keeping the file inside this repo or generating it based on something seems like a less error-prone solution to me.

**Comment by Nackophilz** [comment]
> I'll close this then since it seems to work.
> 
> @Nackophilz How to you update the template, do you need to upload this XML file somewhere or is it pulled? Keeping the file inside this repo or generating it based on something seems like a less error-prone solution to me.

I update it with manually, i just add the key we need on Unraid , and i pull it in my repo then Unraid auto update the template on his CA :) 
And i test all modification on my side before

I have to change the template only when you add or remove New variable, otherwise, nothing change and we took only package update :)

**Comment by unkindlykiller** [comment]
> > I'll close this then since it seems to work.
> > @Nackophilz How to you update the template, do you need to upload this XML file somewhere or is it pulled? Keeping the file inside this repo or generating it based on something seems like a less error-prone solution to me.
> 
> I update it with manually, i just add the key we need on Unraid , and i pull it in my repo then Unraid auto update the template on his CA :) And i test all modification on my side before
> 
> I have to change the template only when you add or remove New variable, otherwise, nothing change and we took only package update :)

yeah that should definitely be integrated with the main repo
