### ISSUE TITLE
Epic Games: Can not claim when not connected to VNC

### ISSUE THREAD

**Issue by kennymc-c** [vogler/free-games-claimer#75]
When running:

```
docker run --rm \
--pull=always \
--name='free-games-claimer-headless' \
--net='bridge' \
-e TZ="Europe/Berlin" \
-e HOST_OS="Unraid" \
-e HOST_HOSTNAME="smartserver" \
-e HOST_CONTAINERNAME="free-games-claimer-headless" \
-e 'NOTIFY'='pover://xxx@xxx' \
-l net.unraid.docker.managed=dockerman \
-v '/mnt/user/appdata/free-games-claimer/':'/fgc/data':'rw' \
'voglerr/free-games-claimer' node epic-games
```

I get the following log and the current free epic game will not be claimed:

```
latest: Pulling from voglerr/free-games-claimer
Digest: sha256:65a77e4104b62c6383a42cb98b997ea45d6f40a1bd02a5767c112fe08aa00169
Status: Image is up to date for voglerr/free-games-claimer:latest
Xvfb display server created screen with resolution 1280x1280
VNC is running on port 5900 (no password!)
noVNC (VNC via browser) is running on http://localhost:6080

2023-02-23 18:38:42.899 started checking epic-games
Signed in as xxx
Free games: [ 'https://store.epicgames.com/en-US/p/duskers-672fdc' ]
Current free game: Duskers
Not in library yet! Click GET.
page.click: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator('[data-testid="purchase-cta-button"]')
locator resolved to attempting click action
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
scrolling into view if needed
done scrolling
performing click action
============================================================
at file:///fgc/epic-games.js:136:18 {
name: 'TimeoutError'
}
```

I tried to set a different timeout but this just removed the timeout warning and the game still wasn't claimed.
Next I ran the container with port 6080 and 5900 exposed, set a VNC Password and tried to connected via noVNC. I was supprised that this time the game was claimed as expected. What could be the reason?

**Comment by Nackophilz** [comment]
New template updated come here for issue : https://github.com/Nackophilz/unraid_templates/issues

**Comment by kennymc-c** [comment]
I am not using your template since I want to run the container just once a day. I am using User Scripts instead and run the shown docker run command from there. I also don't think this issue ist related to Unraid specific.

**Comment by vogler** [comment]
> connected via noVNC. I was supprised that this time the game was claimed as expected. What could be the reason?

I noticed something similar for the last game (native, not docker).
I tried it again and it worked. Not sure if it was a timing issue or because I used `SHOW=1` the second time and moved the mouse over the browser.
Maybe they added some requirement to move the mouse.
I'll try again for this week's game.

**Comment by EthanC** [comment]
I also had this issue with today's game.

FGC (Docker) failed 4 times, then I connected to VNC to record the screen, and it redeemed successfully.

**Comment by vogler** [comment]
Commit message:

> Playwright triggered the click such that the purchase frame opened, but
did not resolve the promise. Had to move mouse into the browser for it
to continue. Adding a click delay of 1ms also worked (default is no
delay between mouse down and up). Went for 11ms. A typical click is
probably 100-200ms.

Probably some effort to detect automation on their side.
Could also make `delay` random in [100, 500], but let's see how long this fix holds 😄
