### ISSUE TITLE
[request] - Skip specific store

### ISSUE THREAD

**Issue by nodiaque** [vogler/free-games-claimer#78]
Hello,

Would be nice to have a var to enable/disable specific store. For exemple, I don't have amazon prime. Even if I put no username/pass, it try to login to prime. A simple "ENABLE_PRIME", "ENABLE_GOG", ... would solve this.

Thank you!

**Comment by Nackophilz** [comment]
Hi! It's already in the readme : https://github.com/vogler/free-games-claimer#how-to-run

You just have to enable only the store you want :)

**Comment by vogler** [comment]
> You can append `bash -c "node epic-games.js; node gog.js"` to your `docker run` to skip Prime Gaming.

_Originally posted by @vogler in https://github.com/vogler/free-games-claimer/issues/76#issuecomment-1443298977_

>> For example :
>> 
>> -e STORE: "all" -e STORE: "epic-games;gog"
>> 
>> I don't know if it's possible, or not, but it could be interesting, it's true that I made the template for Unraid without thinking about the command after the docker run
>
>Currently the scripts are all standalone but pretty similar.
>My idea was to extract the shared framework into an `index.js` which can call the code for the individual stores (e.g. depending on some option as you proposed). The existing files can call the code from there such that you can still execute them individually so that existing setups don't break.
>This new file could then also guide through and save the configuration, either on the command line or maybe some webserver (integrated server-mode with scheduling might be nice to have anyway).

_Originally posted by @vogler in https://github.com/vogler/free-games-claimer/issues/73#issuecomment-1442259901_

**Comment by nodiaque** [comment]
Ok, I had to find how to do it on the unraid template. Turns out, need the whole bash -c... line.

**Comment by vogler** [comment]
> simply having the entrypoint checking the variable to run the correct node.

Also needs to work without docker.
I'll add some options `EG`, `PG`, `GOG` that are checked at the beginning of each script.
