### ISSUE TITLE
skip scripts with docker-compose?

### ISSUE THREAD

**Issue by EQUALIT-CG** [vogler/free-games-claimer#85]
Hello Vogler

This could be better if free game claimer only looks for what you have in your docker-compose
what do i mean!

Well at this time for now I only run this for Epic because I'm lazy to login and click a few buttions

But the issues i have is as soon as its claimed the Epic it will try and log into Amazon and claims games even know i have not filled out login in my docker-compose etc etc

```
    environment:
      - SHOWVMC=1
      - VNC_PASSWORD=
      - PUID=1061
      - PGID=101
      - EG_EMAIL=example@outlook.com
      - EG_PASSWORD=AwKruH5ohjQZes4
#      - PG_EMAIL=example@outlook.com
#      - PG_PASSWORD=AwKruH5ohjQZes4

```

So i think it would better to check for what I have in my Environment say EG and any other Once i know i have the login info for that store then i can go claim the games from there store Once i have it can sleep for 48 hours

Maybe add
    environment:
      - EG_EMAIL=example@outlook.com
      - EG_PASSWORD=AwKruH5ohjQZes4
      - EG_TIME-OUT=3mins
           
This way can sleep and check again in 48 hours right now i log on every now and then when i see some Discord show that there are Epic free games

I will have another test soon as i think the VnC via brower has a time out itself but will make a new PR cheers

**Comment by unkindlykiller** [comment]
#78

**Comment by EQUALIT-CG** [comment]
@unkindlykiller 

I'm sure you can but I'm not running this as a docker run
First I'm using Docker-compose
2nd it should not auto grab games if you haven't enter info for a store
since i don't use Amazon right now or anything expect Epic then shouldn't need to open anything but epic full stop

would use less resources example
- EG_EMAIL=[example@outlook.com](mailto:example@outlook.com)
- EG_PASSWORD=AwKruH5ohjQZes4


start the docker-compose
Log into Epic games grab the games 
any more log in info

AMAZON_Prime=nill
AMAZON_Prime=nill

no close end of story

**Comment by EQUALIT-CG** [comment]
@unkindlykiller 

I did take a look at #78 and think maybe i can

do it via docker-compose if i do it like the following if I'm reading it right

environment:
- STORE: "all"
- STORE: "epic-games;gog"

**Comment by vogler** [comment]
> RE: game flaimer idile

What is the title supposed to mean?

> 2nd it should not auto grab games if you haven't enter info for a store
> since i don't use Amazon right now or anything expect Epic then shouldn't need to open anything but epic full stop

Then don't run the script you don't want to run. How should it know if you want to login manually?

> do it via docker-compose if i do it like the following if I'm reading it right
> 
> environment:
> 
> * STORE: "all"
> * STORE: "epic-games;gog"

No, that was discussing an idea.

Just change the command that docker-compose runs, it's the same as for #73.
https://docs.docker.com/compose/compose-file/#command

I included it in the example:
https://github.com/vogler/free-games-claimer/blob/a5f42a960918b313aa972a971555aa06641b8dfe/docker-compose.yml#L12-L15

**Comment by vogler** [comment]
Technologically this is the simplest solution, but I see that it is too complicated to use.
I'll add some options to skip scripts.

**Comment by vogler** [comment]
I got what you meant. The problem is that not everyone wants to put down email and password in the environment. Some people just login manually at the beginning and that's it, some people put down their email and enter the password manually.
So you can't use email/password as an indicator whether the script should run or not.

> should i add the command like so I do apologize if its wrong

Yes, that looks right.
I'll also add some options (probably just `EG`, `PG`, `GOG`) that you can set to `0` to skip the respective script. Then this can be configured via the environment as well.

**Comment by EQUALIT-CG** [comment]
Hi Volger

Yea i get what you mean i though if you were using an EG_ meaning you want to only run that part of the script but i understand some people wish to log in manually  witch makes seances

maybe try both out see what works best say 

trial 1own our own or clone this repository and test out what works best

when adding login info then x script runs or if
EG=1
the epic games runs its script runs with out the rest

you know what best then what i know thanks for your reply and awesome work

**Comment by EQUALIT-CG** [comment]
Hi Volger

if the command from the screen shot is right then I'm happy to run it that way but iv never run that commend before etc etc so i have no idea what it does or if it works etc etc etc 

```
     environment:
     command: bash -c "node epic-games; node gog" 
#     command: bash -c "node epic-games; node gog; node steam; node Amazon prime; node Xbox Live Games with Gold" 

 ```

**Comment by vogler** [comment]
https://github.com/vogler/free-games-claimer/blob/07ce17f8e3d42869a7798cde81bb0e8f443f329c/Dockerfile#L80
That is the default command, i.e. run all scripts. By supplying a different command you override it. `bash -c ".."` is needed due to some Docker inconsistencies on when a shell is used.
