### ISSUE TITLE
Unraid Notify error - UNRAID DOCKER

### ISSUE THREAD

**Issue by globoxnoob** [vogler/free-games-claimer#87]
Greetings,

i have the problem that the notify parameter didnt work.
The rest of the docker works fine but the notifications gives an error in the log data.

![Bildschirm­foto 2023-03-04 um 16 11 19](https://user-images.githubusercontent.com/46114053/222914100-e223f2d1-2b25-4427-a66c-a62d1cbf69ae.png)

![Bildschirm­foto 2023-03-04 um 16 18 25](https://user-images.githubusercontent.com/46114053/222914225-0ba1ec07-fa30-4c89-980b-ae9d56ad833d.png)

Thanks for your help :)

**Comment by Nackophilz** [comment]
Hi!

The support for the unraid docker is not here, but on my page :)

And for your error it's normal you didn't configure anything in your variable (you didn't put your user-key nor your bot-key, we don't provide support for that, it's to be seen on Apprise :) )

**Comment by Nackophilz** [comment]
And also, if you don't use prime gaming, use the docker instructions to avoid checking it, it will avoid errors ;)

**Comment by globoxnoob** [comment]
Hello @Nackophilz ,

I put my variables (user key and bot token) in, but for this post I changed it to user-key@bot-token but the rest of the string is the same as i put my keys in.

Where exactly can I find the right walkthrough for the notify parameters (I've looked on the GitHub page from apprise but the config samples didn't work.

The prime gaming is activated to trigger an pushover event. In the regular config prime gaming is disabled like the informations on the Unraid docker install page.

Thanks for your help!

**Comment by Nackophilz** [comment]
Hi @globoxnoob,

To start, remove the " ' " you put on both sides of your settings, put directly the value you want.

This way Apprise will surely understand better what you are trying to ask him ;)

**Comment by vogler** [comment]
> To start, remove the " ' " you put on both sides of your settings, put directly the value you want.
> 
> This way Apprise will surely understand better what you are trying to ask him ;)

That shouldn't matter. Without quotes it may even fail if the URL has some character that needs escaping (not sure if this could happen).

**Comment by vogler** [comment]
@globoxnoob Try getting notifications to work first.

```
docker run --rm -it -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer apprise 'pover://...' -b 'hello world'
```

**Comment by Nackophilz** [comment]
With Unraid, you do not need to include the " ' " because it is a variable declared as such by Unraid. because it is a variable declared as such by Unraid.

If you declare the value with " ' ", Unraid will send the complete text with the " ' ". I'm pretty sure that the notification will work without this part :)

I just tested it with my Telegram notification, and I confirm that adding the " ' " makes everything go wrong

**Comment by vogler** [comment]
Ok, so another Unraid idiosyncracy. *distaste intensifies* 😄

**Comment by globoxnoob** [comment]
So i tested it without the " ' " and I got the same issue 

![image](https://user-images.githubusercontent.com/46114053/223325581-0bd7d4a8-4738-46ab-9b53-bae6d76e19ca.jpeg)

I took the flag ** pover://userkey@bottoken/Device **

It's the same way like the apprise guide. I'm a little bit confused 😵‍💫

**Comment by globoxnoob** [comment]
Why is this issue closed? 😰

**Comment by vogler** [comment]
Copy the line after `Command failed: ` and run it with apprise like I wrote above.
