### ISSUE TITLE
[discussion] Another headless approach

### ISSUE THREAD

**Issue by jackblk** [vogler/free-games-claimer#9]
Not really an issue, just a discussion.

After reading your repo a bit, I want to ask you some questions & contribute if possible. Can you let me know if you see captcha when running in headful state (with clean IP)?

If not, there's an approach I think we can consider: run a headful browser inside Docker with headless X11 server. That way, the browser is still headful, but for us it's still headless. I can help with this if the headful does not meet captcha.

**Comment by vogler** [comment]
Thanks! I was looking into this as well in https://github.com/vogler/free-games-claimer/issues/2#issuecomment-1027858090, but haven't tried it yet.
The captcha challenge only appears in headless mode, headful works fine.
Docker may also be a solution for #3.

Tabs I had open on the topic:
- https://github.com/microsoft/playwright/blob/main/docs/src/docker.md
- https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/desktop-lite.md
- https://stackoverflow.com/questions/36221215/using-vncserver-gui-application-virtual-display-in-docker-container
- https://stackoverflow.com/questions/28392949/running-chromium-inside-docker-gtk-cannot-open-display-0
- https://stackoverflow.com/questions/16296753/can-you-run-gui-applications-in-a-linux-docker-container
- https://blog.dangl.me/archive/running-fully-automated-e2e-tests-in-electron-in-a-docker-container-with-playwright/
- https://stackoverflow.com/questions/51883055/running-puppeteer-with-xfvb-headless-false

**Comment by jackblk** [comment]
Cool, so resourceful. From my experience I think it should work with Xfvb but I haven't tested yet.

Maybe this is a good place to start: https://github.com/drcrane/xvfb-alpine-docker

**Comment by viperdriver2000** [comment]
are there any news?

**Comment by jackblk** [comment]
@viperdriver2000 check out https://github.com/vogler/free-games-claimer/pull/11

**Comment by vogler** [comment]
Fixed by https://github.com/vogler/free-games-claimer/pull/11 (run non-headless in docker).
