### ISSUE TITLE
Unable to login anywhere in headless mode

### ISSUE THREAD

**Issue by Tinoo46** [vogler/free-games-claimer#91]
I tried to run the app in the docker on a ubuntu machine on a server. For me, it just timeouts when I enter PW and Email. It does not matter if I pass the email and pw as variables or not, it prompts me every time to type it manually. After entering pw and email it logs the following: 

```
page.waitForURL: Timeout 180000ms exceeded.
=========================== logs ===========================
waiting for navigation to "https://store.epicgames.com/en-US/free-games" until "load"
============================================================
    at file:///fgc/epic-games.js:95:16 {
  name: 'TimeoutError'
}
```

**Comment by vogler** [comment]
> For me, it just timeouts when I enter PW and Email.

Do you have the correct login? The script currently doesn't detect login errors.
You can just login in the browser to avoid mistakes.



> It does not matter if I pass the email and pw as variables or not, it prompts me every time to type it manually.

Then you're not setting the environment variables correctly.

**Comment by vogler** [comment]
> Unable to login anywhere in headless mode

Anywhere = you only tried epic games?
Why mention headless mode? Did you set `SHOW=0`? If not, it's not headless, you can see the browser via VNC.

**Comment by vogler** [comment]
Also, use ``` to enclose code/logs. Edited your post.

**Comment by Tinoo46** [comment]
> > Unable to login anywhere in headless mode
> 
> Anywhere = you only tried epic games? Why mention headless mode? Did you set `SHOW=0`? If not, it's not headless, you can see the browser via VNC.

I tried also gog. I tried it in the console. I did not need to mention headless mode.

**Comment by Tinoo46** [comment]
I tried it again and it worked :D
