### ISSUE TITLE
Trying to use it on windows

### ISSUE THREAD

**Issue by patlinGER** [vogler/free-games-claimer#95]
Hi there,

I installed docker on w11 but ended up with the  "wsl.exe --set-default-version 2" issue.

Then I uninstalled docker and used podman, but seems to have the same issue that it is not able to find connection. 

```
C:\Windows\System32>podman run --rm -it -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.4.2/libpod/_ping": dial unix ///run/podman/podman.sock: connect: An invalid argument was supplied.
```

Any advice?

**Comment by vogler** [comment]
What do you need WSL for? Last time I used Docker on Windows 10, it was pretty straightforward.

**Comment by patlinGER** [comment]
Docker is not able to start ... so I cannot use command
docker run --rm -it -p 6080:6080 -v fgc:/fgc/data --pull=always ghcr.io/vogler/free-games-claimer
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.4.2/libpod/_ping": dial unix ///run/podman/podman.sock: connect: An invalid argument was supplied.
Any advice?

@vogler
Owner
[vogler](https://github.com/vogler) commented [3 days ago](https://github.com/vogler/free-games-claimer/issues/95#issuecomment-1465046717)
What do you need WSL for? Last time I used Docker on Windows 10, it was pretty straightforward.

@patlinGER

 
Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
Add a quote, <Ctrl+Shift+.>Add code, <Ctrl+e>Add a link, <Ctrl+k>
Add a bulleted list, <Ctrl+Shift+8>Add a numbered list, <Ctrl+Shift+7>Add a task list, <Ctrl+Shift+l>
Directly mention a user or team
Reference an issue, pull request, or discussion
Add saved reply
Docker is not able to start ... so I cannot use command
Keine ausgewählt
Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).
Assignees
No one assigned
Labels
None yet
Projects
None yet
M

**Comment by vogler** [comment]
Something wrong with your setup then. Uninstall everything, install https://www.docker.com/products/docker-desktop/
