### ISSUE TITLE
Cannot Login into Epic Games

### ISSUE THREAD

**Issue by z4ch523** [vogler/free-games-claimer#99]
Hi I'm running fgc in docker and when I open the web UI it prompts me to login with epic games.
After I select login with google I get the message, that the browser ist not safe.
![image](https://user-images.githubusercontent.com/69817479/225824142-2931167c-a2bc-4735-9cac-9e788d792fa1.png)

**Comment by GothicIII** [comment]
I had the same problem. You need to create an Epic Account. You can do that from the account setting page, when logged in through google.

**Comment by z4ch523** [comment]
Thanks for the tip.
Do I have both ways to login afterwards?

And is this then still a bug in the program ?

**Comment by GothicIII** [comment]
No this project has nothing to do with it. It is a security check from google to prevent malicious intents.
